//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccessTimeResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccessTimeResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.AccessTimeResource", typeof(AccessTimeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lblAdd {
            get {
                return ResourceManager.GetString("lblAdd", resourceCulture);
            }
        }
        
        public static string lblAddNew {
            get {
                return ResourceManager.GetString("lblAddNew", resourceCulture);
            }
        }
        
        public static string lblDefaultTimezoneName {
            get {
                return ResourceManager.GetString("lblDefaultTimezoneName", resourceCulture);
            }
        }
        
        public static string lblDefaultNotUseTimezoneName {
            get {
                return ResourceManager.GetString("lblDefaultNotUseTimezoneName", resourceCulture);
            }
        }
        
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        public static string lblActive {
            get {
                return ResourceManager.GetString("lblActive", resourceCulture);
            }
        }
        
        public static string lblPassage {
            get {
                return ResourceManager.GetString("lblPassage", resourceCulture);
            }
        }
        
        public static string lblNormal {
            get {
                return ResourceManager.GetString("lblNormal", resourceCulture);
            }
        }
        
        public static string lblDeleteMultiple {
            get {
                return ResourceManager.GetString("lblDeleteMultiple", resourceCulture);
            }
        }
        
        public static string lblEndTime {
            get {
                return ResourceManager.GetString("lblEndTime", resourceCulture);
            }
        }
        
        public static string lblFriday {
            get {
                return ResourceManager.GetString("lblFriday", resourceCulture);
            }
        }
        
        public static string lblHolidayType1 {
            get {
                return ResourceManager.GetString("lblHolidayType1", resourceCulture);
            }
        }
        
        public static string lblHolidayType2 {
            get {
                return ResourceManager.GetString("lblHolidayType2", resourceCulture);
            }
        }
        
        public static string lblHolidayType3 {
            get {
                return ResourceManager.GetString("lblHolidayType3", resourceCulture);
            }
        }
        
        public static string lblMonday {
            get {
                return ResourceManager.GetString("lblMonday", resourceCulture);
            }
        }
        
        public static string lblRemark {
            get {
                return ResourceManager.GetString("lblRemark", resourceCulture);
            }
        }
        
        public static string lblSaturday {
            get {
                return ResourceManager.GetString("lblSaturday", resourceCulture);
            }
        }
        
        public static string lblStartTime {
            get {
                return ResourceManager.GetString("lblStartTime", resourceCulture);
            }
        }
        
        public static string lblSunday {
            get {
                return ResourceManager.GetString("lblSunday", resourceCulture);
            }
        }
        
        public static string lblThursday {
            get {
                return ResourceManager.GetString("lblThursday", resourceCulture);
            }
        }
        
        public static string lblTimezone {
            get {
                return ResourceManager.GetString("lblTimezone", resourceCulture);
            }
        }
        
        public static string lblTimezoneList {
            get {
                return ResourceManager.GetString("lblTimezoneList", resourceCulture);
            }
        }
        
        public static string lblTimezoneName {
            get {
                return ResourceManager.GetString("lblTimezoneName", resourceCulture);
            }
        }
        
        public static string lblTuesday {
            get {
                return ResourceManager.GetString("lblTuesday", resourceCulture);
            }
        }
        
        public static string lblUpdate {
            get {
                return ResourceManager.GetString("lblUpdate", resourceCulture);
            }
        }
        
        public static string lblWednesday {
            get {
                return ResourceManager.GetString("lblWednesday", resourceCulture);
            }
        }
        
        public static string msgCannotDeleteDefaultTz {
            get {
                return ResourceManager.GetString("msgCannotDeleteDefaultTz", resourceCulture);
            }
        }
        
        public static string msgCannotUpdateDefaultTz {
            get {
                return ResourceManager.GetString("msgCannotUpdateDefaultTz", resourceCulture);
            }
        }
        
        public static string msgCannotDeleteTimezone {
            get {
                return ResourceManager.GetString("msgCannotDeleteTimezone", resourceCulture);
            }
        }
        
        public static string msgLimitTimezone {
            get {
                return ResourceManager.GetString("msgLimitTimezone", resourceCulture);
            }
        }
        
        public static string lblAccess {
            get {
                return ResourceManager.GetString("lblAccess", resourceCulture);
            }
        }
        
        public static string lblAccessTime {
            get {
                return ResourceManager.GetString("lblAccessTime", resourceCulture);
            }
        }
        
        public static string msgNotFound {
            get {
                return ResourceManager.GetString("msgNotFound", resourceCulture);
            }
        }
    }
}
