//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DepartmentResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DepartmentResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.DepartmentResource", typeof(DepartmentResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lblAdd {
            get {
                return ResourceManager.GetString("lblAdd", resourceCulture);
            }
        }
        
        public static string lblAddNew {
            get {
                return ResourceManager.GetString("lblAddNew", resourceCulture);
            }
        }
        
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        public static string lblDeleteMultiple {
            get {
                return ResourceManager.GetString("lblDeleteMultiple", resourceCulture);
            }
        }
        
        public static string lblDepartment {
            get {
                return ResourceManager.GetString("lblDepartment", resourceCulture);
            }
        }
        
        public static string lblDepartmentList {
            get {
                return ResourceManager.GetString("lblDepartmentList", resourceCulture);
            }
        }
        
        public static string lblDepartmentName {
            get {
                return ResourceManager.GetString("lblDepartmentName", resourceCulture);
            }
        }
        
        public static string lblDepartmentNumber {
            get {
                return ResourceManager.GetString("lblDepartmentNumber", resourceCulture);
            }
        }
        
        public static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        public static string lblParentDepartment {
            get {
                return ResourceManager.GetString("lblParentDepartment", resourceCulture);
            }
        }
        
        public static string lblPleaseSelect {
            get {
                return ResourceManager.GetString("lblPleaseSelect", resourceCulture);
            }
        }
        
        public static string lblUpdate {
            get {
                return ResourceManager.GetString("lblUpdate", resourceCulture);
            }
        }
        
        public static string msgChangeDepartmentName {
            get {
                return ResourceManager.GetString("msgChangeDepartmentName", resourceCulture);
            }
        }
        
        public static string msgNotDeleted {
            get {
                return ResourceManager.GetString("msgNotDeleted", resourceCulture);
            }
        }
        
        public static string objDepartmentNumber {
            get {
                return ResourceManager.GetString("objDepartmentNumber", resourceCulture);
            }
        }
        
        public static string objParentDepartmentId {
            get {
                return ResourceManager.GetString("objParentDepartmentId", resourceCulture);
            }
        }
        
        public static string objParentId {
            get {
                return ResourceManager.GetString("objParentId", resourceCulture);
            }
        }
        
        public static string lblWgSetting {
            get {
                return ResourceManager.GetString("lblWgSetting", resourceCulture);
            }
        }
        
        public static string msgExportDepartmentList {
            get {
                return ResourceManager.GetString("msgExportDepartmentList", resourceCulture);
            }
        }
        
        public static string msgLogin {
            get {
                return ResourceManager.GetString("msgLogin", resourceCulture);
            }
        }
        
        public static string msgImportDepartmentList {
            get {
                return ResourceManager.GetString("msgImportDepartmentList", resourceCulture);
            }
        }
        
        public static string msgFailedToImport {
            get {
                return ResourceManager.GetString("msgFailedToImport", resourceCulture);
            }
        }
        
        public static string lblDepartmentUserCount {
            get {
                return ResourceManager.GetString("lblDepartmentUserCount", resourceCulture);
            }
        }
        
        public static string lblDepartmentManager {
            get {
                return ResourceManager.GetString("lblDepartmentManager", resourceCulture);
            }
        }
        
        public static string lblManagementDepartment {
            get {
                return ResourceManager.GetString("lblManagementDepartment", resourceCulture);
            }
        }
        
        public static string msgAssignUsersToDepartment {
            get {
                return ResourceManager.GetString("msgAssignUsersToDepartment", resourceCulture);
            }
        }
        
        public static string msgSuccessSetManager {
            get {
                return ResourceManager.GetString("msgSuccessSetManager", resourceCulture);
            }
        }
        
        public static string msgAssignDoors {
            get {
                return ResourceManager.GetString("msgAssignDoors", resourceCulture);
            }
        }
        
        public static string msgUnAssignDoors {
            get {
                return ResourceManager.GetString("msgUnAssignDoors", resourceCulture);
            }
        }
        
        public static string lblDepartmentAccessGroup {
            get {
                return ResourceManager.GetString("lblDepartmentAccessGroup", resourceCulture);
            }
        }
        
        public static string lblMaxNumberCheckout {
            get {
                return ResourceManager.GetString("lblMaxNumberCheckout", resourceCulture);
            }
        }
        
        public static string lblMaxPercentCheckout {
            get {
                return ResourceManager.GetString("lblMaxPercentCheckout", resourceCulture);
            }
        }
        
        public static string msgNotUnassignUserToDepartment {
            get {
                return ResourceManager.GetString("msgNotUnassignUserToDepartment", resourceCulture);
            }
        }
        
        public static string msgUnassignSuccess {
            get {
                return ResourceManager.GetString("msgUnassignSuccess", resourceCulture);
            }
        }
    }
}
