//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EventLogResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EventLogResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.EventLogResource", typeof(EventLogResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        public static string btnExport {
            get {
                return ResourceManager.GetString("btnExport", resourceCulture);
            }
        }
        
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        public static string IblSite2 {
            get {
                return ResourceManager.GetString("IblSite2", resourceCulture);
            }
        }
        
        public static string lblAccessDateFrom {
            get {
                return ResourceManager.GetString("lblAccessDateFrom", resourceCulture);
            }
        }
        
        public static string lblAccessDateTo {
            get {
                return ResourceManager.GetString("lblAccessDateTo", resourceCulture);
            }
        }
        
        public static string lblAccessDenied {
            get {
                return ResourceManager.GetString("lblAccessDenied", resourceCulture);
            }
        }
        
        public static string lblAccessTime {
            get {
                return ResourceManager.GetString("lblAccessTime", resourceCulture);
            }
        }
        
        public static string lblAccessTimeFrom {
            get {
                return ResourceManager.GetString("lblAccessTimeFrom", resourceCulture);
            }
        }
        
        public static string lblAccessTimeTo {
            get {
                return ResourceManager.GetString("lblAccessTimeTo", resourceCulture);
            }
        }
        
        public static string lblAntiPassbackError {
            get {
                return ResourceManager.GetString("lblAntiPassbackError", resourceCulture);
            }
        }
        
        public static string lblApplicationIsRunning {
            get {
                return ResourceManager.GetString("lblApplicationIsRunning", resourceCulture);
            }
        }
        
        public static string lblAppOpen {
            get {
                return ResourceManager.GetString("lblAppOpen", resourceCulture);
            }
        }
        
        public static string lblBirthDay {
            get {
                return ResourceManager.GetString("lblBirthDay", resourceCulture);
            }
        }
        
        public static string lblBreakfast {
            get {
                return ResourceManager.GetString("lblBreakfast", resourceCulture);
            }
        }
        
        public static string lblBuilding {
            get {
                return ResourceManager.GetString("lblBuilding", resourceCulture);
            }
        }
        
        public static string lblCard {
            get {
                return ResourceManager.GetString("lblCard", resourceCulture);
            }
        }
        
        public static string lblCardAccess {
            get {
                return ResourceManager.GetString("lblCardAccess", resourceCulture);
            }
        }
        
        public static string lblCardAndPassword {
            get {
                return ResourceManager.GetString("lblCardAndPassword", resourceCulture);
            }
        }
        
        public static string lblCardId {
            get {
                return ResourceManager.GetString("lblCardId", resourceCulture);
            }
        }
        
        public static string lblCardStatus {
            get {
                return ResourceManager.GetString("lblCardStatus", resourceCulture);
            }
        }
        
        public static string lblCardType {
            get {
                return ResourceManager.GetString("lblCardType", resourceCulture);
            }
        }
        
        public static string lblCommunicationFailed {
            get {
                return ResourceManager.GetString("lblCommunicationFailed", resourceCulture);
            }
        }
        
        public static string lblCommunicationSucceed {
            get {
                return ResourceManager.GetString("lblCommunicationSucceed", resourceCulture);
            }
        }
        
        public static string lblCompany {
            get {
                return ResourceManager.GetString("lblCompany", resourceCulture);
            }
        }
        
        public static string lblCompanyCode {
            get {
                return ResourceManager.GetString("lblCompanyCode", resourceCulture);
            }
        }
        
        public static string lblContact {
            get {
                return ResourceManager.GetString("lblContact", resourceCulture);
            }
        }
        
        public static string lblDepartment {
            get {
                return ResourceManager.GetString("lblDepartment", resourceCulture);
            }
        }
        
        public static string lblDevice {
            get {
                return ResourceManager.GetString("lblDevice", resourceCulture);
            }
        }
        
        public static string lblDeviceInstructionDeleteAllUser {
            get {
                return ResourceManager.GetString("lblDeviceInstructionDeleteAllUser", resourceCulture);
            }
        }
        
        public static string lblDeviceInstructionDeleteAllUserEvent {
            get {
                return ResourceManager.GetString("lblDeviceInstructionDeleteAllUserEvent", resourceCulture);
            }
        }
        
        public static string lblDeviceInstructionDeleteAllUserEvent1 {
            get {
                return ResourceManager.GetString("lblDeviceInstructionDeleteAllUserEvent1", resourceCulture);
            }
        }
        
        public static string lblDeviceInstructionForceClose {
            get {
                return ResourceManager.GetString("lblDeviceInstructionForceClose", resourceCulture);
            }
        }
        
        public static string lblDeviceInstructionForceOpen {
            get {
                return ResourceManager.GetString("lblDeviceInstructionForceOpen", resourceCulture);
            }
        }
        
        public static string lblDeviceInstructionOpen {
            get {
                return ResourceManager.GetString("lblDeviceInstructionOpen", resourceCulture);
            }
        }
        
        public static string lblDeviceInstructionRelease {
            get {
                return ResourceManager.GetString("lblDeviceInstructionRelease", resourceCulture);
            }
        }
        
        public static string lblDeviceInstructionReset {
            get {
                return ResourceManager.GetString("lblDeviceInstructionReset", resourceCulture);
            }
        }
        
        public static string lblDeviceInstructionSettime {
            get {
                return ResourceManager.GetString("lblDeviceInstructionSettime", resourceCulture);
            }
        }
        
        public static string lblDeviceIsRunning {
            get {
                return ResourceManager.GetString("lblDeviceIsRunning", resourceCulture);
            }
        }
        
        public static string lblDinner {
            get {
                return ResourceManager.GetString("lblDinner", resourceCulture);
            }
        }
        
        public static string lblDoorName {
            get {
                return ResourceManager.GetString("lblDoorName", resourceCulture);
            }
        }
        
        public static string lblDoorOpenManually {
            get {
                return ResourceManager.GetString("lblDoorOpenManually", resourceCulture);
            }
        }
        
        public static string lblEffectiveDateNotStarted {
            get {
                return ResourceManager.GetString("lblEffectiveDateNotStarted", resourceCulture);
            }
        }
        
        public static string lblEmpNum {
            get {
                return ResourceManager.GetString("lblEmpNum", resourceCulture);
            }
        }
        
        public static string lblEtcMeal {
            get {
                return ResourceManager.GetString("lblEtcMeal", resourceCulture);
            }
        }
        
        public static string lblEventDetail {
            get {
                return ResourceManager.GetString("lblEventDetail", resourceCulture);
            }
        }
        
        public static string lblEventLog {
            get {
                return ResourceManager.GetString("lblEventLog", resourceCulture);
            }
        }
        
        public static string lblEventType {
            get {
                return ResourceManager.GetString("lblEventType", resourceCulture);
            }
        }
        
        public static string lblExitApplication {
            get {
                return ResourceManager.GetString("lblExitApplication", resourceCulture);
            }
        }
        
        public static string lblExpirationDate {
            get {
                return ResourceManager.GetString("lblExpirationDate", resourceCulture);
            }
        }
        
        public static string lblExpiredCard {
            get {
                return ResourceManager.GetString("lblExpiredCard", resourceCulture);
            }
        }
        
        public static string lblExpiredCardAndPwd {
            get {
                return ResourceManager.GetString("lblExpiredCardAndPwd", resourceCulture);
            }
        }
        
        public static string lblExpiredPwd {
            get {
                return ResourceManager.GetString("lblExpiredPwd", resourceCulture);
            }
        }
        
        public static string lblFirmwareApplicationUpdate {
            get {
                return ResourceManager.GetString("lblFirmwareApplicationUpdate", resourceCulture);
            }
        }
        
        public static string lblFirmwareDownloadFailed {
            get {
                return ResourceManager.GetString("lblFirmwareDownloadFailed", resourceCulture);
            }
        }
        
        public static string lblIDX {
            get {
                return ResourceManager.GetString("lblIDX", resourceCulture);
            }
        }
        
        public static string lblInDevice {
            get {
                return ResourceManager.GetString("lblInDevice", resourceCulture);
            }
        }
        
        public static string lblInOut {
            get {
                return ResourceManager.GetString("lblInOut", resourceCulture);
            }
        }
        
        public static string lblWrongAccessType {
            get {
                return ResourceManager.GetString("lblWrongAccessType", resourceCulture);
            }
        }
        
        public static string lblInvalidDoor {
            get {
                return ResourceManager.GetString("lblInvalidDoor", resourceCulture);
            }
        }
        
        public static string lblIssueCount {
            get {
                return ResourceManager.GetString("lblIssueCount", resourceCulture);
            }
        }
        
        public static string lblKeyPadPassword {
            get {
                return ResourceManager.GetString("lblKeyPadPassword", resourceCulture);
            }
        }
        
        public static string lblLateNightSnack {
            get {
                return ResourceManager.GetString("lblLateNightSnack", resourceCulture);
            }
        }
        
        public static string lblLunch {
            get {
                return ResourceManager.GetString("lblLunch", resourceCulture);
            }
        }
        
        public static string lblMasterCardAccess {
            get {
                return ResourceManager.GetString("lblMasterCardAccess", resourceCulture);
            }
        }
        
        public static string lblMPRAuth {
            get {
                return ResourceManager.GetString("lblMPRAuth", resourceCulture);
            }
        }
        
        public static string lblMPRError {
            get {
                return ResourceManager.GetString("lblMPRError", resourceCulture);
            }
        }
        
        public static string lblMPRIntervalExpired {
            get {
                return ResourceManager.GetString("lblMPRIntervalExpired", resourceCulture);
            }
        }
        
        public static string lblNoAccessTime {
            get {
                return ResourceManager.GetString("lblNoAccessTime", resourceCulture);
            }
        }
        
        public static string lblNoDoorActiveTime {
            get {
                return ResourceManager.GetString("lblNoDoorActiveTime", resourceCulture);
            }
        }
        
        public static string lblNormalAccess {
            get {
                return ResourceManager.GetString("lblNormalAccess", resourceCulture);
            }
        }
        
        public static string lblNormalAccessMPR {
            get {
                return ResourceManager.GetString("lblNormalAccessMPR", resourceCulture);
            }
        }
        
        public static string lblNormalApp {
            get {
                return ResourceManager.GetString("lblNormalApp", resourceCulture);
            }
        }
        
        public static string lblNoUserAccessTime {
            get {
                return ResourceManager.GetString("lblNoUserAccessTime", resourceCulture);
            }
        }
        
        public static string lblOnlyAccessibleAtMealtime {
            get {
                return ResourceManager.GetString("lblOnlyAccessibleAtMealtime", resourceCulture);
            }
        }
        
        public static string lblOutDevice {
            get {
                return ResourceManager.GetString("lblOutDevice", resourceCulture);
            }
        }
        
        public static string lblPassageAccessTimeOff {
            get {
                return ResourceManager.GetString("lblPassageAccessTimeOff", resourceCulture);
            }
        }
        
        public static string lblPassageAccessTimeOn {
            get {
                return ResourceManager.GetString("lblPassageAccessTimeOn", resourceCulture);
            }
        }
        
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        public static string lblPaswordAccess {
            get {
                return ResourceManager.GetString("lblPaswordAccess", resourceCulture);
            }
        }
        
        public static string lblPowerApp {
            get {
                return ResourceManager.GetString("lblPowerApp", resourceCulture);
            }
        }
        
        public static string lblReport {
            get {
                return ResourceManager.GetString("lblReport", resourceCulture);
            }
        }
        
        public static string lblRID {
            get {
                return ResourceManager.GetString("lblRID", resourceCulture);
            }
        }
        
        public static string lblTimezone {
            get {
                return ResourceManager.GetString("lblTimezone", resourceCulture);
            }
        }
        
        public static string lblTimezoneSchedule {
            get {
                return ResourceManager.GetString("lblTimezoneSchedule", resourceCulture);
            }
        }
        
        public static string lblTryAccessInEmergencyClose {
            get {
                return ResourceManager.GetString("lblTryAccessInEmergencyClose", resourceCulture);
            }
        }
        
        public static string lblTryAccessInInvalidDoor {
            get {
                return ResourceManager.GetString("lblTryAccessInInvalidDoor", resourceCulture);
            }
        }
        
        public static string lblType {
            get {
                return ResourceManager.GetString("lblType", resourceCulture);
            }
        }
        
        public static string lblUnknown {
            get {
                return ResourceManager.GetString("lblUnknown", resourceCulture);
            }
        }
        
        public static string lblUnRegisteredID {
            get {
                return ResourceManager.GetString("lblUnRegisteredID", resourceCulture);
            }
        }
        
        public static string lblUnregisteredCardAndPwd {
            get {
                return ResourceManager.GetString("lblUnregisteredCardAndPwd", resourceCulture);
            }
        }
        
        public static string lblUnregisteredPwd {
            get {
                return ResourceManager.GetString("lblUnregisteredPwd", resourceCulture);
            }
        }
        
        public static string lblUpdateDeviceState {
            get {
                return ResourceManager.GetString("lblUpdateDeviceState", resourceCulture);
            }
        }
        
        public static string lblUserCode {
            get {
                return ResourceManager.GetString("lblUserCode", resourceCulture);
            }
        }
        
        public static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        public static string lblValidDoor {
            get {
                return ResourceManager.GetString("lblValidDoor", resourceCulture);
            }
        }
        
        public static string lblVerifyMode {
            get {
                return ResourceManager.GetString("lblVerifyMode", resourceCulture);
            }
        }
        
        public static string lblWrongIssueCount {
            get {
                return ResourceManager.GetString("lblWrongIssueCount", resourceCulture);
            }
        }
        
        public static string lblWrongPwd {
            get {
                return ResourceManager.GetString("lblWrongPwd", resourceCulture);
            }
        }
        
        public static string lblDeviceInstructionDeleteAllEvent {
            get {
                return ResourceManager.GetString("lblDeviceInstructionDeleteAllEvent", resourceCulture);
            }
        }
        
        public static string lblEventRecovery {
            get {
                return ResourceManager.GetString("lblEventRecovery", resourceCulture);
            }
        }
        
        public static string lblExpiredQrCode {
            get {
                return ResourceManager.GetString("lblExpiredQrCode", resourceCulture);
            }
        }
        
        public static string lblQR {
            get {
                return ResourceManager.GetString("lblQR", resourceCulture);
            }
        }
        
        public static string lblPassCode {
            get {
                return ResourceManager.GetString("lblPassCode", resourceCulture);
            }
        }
        
        public static string lblPressedButton {
            get {
                return ResourceManager.GetString("lblPressedButton", resourceCulture);
            }
        }
        
        public static string lblMeal1 {
            get {
                return ResourceManager.GetString("lblMeal1", resourceCulture);
            }
        }
        
        public static string lblMeal2 {
            get {
                return ResourceManager.GetString("lblMeal2", resourceCulture);
            }
        }
        
        public static string lblMeal10 {
            get {
                return ResourceManager.GetString("lblMeal10", resourceCulture);
            }
        }
        
        public static string lblMeal9 {
            get {
                return ResourceManager.GetString("lblMeal9", resourceCulture);
            }
        }
        
        public static string lblMeal8 {
            get {
                return ResourceManager.GetString("lblMeal8", resourceCulture);
            }
        }
        
        public static string lblMeal7 {
            get {
                return ResourceManager.GetString("lblMeal7", resourceCulture);
            }
        }
        
        public static string lblMeal6 {
            get {
                return ResourceManager.GetString("lblMeal6", resourceCulture);
            }
        }
        
        public static string lblMeal5 {
            get {
                return ResourceManager.GetString("lblMeal5", resourceCulture);
            }
        }
        
        public static string lblMeal4 {
            get {
                return ResourceManager.GetString("lblMeal4", resourceCulture);
            }
        }
        
        public static string lblMeal3 {
            get {
                return ResourceManager.GetString("lblMeal3", resourceCulture);
            }
        }
        
        public static string lblErrTwoFactorAuth {
            get {
                return ResourceManager.GetString("lblErrTwoFactorAuth", resourceCulture);
            }
        }
        
        public static string lblWrongQRcode {
            get {
                return ResourceManager.GetString("lblWrongQRcode", resourceCulture);
            }
        }
        
        public static string lblRetiredPerson {
            get {
                return ResourceManager.GetString("lblRetiredPerson", resourceCulture);
            }
        }
        
        public static string lblLostCard {
            get {
                return ResourceManager.GetString("lblLostCard", resourceCulture);
            }
        }
        
        public static string lblTransferCard {
            get {
                return ResourceManager.GetString("lblTransferCard", resourceCulture);
            }
        }
        
        public static string lblInvalidCard {
            get {
                return ResourceManager.GetString("lblInvalidCard", resourceCulture);
            }
        }
        
        public static string lblFace {
            get {
                return ResourceManager.GetString("lblFace", resourceCulture);
            }
        }
        
        public static string lblUnknownFace {
            get {
                return ResourceManager.GetString("lblUnknownFace", resourceCulture);
            }
        }
        
        public static string lblHFaceId {
            get {
                return ResourceManager.GetString("lblHFaceId", resourceCulture);
            }
        }
        
        public static string lblCameraResponseExpired {
            get {
                return ResourceManager.GetString("lblCameraResponseExpired", resourceCulture);
            }
        }
        
        public static string lblVehicleId {
            get {
                return ResourceManager.GetString("lblVehicleId", resourceCulture);
            }
        }
        
        public static string lblBodyTemperature {
            get {
                return ResourceManager.GetString("lblBodyTemperature", resourceCulture);
            }
        }
        
        public static string msgErrorLimitRangeDayExport {
            get {
                return ResourceManager.GetString("msgErrorLimitRangeDayExport", resourceCulture);
            }
        }
        
        public static string lblNotMatchCardType {
            get {
                return ResourceManager.GetString("lblNotMatchCardType", resourceCulture);
            }
        }
        
        public static string lblNormalVehicle {
            get {
                return ResourceManager.GetString("lblNormalVehicle", resourceCulture);
            }
        }
        
        public static string lblUnregisteredVehicle {
            get {
                return ResourceManager.GetString("lblUnregisteredVehicle", resourceCulture);
            }
        }
        
        public static string lblViolationRule2 {
            get {
                return ResourceManager.GetString("lblViolationRule2", resourceCulture);
            }
        }
        
        public static string lblViolationRule5 {
            get {
                return ResourceManager.GetString("lblViolationRule5", resourceCulture);
            }
        }
        
        public static string lblExceptionVehicle {
            get {
                return ResourceManager.GetString("lblExceptionVehicle", resourceCulture);
            }
        }
        
        public static string lblViolatedVehicle {
            get {
                return ResourceManager.GetString("lblViolatedVehicle", resourceCulture);
            }
        }
        
        public static string lblIdCertifiedVehicle {
            get {
                return ResourceManager.GetString("lblIdCertifiedVehicle", resourceCulture);
            }
        }
        
        public static string lblRemoteOperation {
            get {
                return ResourceManager.GetString("lblRemoteOperation", resourceCulture);
            }
        }
        
        public static string lblPlateNumber {
            get {
                return ResourceManager.GetString("lblPlateNumber", resourceCulture);
            }
        }
        
        public static string lblVehicleModel {
            get {
                return ResourceManager.GetString("lblVehicleModel", resourceCulture);
            }
        }
        
        public static string lblAntiPassbackNormal {
            get {
                return ResourceManager.GetString("lblAntiPassbackNormal", resourceCulture);
            }
        }
        
        public static string lblAntiPassbackDenied {
            get {
                return ResourceManager.GetString("lblAntiPassbackDenied", resourceCulture);
            }
        }
        
        public static string lblHighTemperature {
            get {
                return ResourceManager.GetString("lblHighTemperature", resourceCulture);
            }
        }
        
        public static string lblHighTemperatureDeny {
            get {
                return ResourceManager.GetString("lblHighTemperatureDeny", resourceCulture);
            }
        }
        
        public static string lblAlarmActivated {
            get {
                return ResourceManager.GetString("lblAlarmActivated", resourceCulture);
            }
        }
        
        public static string lblVein {
            get {
                return ResourceManager.GetString("lblVein", resourceCulture);
            }
        }
        
        public static string lblFireOn {
            get {
                return ResourceManager.GetString("lblFireOn", resourceCulture);
            }
        }
        
        public static string lblFireOff {
            get {
                return ResourceManager.GetString("lblFireOff", resourceCulture);
            }
        }
        
        public static string lblVehicleImage {
            get {
                return ResourceManager.GetString("lblVehicleImage", resourceCulture);
            }
        }
        
        public static string lblVehicleEventLog {
            get {
                return ResourceManager.GetString("lblVehicleEventLog", resourceCulture);
            }
        }
        
        public static string lblContinuousAbnormalAccess {
            get {
                return ResourceManager.GetString("lblContinuousAbnormalAccess", resourceCulture);
            }
        }
        
        public static string lblErrorReadingCard {
            get {
                return ResourceManager.GetString("lblErrorReadingCard", resourceCulture);
            }
        }
        
        public static string lblNFCPhone {
            get {
                return ResourceManager.GetString("lblNFCPhone", resourceCulture);
            }
        }
        
        public static string lblDuplicatedMealEvent {
            get {
                return ResourceManager.GetString("lblDuplicatedMealEvent", resourceCulture);
            }
        }
        
        public static string lblPlateRFID {
            get {
                return ResourceManager.GetString("lblPlateRFID", resourceCulture);
            }
        }
        
        public static string lblVehicleType {
            get {
                return ResourceManager.GetString("lblVehicleType", resourceCulture);
            }
        }
        
        public static string lblVehicleClassification {
            get {
                return ResourceManager.GetString("lblVehicleClassification", resourceCulture);
            }
        }
        
        public static string lblDeviceInstructionSendAllUser {
            get {
                return ResourceManager.GetString("lblDeviceInstructionSendAllUser", resourceCulture);
            }
        }
        
        public static string lblCameraAlarm {
            get {
                return ResourceManager.GetString("lblCameraAlarm", resourceCulture);
            }
        }
        
        public static string msgPushNotificationToManager {
            get {
                return ResourceManager.GetString("msgPushNotificationToManager", resourceCulture);
            }
        }
        
        public static string msgYourRequestExecuting {
            get {
                return ResourceManager.GetString("msgYourRequestExecuting", resourceCulture);
            }
        }
        
        public static string msgExportComplete {
            get {
                return ResourceManager.GetString("msgExportComplete", resourceCulture);
            }
        }
        
        public static string msgExportError {
            get {
                return ResourceManager.GetString("msgExportError", resourceCulture);
            }
        }
        
        public static string lblVehicleName {
            get {
                return ResourceManager.GetString("lblVehicleName", resourceCulture);
            }
        }
        
        public static string lblNoMealPermission {
            get {
                return ResourceManager.GetString("lblNoMealPermission", resourceCulture);
            }
        }
        
        public static string msgLimitAllowExport {
            get {
                return ResourceManager.GetString("msgLimitAllowExport", resourceCulture);
            }
        }
        
        public static string lblWorkType {
            get {
                return ResourceManager.GetString("lblWorkType", resourceCulture);
            }
        }
        
        public static string lblEventMemo {
            get {
                return ResourceManager.GetString("lblEventMemo", resourceCulture);
            }
        }
        
        public static string lblFingerPrint {
            get {
                return ResourceManager.GetString("lblFingerPrint", resourceCulture);
            }
        }
        
        public static string lblSelfDevice {
            get {
                return ResourceManager.GetString("lblSelfDevice", resourceCulture);
            }
        }
        
        public static string lblPowerDevice {
            get {
                return ResourceManager.GetString("lblPowerDevice", resourceCulture);
            }
        }
        
        public static string lblNormalDevice {
            get {
                return ResourceManager.GetString("lblNormalDevice", resourceCulture);
            }
        }
        
        public static string lblTimezoneDevice {
            get {
                return ResourceManager.GetString("lblTimezoneDevice", resourceCulture);
            }
        }
        
        public static string lblLFaceId {
            get {
                return ResourceManager.GetString("lblLFaceId", resourceCulture);
            }
        }
        
        public static string lblEbknFaceId {
            get {
                return ResourceManager.GetString("lblEbknFaceId", resourceCulture);
            }
        }
        
        public static string lblEbknFingerprint {
            get {
                return ResourceManager.GetString("lblEbknFingerprint", resourceCulture);
            }
        }
        
        public static string lblBioFace {
            get {
                return ResourceManager.GetString("lblBioFace", resourceCulture);
            }
        }
        
        public static string lblAratekFingerPrint {
            get {
                return ResourceManager.GetString("lblAratekFingerPrint", resourceCulture);
            }
        }
        
        public static string lblRemark1 {
            get {
                return ResourceManager.GetString("lblRemark1", resourceCulture);
            }
        }
        
        public static string lblRemark2 {
            get {
                return ResourceManager.GetString("lblRemark2", resourceCulture);
            }
        }
        
        public static string lblSite2 {
            get {
                return ResourceManager.GetString("lblSite2", resourceCulture);
            }
        }
        
        public static string lblDCFaceId {
            get {
                return ResourceManager.GetString("lblDCFaceId", resourceCulture);
            }
        }
        
        public static string lblVNID {
            get {
                return ResourceManager.GetString("lblVNID", resourceCulture);
            }
        }
        
        public static string lblTBFace {
            get {
                return ResourceManager.GetString("lblTBFace", resourceCulture);
            }
        }
        
        public static string lblVehicleMotoBikeId {
            get {
                return ResourceManager.GetString("lblVehicleMotoBikeId", resourceCulture);
            }
        }
        
        public static string lblTBFingerprint {
            get {
                return ResourceManager.GetString("lblTBFingerprint", resourceCulture);
            }
        }
    }
}
