//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MailTemplateResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailTemplateResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.MailTemplateResource", typeof(MailTemplateResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string titleRequestApproval {
            get {
                return ResourceManager.GetString("titleRequestApproval", resourceCulture);
            }
        }
        
        public static string titleApprovalVisit {
            get {
                return ResourceManager.GetString("titleApprovalVisit", resourceCulture);
            }
        }
        
        public static string titleRejectVisit {
            get {
                return ResourceManager.GetString("titleRejectVisit", resourceCulture);
            }
        }
        
        public static string titleLinkRegisterVisit {
            get {
                return ResourceManager.GetString("titleLinkRegisterVisit", resourceCulture);
            }
        }
        
        public static string titleWelcomeUserEmail {
            get {
                return ResourceManager.GetString("titleWelcomeUserEmail", resourceCulture);
            }
        }
        
        public static string titleSendPassCodeEmail {
            get {
                return ResourceManager.GetString("titleSendPassCodeEmail", resourceCulture);
            }
        }
        
        public static string descriptionRequestApproval {
            get {
                return ResourceManager.GetString("descriptionRequestApproval", resourceCulture);
            }
        }
        
        public static string descriptionApprovalVisit {
            get {
                return ResourceManager.GetString("descriptionApprovalVisit", resourceCulture);
            }
        }
        
        public static string descriptionRejectVisit {
            get {
                return ResourceManager.GetString("descriptionRejectVisit", resourceCulture);
            }
        }
        
        public static string descriptionLinkRegisterVisit {
            get {
                return ResourceManager.GetString("descriptionLinkRegisterVisit", resourceCulture);
            }
        }
        
        public static string descriptionWelcomeUserEmail {
            get {
                return ResourceManager.GetString("descriptionWelcomeUserEmail", resourceCulture);
            }
        }
        
        public static string descriptionSendPassCodeEmail {
            get {
                return ResourceManager.GetString("descriptionSendPassCodeEmail", resourceCulture);
            }
        }
        
        public static string titleSendQREmail {
            get {
                return ResourceManager.GetString("titleSendQREmail", resourceCulture);
            }
        }
        
        public static string descriptionSendQREmail {
            get {
                return ResourceManager.GetString("descriptionSendQREmail", resourceCulture);
            }
        }
        
        public static string titleWelcomeMailForManager {
            get {
                return ResourceManager.GetString("titleWelcomeMailForManager", resourceCulture);
            }
        }
        
        public static string descriptionWelcomeMailForManager {
            get {
                return ResourceManager.GetString("descriptionWelcomeMailForManager", resourceCulture);
            }
        }
        
        public static string titleWelcomeMailForAdmin {
            get {
                return ResourceManager.GetString("titleWelcomeMailForAdmin", resourceCulture);
            }
        }
        
        public static string descriptionWelcomeMailForAdmin {
            get {
                return ResourceManager.GetString("descriptionWelcomeMailForAdmin", resourceCulture);
            }
        }
        
        public static string descriptionCompanyName {
            get {
                return ResourceManager.GetString("descriptionCompanyName", resourceCulture);
            }
        }
        
        public static string descriptionVisitorName {
            get {
                return ResourceManager.GetString("descriptionVisitorName", resourceCulture);
            }
        }
        
        public static string descriptionApprovalName {
            get {
                return ResourceManager.GetString("descriptionApprovalName", resourceCulture);
            }
        }
        
        public static string descriptionApprovalCount {
            get {
                return ResourceManager.GetString("descriptionApprovalCount", resourceCulture);
            }
        }
        
        public static string descriptionVisitTargetName {
            get {
                return ResourceManager.GetString("descriptionVisitTargetName", resourceCulture);
            }
        }
        
        public static string descriptionVisitLink {
            get {
                return ResourceManager.GetString("descriptionVisitLink", resourceCulture);
            }
        }
        
        public static string descriptionAddress {
            get {
                return ResourceManager.GetString("descriptionAddress", resourceCulture);
            }
        }
        
        public static string descriptionImgVisit1 {
            get {
                return ResourceManager.GetString("descriptionImgVisit1", resourceCulture);
            }
        }
        
        public static string descriptionImgVisit2 {
            get {
                return ResourceManager.GetString("descriptionImgVisit2", resourceCulture);
            }
        }
        
        public static string descriptionNoteScanQR {
            get {
                return ResourceManager.GetString("descriptionNoteScanQR", resourceCulture);
            }
        }
        
        public static string descriptionTextPowerBy {
            get {
                return ResourceManager.GetString("descriptionTextPowerBy", resourceCulture);
            }
        }
        
        public static string descriptionTextInvite {
            get {
                return ResourceManager.GetString("descriptionTextInvite", resourceCulture);
            }
        }
        
        public static string descriptionLogoSquare {
            get {
                return ResourceManager.GetString("descriptionLogoSquare", resourceCulture);
            }
        }
        
        public static string descriptionVisitorPhone {
            get {
                return ResourceManager.GetString("descriptionVisitorPhone", resourceCulture);
            }
        }
        
        public static string descriptionVisitReason {
            get {
                return ResourceManager.GetString("descriptionVisitReason", resourceCulture);
            }
        }
        
        public static string descriptionVisitUserCreate {
            get {
                return ResourceManager.GetString("descriptionVisitUserCreate", resourceCulture);
            }
        }
        
        public static string descriptionVisitUserReject {
            get {
                return ResourceManager.GetString("descriptionVisitUserReject", resourceCulture);
            }
        }
        
        public static string descriptionVisitTimeAccess {
            get {
                return ResourceManager.GetString("descriptionVisitTimeAccess", resourceCulture);
            }
        }
        
        public static string descriptionVisitEmail {
            get {
                return ResourceManager.GetString("descriptionVisitEmail", resourceCulture);
            }
        }
        
        public static string descriptionVisitLinkQrCode {
            get {
                return ResourceManager.GetString("descriptionVisitLinkQrCode", resourceCulture);
            }
        }
        
        public static string descriptionLogoImageId {
            get {
                return ResourceManager.GetString("descriptionLogoImageId", resourceCulture);
            }
        }
        
        public static string descriptionImageQRCode {
            get {
                return ResourceManager.GetString("descriptionImageQRCode", resourceCulture);
            }
        }
        
        public static string descriptionAndroidIcon {
            get {
                return ResourceManager.GetString("descriptionAndroidIcon", resourceCulture);
            }
        }
        
        public static string descriptionIosIcon {
            get {
                return ResourceManager.GetString("descriptionIosIcon", resourceCulture);
            }
        }
        
        public static string descriptionUserNameWelcome {
            get {
                return ResourceManager.GetString("descriptionUserNameWelcome", resourceCulture);
            }
        }
        
        public static string descriptionEmailWelcome {
            get {
                return ResourceManager.GetString("descriptionEmailWelcome", resourceCulture);
            }
        }
        
        public static string descriptionToken {
            get {
                return ResourceManager.GetString("descriptionToken", resourceCulture);
            }
        }
        
        public static string descriptionUserName {
            get {
                return ResourceManager.GetString("descriptionUserName", resourceCulture);
            }
        }
        
        public static string descriptionPassCode {
            get {
                return ResourceManager.GetString("descriptionPassCode", resourceCulture);
            }
        }
        
        public static string descriptionPasswordDefault {
            get {
                return ResourceManager.GetString("descriptionPasswordDefault", resourceCulture);
            }
        }
        
        public static string descriptionFireCrackerIcon {
            get {
                return ResourceManager.GetString("descriptionFireCrackerIcon", resourceCulture);
            }
        }
        
        public static string descriptionGetItOnGooglePlayIcon {
            get {
                return ResourceManager.GetString("descriptionGetItOnGooglePlayIcon", resourceCulture);
            }
        }
        
        public static string descriptionDownloadOnAppStoreIcon {
            get {
                return ResourceManager.GetString("descriptionDownloadOnAppStoreIcon", resourceCulture);
            }
        }
        
        public static string descriptionCompanyLogo {
            get {
                return ResourceManager.GetString("descriptionCompanyLogo", resourceCulture);
            }
        }
        
        public static string descriptionTimeIcon {
            get {
                return ResourceManager.GetString("descriptionTimeIcon", resourceCulture);
            }
        }
        
        public static string descriptionLocationIcon {
            get {
                return ResourceManager.GetString("descriptionLocationIcon", resourceCulture);
            }
        }
        
        public static string descriptionDoorIcon {
            get {
                return ResourceManager.GetString("descriptionDoorIcon", resourceCulture);
            }
        }
        
        public static string descriptionDoorListVisitAccess {
            get {
                return ResourceManager.GetString("descriptionDoorListVisitAccess", resourceCulture);
            }
        }
        
        public static string descriptionPhoneIcon {
            get {
                return ResourceManager.GetString("descriptionPhoneIcon", resourceCulture);
            }
        }
        
        public static string descriptionContactVisitTarget {
            get {
                return ResourceManager.GetString("descriptionContactVisitTarget", resourceCulture);
            }
        }
        
        public static string titleNotifyOverDueBook {
            get {
                return ResourceManager.GetString("titleNotifyOverDueBook", resourceCulture);
            }
        }
        
        public static string descriptionNotifyOverDueBook {
            get {
                return ResourceManager.GetString("descriptionNotifyOverDueBook", resourceCulture);
            }
        }
        
        public static string descriptionUserNameBorrowBook {
            get {
                return ResourceManager.GetString("descriptionUserNameBorrowBook", resourceCulture);
            }
        }
        
        public static string descriptionBookNameBorrowBook {
            get {
                return ResourceManager.GetString("descriptionBookNameBorrowBook", resourceCulture);
            }
        }
        
        public static string descriptionBorrowDateBorrowBook {
            get {
                return ResourceManager.GetString("descriptionBorrowDateBorrowBook", resourceCulture);
            }
        }
        
        public static string descriptionDeadlineDateBorrowBook {
            get {
                return ResourceManager.GetString("descriptionDeadlineDateBorrowBook", resourceCulture);
            }
        }
        
        public static string descriptionNameOfUser {
            get {
                return ResourceManager.GetString("descriptionNameOfUser", resourceCulture);
            }
        }
        
        public static string descriptionLeaveType {
            get {
                return ResourceManager.GetString("descriptionLeaveType", resourceCulture);
            }
        }
        
        public static string descriptionLeaveFromDate {
            get {
                return ResourceManager.GetString("descriptionLeaveFromDate", resourceCulture);
            }
        }
        
        public static string descriptionLeaveToDate {
            get {
                return ResourceManager.GetString("descriptionLeaveToDate", resourceCulture);
            }
        }
        
        public static string descriptionLeaveReason {
            get {
                return ResourceManager.GetString("descriptionLeaveReason", resourceCulture);
            }
        }
        
        public static string descriptionLeaveRejectReason {
            get {
                return ResourceManager.GetString("descriptionLeaveRejectReason", resourceCulture);
            }
        }
        
        public static string titleLeaveRequestReview {
            get {
                return ResourceManager.GetString("titleLeaveRequestReview", resourceCulture);
            }
        }
        
        public static string descriptionLeaveRequestReview {
            get {
                return ResourceManager.GetString("descriptionLeaveRequestReview", resourceCulture);
            }
        }
        
        public static string descriptionLeaveRequestLink {
            get {
                return ResourceManager.GetString("descriptionLeaveRequestLink", resourceCulture);
            }
        }
        
        public static string descriptionManagerApproval {
            get {
                return ResourceManager.GetString("descriptionManagerApproval", resourceCulture);
            }
        }
        
        public static string descriptionLeaveUserName {
            get {
                return ResourceManager.GetString("descriptionLeaveUserName", resourceCulture);
            }
        }
        
        public static string titleLeaveRequestApproval {
            get {
                return ResourceManager.GetString("titleLeaveRequestApproval", resourceCulture);
            }
        }
        
        public static string descriptionLeaveRequestApproval {
            get {
                return ResourceManager.GetString("descriptionLeaveRequestApproval", resourceCulture);
            }
        }
        
        public static string titleLeaveRequestReject {
            get {
                return ResourceManager.GetString("titleLeaveRequestReject", resourceCulture);
            }
        }
        
        public static string descriptionLeaveRequestReject {
            get {
                return ResourceManager.GetString("descriptionLeaveRequestReject", resourceCulture);
            }
        }
        
        public static string lblEmailTemplate {
            get {
                return ResourceManager.GetString("lblEmailTemplate", resourceCulture);
            }
        }
        
        public static string lblNoteScanQR {
            get {
                return ResourceManager.GetString("lblNoteScanQR", resourceCulture);
            }
        }
        
        public static string lblTextInvite {
            get {
                return ResourceManager.GetString("lblTextInvite", resourceCulture);
            }
        }
        
        public static string lblTextPowerBy {
            get {
                return ResourceManager.GetString("lblTextPowerBy", resourceCulture);
            }
        }
        
        public static string SubjectCardQRTemplate {
            get {
                return ResourceManager.GetString("SubjectCardQRTemplate", resourceCulture);
            }
        }
        
        public static string titleQRCardTemplate {
            get {
                return ResourceManager.GetString("titleQRCardTemplate", resourceCulture);
            }
        }
        
        public static string titleMonitoringTemplate {
            get {
                return ResourceManager.GetString("titleMonitoringTemplate", resourceCulture);
            }
        }
        
        public static string descriptionMonitoringTemplate {
            get {
                return ResourceManager.GetString("descriptionMonitoringTemplate", resourceCulture);
            }
        }
        
        public static string descriptionVisitorAvatar {
            get {
                return ResourceManager.GetString("descriptionVisitorAvatar", resourceCulture);
            }
        }
        
        public static string descriptionResultCheckin {
            get {
                return ResourceManager.GetString("descriptionResultCheckin", resourceCulture);
            }
        }
        
        public static string descriptionVisitorPosition {
            get {
                return ResourceManager.GetString("descriptionVisitorPosition", resourceCulture);
            }
        }
    }
}
