//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.SystemResource", typeof(SystemResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string PlugInCommon {
            get {
                return ResourceManager.GetString("PlugInCommon", resourceCulture);
            }
        }
        
        public static string PlugInCardIssuing {
            get {
                return ResourceManager.GetString("PlugInCardIssuing", resourceCulture);
            }
        }
        
        public static string PlugInAccessControl {
            get {
                return ResourceManager.GetString("PlugInAccessControl", resourceCulture);
            }
        }
        
        public static string PlugInTimeAttendance {
            get {
                return ResourceManager.GetString("PlugInTimeAttendance", resourceCulture);
            }
        }
        
        public static string PlugInVisitManagement {
            get {
                return ResourceManager.GetString("PlugInVisitManagement", resourceCulture);
            }
        }
        
        public static string PlugInCanteenManagement {
            get {
                return ResourceManager.GetString("PlugInCanteenManagement", resourceCulture);
            }
        }
        
        public static string PlugInQrCode {
            get {
                return ResourceManager.GetString("PlugInQrCode", resourceCulture);
            }
        }
        
        public static string PlugInScreenMessage {
            get {
                return ResourceManager.GetString("PlugInScreenMessage", resourceCulture);
            }
        }
        
        public static string PlugInPassCode {
            get {
                return ResourceManager.GetString("PlugInPassCode", resourceCulture);
            }
        }
        
        public static string PlugInCameraPlugIn {
            get {
                return ResourceManager.GetString("PlugInCameraPlugIn", resourceCulture);
            }
        }
        
        public static string PlugInArmyManagement {
            get {
                return ResourceManager.GetString("PlugInArmyManagement", resourceCulture);
            }
        }
        
        public static string DescPlugInAccessControl {
            get {
                return ResourceManager.GetString("DescPlugInAccessControl", resourceCulture);
            }
        }
        
        public static string DescPlugInArmyManagement {
            get {
                return ResourceManager.GetString("DescPlugInArmyManagement", resourceCulture);
            }
        }
        
        public static string DescPlugInCameraPlugIn {
            get {
                return ResourceManager.GetString("DescPlugInCameraPlugIn", resourceCulture);
            }
        }
        
        public static string DescPlugInCanteenManagement {
            get {
                return ResourceManager.GetString("DescPlugInCanteenManagement", resourceCulture);
            }
        }
        
        public static string DescPlugInCardIssuing {
            get {
                return ResourceManager.GetString("DescPlugInCardIssuing", resourceCulture);
            }
        }
        
        public static string DescPlugInCommon {
            get {
                return ResourceManager.GetString("DescPlugInCommon", resourceCulture);
            }
        }
        
        public static string DescPlugInPassCode {
            get {
                return ResourceManager.GetString("DescPlugInPassCode", resourceCulture);
            }
        }
        
        public static string DescPlugInQrCode {
            get {
                return ResourceManager.GetString("DescPlugInQrCode", resourceCulture);
            }
        }
        
        public static string DescPlugInScreenMessage {
            get {
                return ResourceManager.GetString("DescPlugInScreenMessage", resourceCulture);
            }
        }
        
        public static string DescPlugInTimeAttendance {
            get {
                return ResourceManager.GetString("DescPlugInTimeAttendance", resourceCulture);
            }
        }
        
        public static string DescPlugInVisitManagement {
            get {
                return ResourceManager.GetString("DescPlugInVisitManagement", resourceCulture);
            }
        }
        
        public static string PlugInEventManagement {
            get {
                return ResourceManager.GetString("PlugInEventManagement", resourceCulture);
            }
        }
        
        public static string DescPlugInEventManagement {
            get {
                return ResourceManager.GetString("DescPlugInEventManagement", resourceCulture);
            }
        }
        
        public static string DescPlugInVehiclePlugIn {
            get {
                return ResourceManager.GetString("DescPlugInVehiclePlugIn", resourceCulture);
            }
        }
        
        public static string PlugInVehiclePlugIn {
            get {
                return ResourceManager.GetString("PlugInVehiclePlugIn", resourceCulture);
            }
        }
        
        public static string DescPlugInCovid19 {
            get {
                return ResourceManager.GetString("DescPlugInCovid19", resourceCulture);
            }
        }
        
        public static string PlugInCovid19 {
            get {
                return ResourceManager.GetString("PlugInCovid19", resourceCulture);
            }
        }
        
        public static string PlugInBuildingMaster {
            get {
                return ResourceManager.GetString("PlugInBuildingMaster", resourceCulture);
            }
        }
        
        public static string DescPlugInBuildingMaster {
            get {
                return ResourceManager.GetString("DescPlugInBuildingMaster", resourceCulture);
            }
        }
        
        public static string PlugInCameraPlugIn2 {
            get {
                return ResourceManager.GetString("PlugInCameraPlugIn2", resourceCulture);
            }
        }
        
        public static string DescPlugInCameraPlugIn2 {
            get {
                return ResourceManager.GetString("DescPlugInCameraPlugIn2", resourceCulture);
            }
        }
        
        public static string PlugInElevator {
            get {
                return ResourceManager.GetString("PlugInElevator", resourceCulture);
            }
        }
        
        public static string DescPlugInElevator {
            get {
                return ResourceManager.GetString("DescPlugInElevator", resourceCulture);
            }
        }
        
        public static string PlugInVideoDoorbell {
            get {
                return ResourceManager.GetString("PlugInVideoDoorbell", resourceCulture);
            }
        }
        
        public static string DescPlugInVideoDoorbell {
            get {
                return ResourceManager.GetString("DescPlugInVideoDoorbell", resourceCulture);
            }
        }
        
        public static string PlugInFaceRecognition {
            get {
                return ResourceManager.GetString("PlugInFaceRecognition", resourceCulture);
            }
        }
        
        public static string DescPlugInFaceRecognition {
            get {
                return ResourceManager.GetString("DescPlugInFaceRecognition", resourceCulture);
            }
        }
        
        public static string PlugInVein {
            get {
                return ResourceManager.GetString("PlugInVein", resourceCulture);
            }
        }
        
        public static string DescPlugInVein {
            get {
                return ResourceManager.GetString("DescPlugInVein", resourceCulture);
            }
        }
        
        public static string PlugInLibraryManagement {
            get {
                return ResourceManager.GetString("PlugInLibraryManagement", resourceCulture);
            }
        }
        
        public static string DescPlugInLibraryManagement {
            get {
                return ResourceManager.GetString("DescPlugInLibraryManagement", resourceCulture);
            }
        }
        
        public static string PlugInUnKnownPersonManagement {
            get {
                return ResourceManager.GetString("PlugInUnKnownPersonManagement", resourceCulture);
            }
        }
        
        public static string DescPlugInUnknownPersonManagement {
            get {
                return ResourceManager.GetString("DescPlugInUnknownPersonManagement", resourceCulture);
            }
        }
        
        public static string PlugInFingerPrint {
            get {
                return ResourceManager.GetString("PlugInFingerPrint", resourceCulture);
            }
        }
        
        public static string DescPlugInFingerPrint {
            get {
                return ResourceManager.GetString("DescPlugInFingerPrint", resourceCulture);
            }
        }
        
        public static string PlugInKakao {
            get {
                return ResourceManager.GetString("PlugInKakao", resourceCulture);
            }
        }
        
        public static string DescPlugInKakao {
            get {
                return ResourceManager.GetString("DescPlugInKakao", resourceCulture);
            }
        }
        
        public static string PlugInDeptAcGrpConn {
            get {
                return ResourceManager.GetString("PlugInDeptAcGrpConn", resourceCulture);
            }
        }
        
        public static string DescPlugInDeptAcGrpConn {
            get {
                return ResourceManager.GetString("DescPlugInDeptAcGrpConn", resourceCulture);
            }
        }
        
        public static string PlugInDepartmentAccessLevel {
            get {
                return ResourceManager.GetString("PlugInDepartmentAccessLevel", resourceCulture);
            }
        }
        
        public static string DescPlugInDepartmentAccessLevel {
            get {
                return ResourceManager.GetString("DescPlugInDepartmentAccessLevel", resourceCulture);
            }
        }
        
        public static string DescPlugInCustomizeLanguage {
            get {
                return ResourceManager.GetString("DescPlugInCustomizeLanguage", resourceCulture);
            }
        }
        
        public static string PlugInCustomizeLanguage {
            get {
                return ResourceManager.GetString("PlugInCustomizeLanguage", resourceCulture);
            }
        }
    }
}
