//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TransactionResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransactionResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.TransactionResource", typeof(TransactionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string addType {
            get {
                return ResourceManager.GetString("addType", resourceCulture);
            }
        }
        public static string deleteType {
            get {
                return ResourceManager.GetString("deleteType", resourceCulture);
            }
        }
        public static string visitType {
            get {
                return ResourceManager.GetString("visitType", resourceCulture);
            }
        }
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        public static string UpdatePointSuccess {
            get {
                return ResourceManager.GetString("UpdatePointSuccess", resourceCulture);
            }
        }
        public static string UpdatePointFailed {
            get {
                return ResourceManager.GetString("UpdatePointFailed", resourceCulture);
            }
        }
        public static string UpdateUsePointSuccess {
            get {
                return ResourceManager.GetString("UpdateUsePointSuccess", resourceCulture);
            }
        }
        public static string MessageUpdateFailed {
            get {
                return ResourceManager.GetString("MessageUpdateFailed", resourceCulture);
            }
        }
    }
}
