//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.UserResource", typeof(UserResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lblAccessGroupId {
            get {
                return ResourceManager.GetString("lblAccessGroupId", resourceCulture);
            }
        }
        
        public static string lblAccessLevel {
            get {
                return ResourceManager.GetString("lblAccessLevel", resourceCulture);
            }
        }
        
        public static string lblAddNew {
            get {
                return ResourceManager.GetString("lblAddNew", resourceCulture);
            }
        }
        
        public static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        public static string lblAvatar {
            get {
                return ResourceManager.GetString("lblAvatar", resourceCulture);
            }
        }
        
        public static string lblCardId {
            get {
                return ResourceManager.GetString("lblCardId", resourceCulture);
            }
        }
        
        public static string lblCardStatus {
            get {
                return ResourceManager.GetString("lblCardStatus", resourceCulture);
            }
        }
        
        public static string lblCardType {
            get {
                return ResourceManager.GetString("lblCardType", resourceCulture);
            }
        }
        
        public static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        public static string lblClear {
            get {
                return ResourceManager.GetString("lblClear", resourceCulture);
            }
        }
        
        public static string lblCompanyPhone {
            get {
                return ResourceManager.GetString("lblCompanyPhone", resourceCulture);
            }
        }
        
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        public static string lblDeleteMultiple {
            get {
                return ResourceManager.GetString("lblDeleteMultiple", resourceCulture);
            }
        }
        
        public static string lblDepartment {
            get {
                return ResourceManager.GetString("lblDepartment", resourceCulture);
            }
        }
        
        public static string lblDepartmentName {
            get {
                return ResourceManager.GetString("lblDepartmentName", resourceCulture);
            }
        }
        
        public static string lblDepartmentNumber {
            get {
                return ResourceManager.GetString("lblDepartmentNumber", resourceCulture);
            }
        }
        
        public static string lblDetails {
            get {
                return ResourceManager.GetString("lblDetails", resourceCulture);
            }
        }
        
        public static string lblDeviceAuthority {
            get {
                return ResourceManager.GetString("lblDeviceAuthority", resourceCulture);
            }
        }
        
        public static string lblEffectiveDate {
            get {
                return ResourceManager.GetString("lblEffectiveDate", resourceCulture);
            }
        }
        
        public static string lblEmergencyPassword {
            get {
                return ResourceManager.GetString("lblEmergencyPassword", resourceCulture);
            }
        }
        
        public static string lblEmployeeNumber {
            get {
                return ResourceManager.GetString("lblEmployeeNumber", resourceCulture);
            }
        }
        
        public static string lblErrorData {
            get {
                return ResourceManager.GetString("lblErrorData", resourceCulture);
            }
        }
        
        public static string lblExpiredDate {
            get {
                return ResourceManager.GetString("lblExpiredDate", resourceCulture);
            }
        }
        
        public static string lblExport {
            get {
                return ResourceManager.GetString("lblExport", resourceCulture);
            }
        }
        
        public static string lblFemale {
            get {
                return ResourceManager.GetString("lblFemale", resourceCulture);
            }
        }
        
        public static string lblFirstName {
            get {
                return ResourceManager.GetString("lblFirstName", resourceCulture);
            }
        }
        
        public static string lblGender {
            get {
                return ResourceManager.GetString("lblGender", resourceCulture);
            }
        }
        
        public static string lblGeneral {
            get {
                return ResourceManager.GetString("lblGeneral", resourceCulture);
            }
        }
        
        public static string lblHomePhone {
            get {
                return ResourceManager.GetString("lblHomePhone", resourceCulture);
            }
        }
        
        public static string lblImport {
            get {
                return ResourceManager.GetString("lblImport", resourceCulture);
            }
        }
        
        public static string lblInValid {
            get {
                return ResourceManager.GetString("lblInValid", resourceCulture);
            }
        }
        
        public static string lblInvalidImport {
            get {
                return ResourceManager.GetString("lblInvalidImport", resourceCulture);
            }
        }
        
        public static string lblIsMasterCard {
            get {
                return ResourceManager.GetString("lblIsMasterCard", resourceCulture);
            }
        }
        
        public static string lblIssueCount {
            get {
                return ResourceManager.GetString("lblIssueCount", resourceCulture);
            }
        }
        
        public static string lblIssuedDate {
            get {
                return ResourceManager.GetString("lblIssuedDate", resourceCulture);
            }
        }
        
        public static string lblJob {
            get {
                return ResourceManager.GetString("lblJob", resourceCulture);
            }
        }
        
        public static string lblKeyPadPassword {
            get {
                return ResourceManager.GetString("lblKeyPadPassword", resourceCulture);
            }
        }
        
        public static string lblLastName {
            get {
                return ResourceManager.GetString("lblLastName", resourceCulture);
            }
        }
        
        public static string lblLost {
            get {
                return ResourceManager.GetString("lblLost", resourceCulture);
            }
        }
        
        public static string lblMale {
            get {
                return ResourceManager.GetString("lblMale", resourceCulture);
            }
        }
        
        public static string lblNationality {
            get {
                return ResourceManager.GetString("lblNationality", resourceCulture);
            }
        }
        
        public static string lblNote {
            get {
                return ResourceManager.GetString("lblNote", resourceCulture);
            }
        }
        
        public static string lblOfficePhone {
            get {
                return ResourceManager.GetString("lblOfficePhone", resourceCulture);
            }
        }
        
        public static string lblOptimalSize {
            get {
                return ResourceManager.GetString("lblOptimalSize", resourceCulture);
            }
        }
        
        public static string lblPleaseChoose {
            get {
                return ResourceManager.GetString("lblPleaseChoose", resourceCulture);
            }
        }
        
        public static string lblPosition {
            get {
                return ResourceManager.GetString("lblPosition", resourceCulture);
            }
        }
        
        public static string lblPostCode {
            get {
                return ResourceManager.GetString("lblPostCode", resourceCulture);
            }
        }
        
        public static string lblRemarks {
            get {
                return ResourceManager.GetString("lblRemarks", resourceCulture);
            }
        }
        
        public static string lblResponsibility {
            get {
                return ResourceManager.GetString("lblResponsibility", resourceCulture);
            }
        }
        
        public static string lblRetire {
            get {
                return ResourceManager.GetString("lblRetire", resourceCulture);
            }
        }
        
        public static string lblSelectDepartment {
            get {
                return ResourceManager.GetString("lblSelectDepartment", resourceCulture);
            }
        }
        
        public static string lblSex {
            get {
                return ResourceManager.GetString("lblSex", resourceCulture);
            }
        }
        
        public static string lblSyncTime {
            get {
                return ResourceManager.GetString("lblSyncTime", resourceCulture);
            }
        }
        
        public static string lblTemp {
            get {
                return ResourceManager.GetString("lblTemp", resourceCulture);
            }
        }
        
        public static string lblUpdate {
            get {
                return ResourceManager.GetString("lblUpdate", resourceCulture);
            }
        }
        
        public static string lblUser {
            get {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }
        
        public static string lblCard {
            get {
                return ResourceManager.GetString("lblCard", resourceCulture);
            }
        }
        
        public static string lblUserInfomation {
            get {
                return ResourceManager.GetString("lblUserInfomation", resourceCulture);
            }
        }
        
        public static string lblUserList {
            get {
                return ResourceManager.GetString("lblUserList", resourceCulture);
            }
        }
        
        public static string lblUsers {
            get {
                return ResourceManager.GetString("lblUsers", resourceCulture);
            }
        }
        
        public static string msgCardIDIsBeingUsedByAnother {
            get {
                return ResourceManager.GetString("msgCardIDIsBeingUsedByAnother", resourceCulture);
            }
        }
        
        public static string msgCardIDIsBeingUsedByAnotherInSystem {
            get {
                return ResourceManager.GetString("msgCardIDIsBeingUsedByAnotherInSystem", resourceCulture);
            }
        }
        
        public static string msgChangeUserInfor {
            get {
                return ResourceManager.GetString("msgChangeUserInfor", resourceCulture);
            }
        }
        
        public static string msgChangeUserInforUserCode {
            get {
                return ResourceManager.GetString("msgChangeUserInforUserCode", resourceCulture);
            }
        }
        
        public static string msgDeleteMultipleUserCode {
            get {
                return ResourceManager.GetString("msgDeleteMultipleUserCode", resourceCulture);
            }
        }
        
        public static string msgExportSuccess {
            get {
                return ResourceManager.GetString("msgExportSuccess", resourceCulture);
            }
        }
        
        public static string msgExportUserList {
            get {
                return ResourceManager.GetString("msgExportUserList", resourceCulture);
            }
        }
        
        public static string msgImportSuccess {
            get {
                return ResourceManager.GetString("msgImportSuccess", resourceCulture);
            }
        }
        
        public static string msgImportUserList {
            get {
                return ResourceManager.GetString("msgImportUserList", resourceCulture);
            }
        }
        
        public static string msgInValidAvatar {
            get {
                return ResourceManager.GetString("msgInValidAvatar", resourceCulture);
            }
        }
        
        public static string msgInvalidRecord {
            get {
                return ResourceManager.GetString("msgInvalidRecord", resourceCulture);
            }
        }
        
        public static string msgKeyPadPwdBeingUsedByAnother {
            get {
                return ResourceManager.GetString("msgKeyPadPwdBeingUsedByAnother", resourceCulture);
            }
        }
        
        public static string msgKeyPadPwdBeingUsedByAnotherInSystem {
            get {
                return ResourceManager.GetString("msgKeyPadPwdBeingUsedByAnotherInSystem", resourceCulture);
            }
        }
        
        public static string msgNoData {
            get {
                return ResourceManager.GetString("msgNoData", resourceCulture);
            }
        }
        
        public static string msgUserCodeIsBeingUsedByAnother {
            get {
                return ResourceManager.GetString("msgUserCodeIsBeingUsedByAnother", resourceCulture);
            }
        }
        
        public static string PresentDate {
            get {
                return ResourceManager.GetString("PresentDate", resourceCulture);
            }
        }
        
        public static string lblAccessibleDoors {
            get {
                return ResourceManager.GetString("lblAccessibleDoors", resourceCulture);
            }
        }
        
        public static string msgExportAccessibleDoorList {
            get {
                return ResourceManager.GetString("msgExportAccessibleDoorList", resourceCulture);
            }
        }
        
        public static string lblExportAccessibleDoor {
            get {
                return ResourceManager.GetString("lblExportAccessibleDoor", resourceCulture);
            }
        }
        
        public static string lblId {
            get {
                return ResourceManager.GetString("lblId", resourceCulture);
            }
        }
        
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        public static string lblIndex {
            get {
                return ResourceManager.GetString("lblIndex", resourceCulture);
            }
        }
        
        public static string lblAccessGroup {
            get {
                return ResourceManager.GetString("lblAccessGroup", resourceCulture);
            }
        }
        
        public static string lblContractWorker {
            get {
                return ResourceManager.GetString("lblContractWorker", resourceCulture);
            }
        }
        
        public static string lblPartTimeWorker {
            get {
                return ResourceManager.GetString("lblPartTimeWorker", resourceCulture);
            }
        }
        
        public static string lblPassCard {
            get {
                return ResourceManager.GetString("lblPassCard", resourceCulture);
            }
        }
        
        public static string lblPermanentWorker {
            get {
                return ResourceManager.GetString("lblPermanentWorker", resourceCulture);
            }
        }
        
        public static string lblResidentWorker {
            get {
                return ResourceManager.GetString("lblResidentWorker", resourceCulture);
            }
        }
        
        public static string lblVisitCard {
            get {
                return ResourceManager.GetString("lblVisitCard", resourceCulture);
            }
        }
        
        public static string lblNotUse {
            get {
                return ResourceManager.GetString("lblNotUse", resourceCulture);
            }
        }
        
        public static string lblUse {
            get {
                return ResourceManager.GetString("lblUse", resourceCulture);
            }
        }
        
        public static string lblSystemAdmin {
            get {
                return ResourceManager.GetString("lblSystemAdmin", resourceCulture);
            }
        }
        
        public static string lblUserCode {
            get {
                return ResourceManager.GetString("lblUserCode", resourceCulture);
            }
        }
        
        public static string lblBirthday {
            get {
                return ResourceManager.GetString("lblBirthday", resourceCulture);
            }
        }
        
        public static string msgAddNewCertification {
            get {
                return ResourceManager.GetString("msgAddNewCertification", resourceCulture);
            }
        }
        
        public static string lblQR {
            get {
                return ResourceManager.GetString("lblQR", resourceCulture);
            }
        }
        
        public static string lblWorkingType {
            get {
                return ResourceManager.GetString("lblWorkingType", resourceCulture);
            }
        }
        
        public static string lblUserCount {
            get {
                return ResourceManager.GetString("lblUserCount", resourceCulture);
            }
        }
        
        public static string DeleteDefaultWorkingType {
            get {
                return ResourceManager.GetString("DeleteDefaultWorkingType", resourceCulture);
            }
        }
        
        public static string DeleteWorkingTypeUserWorkingOn {
            get {
                return ResourceManager.GetString("DeleteWorkingTypeUserWorkingOn", resourceCulture);
            }
        }
        
        public static string lblLateIn {
            get {
                return ResourceManager.GetString("lblLateIn", resourceCulture);
            }
        }
        
        public static string lblEarlyOut {
            get {
                return ResourceManager.GetString("lblEarlyOut", resourceCulture);
            }
        }
        
        public static string lblAbsentNoReason {
            get {
                return ResourceManager.GetString("lblAbsentNoReason", resourceCulture);
            }
        }
        
        public static string lblOverTime {
            get {
                return ResourceManager.GetString("lblOverTime", resourceCulture);
            }
        }
        
        public static string lblNormal {
            get {
                return ResourceManager.GetString("lblNormal", resourceCulture);
            }
        }
        
        public static string lblBusinessTrip {
            get {
                return ResourceManager.GetString("lblBusinessTrip", resourceCulture);
            }
        }
        
        public static string lblVacation {
            get {
                return ResourceManager.GetString("lblVacation", resourceCulture);
            }
        }
        
        public static string lblSickness {
            get {
                return ResourceManager.GetString("lblSickness", resourceCulture);
            }
        }
        
        public static string lblLateInEarlyOut {
            get {
                return ResourceManager.GetString("lblLateInEarlyOut", resourceCulture);
            }
        }
        
        public static string lblRemote {
            get {
                return ResourceManager.GetString("lblRemote", resourceCulture);
            }
        }
        
        public static string lblAbNormal {
            get {
                return ResourceManager.GetString("lblAbNormal", resourceCulture);
            }
        }
        
        public static string lblPlugIn {
            get {
                return ResourceManager.GetString("lblPlugIn", resourceCulture);
            }
        }
        
        public static string lblHoliday {
            get {
                return ResourceManager.GetString("lblHoliday", resourceCulture);
            }
        }
        
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        public static string msgUserCodeLength {
            get {
                return ResourceManager.GetString("msgUserCodeLength", resourceCulture);
            }
        }
        
        public static string lblActiveDutySoldier {
            get {
                return ResourceManager.GetString("lblActiveDutySoldier", resourceCulture);
            }
        }
        
        public static string lblCivilianWorker {
            get {
                return ResourceManager.GetString("lblCivilianWorker", resourceCulture);
            }
        }
        
        public static string lblSoldier {
            get {
                return ResourceManager.GetString("lblSoldier", resourceCulture);
            }
        }
        
        public static string lblAction {
            get {
                return ResourceManager.GetString("lblAction", resourceCulture);
            }
        }
        
        public static string lblMilitaryNumber {
            get {
                return ResourceManager.GetString("lblMilitaryNumber", resourceCulture);
            }
        }
        
        public static string lblEnlistmentDate {
            get {
                return ResourceManager.GetString("lblEnlistmentDate", resourceCulture);
            }
        }
        
        public static string lblCategoryOptionId {
            get {
                return ResourceManager.GetString("lblCategoryOptionId", resourceCulture);
            }
        }
        
        public static string lblValidUser {
            get {
                return ResourceManager.GetString("lblValidUser", resourceCulture);
            }
        }
        
        public static string lblInvalidUser {
            get {
                return ResourceManager.GetString("lblInvalidUser", resourceCulture);
            }
        }
        
        public static string lblAllUser {
            get {
                return ResourceManager.GetString("lblAllUser", resourceCulture);
            }
        }
        
        public static string msgDuplicatedFaceData {
            get {
                return ResourceManager.GetString("msgDuplicatedFaceData", resourceCulture);
            }
        }
        
        public static string lblMaster {
            get {
                return ResourceManager.GetString("lblMaster", resourceCulture);
            }
        }
        
        public static string lblSoldierFamily {
            get {
                return ResourceManager.GetString("lblSoldierFamily", resourceCulture);
            }
        }
        
        public static string lblApprovalWaiting1 {
            get {
                return ResourceManager.GetString("lblApprovalWaiting1", resourceCulture);
            }
        }
        
        public static string lblApprovalWaiting2 {
            get {
                return ResourceManager.GetString("lblApprovalWaiting2", resourceCulture);
            }
        }
        
        public static string lblApproved {
            get {
                return ResourceManager.GetString("lblApproved", resourceCulture);
            }
        }
        
        public static string lblRejected {
            get {
                return ResourceManager.GetString("lblRejected", resourceCulture);
            }
        }
        
        public static string lblApproval {
            get {
                return ResourceManager.GetString("lblApproval", resourceCulture);
            }
        }
        
        public static string lblReject {
            get {
                return ResourceManager.GetString("lblReject", resourceCulture);
            }
        }
        
        public static string lblAccessSetting {
            get {
                return ResourceManager.GetString("lblAccessSetting", resourceCulture);
            }
        }
        
        public static string lblNotUseApproval {
            get {
                return ResourceManager.GetString("lblNotUseApproval", resourceCulture);
            }
        }
        
        public static string lblApprovalStatus {
            get {
                return ResourceManager.GetString("lblApprovalStatus", resourceCulture);
            }
        }
        
        public static string lblUpdateWaiting1 {
            get {
                return ResourceManager.GetString("lblUpdateWaiting1", resourceCulture);
            }
        }
        
        public static string lblUpdateWaiting2 {
            get {
                return ResourceManager.GetString("lblUpdateWaiting2", resourceCulture);
            }
        }
        
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        public static string lblWorkType {
            get {
                return ResourceManager.GetString("lblWorkType", resourceCulture);
            }
        }
        
        public static string lblSecretIssuanceBasis {
            get {
                return ResourceManager.GetString("lblSecretIssuanceBasis", resourceCulture);
            }
        }
        
        public static string lblColor {
            get {
                return ResourceManager.GetString("lblColor", resourceCulture);
            }
        }
        
        public static string lblBlackBox {
            get {
                return ResourceManager.GetString("lblBlackBox", resourceCulture);
            }
        }
        
        public static string lblModel {
            get {
                return ResourceManager.GetString("lblModel", resourceCulture);
            }
        }
        
        public static string lblImageFileName {
            get {
                return ResourceManager.GetString("lblImageFileName", resourceCulture);
            }
        }
        
        public static string lblArmyWorkType {
            get {
                return ResourceManager.GetString("lblArmyWorkType", resourceCulture);
            }
        }
        
        public static string msgMaximumAddUser {
            get {
                return ResourceManager.GetString("msgMaximumAddUser", resourceCulture);
            }
        }
        
        public static string lblContractorStaff {
            get {
                return ResourceManager.GetString("lblContractorStaff", resourceCulture);
            }
        }
        
        public static string lblPersonnel {
            get {
                return ResourceManager.GetString("lblPersonnel", resourceCulture);
            }
        }
        
        public static string lblArmyUserFamilyName {
            get {
                return ResourceManager.GetString("lblArmyUserFamilyName", resourceCulture);
            }
        }
        
        public static string lblArmyUserFamilyRank {
            get {
                return ResourceManager.GetString("lblArmyUserFamilyRank", resourceCulture);
            }
        }
        
        public static string lblArmyUserFamilyDepartment {
            get {
                return ResourceManager.GetString("lblArmyUserFamilyDepartment", resourceCulture);
            }
        }
        
        public static string msgDeleteCard {
            get {
                return ResourceManager.GetString("msgDeleteCard", resourceCulture);
            }
        }
        
        public static string lblVehicle {
            get {
                return ResourceManager.GetString("lblVehicle", resourceCulture);
            }
        }
        
        public static string lblOfficer {
            get {
                return ResourceManager.GetString("lblOfficer", resourceCulture);
            }
        }
        
        public static string lblNCOfficer {
            get {
                return ResourceManager.GetString("lblNCOfficer", resourceCulture);
            }
        }
        
        public static string lblPublicOfficer {
            get {
                return ResourceManager.GetString("lblPublicOfficer", resourceCulture);
            }
        }
        
        public static string lblParmanentOfficer {
            get {
                return ResourceManager.GetString("lblParmanentOfficer", resourceCulture);
            }
        }
        
        public static string lblFixedWorker {
            get {
                return ResourceManager.GetString("lblFixedWorker", resourceCulture);
            }
        }
        
        public static string lblResidedWorker {
            get {
                return ResourceManager.GetString("lblResidedWorker", resourceCulture);
            }
        }
        
        public static string lblReservedArmy {
            get {
                return ResourceManager.GetString("lblReservedArmy", resourceCulture);
            }
        }
        
        public static string lblCivilian {
            get {
                return ResourceManager.GetString("lblCivilian", resourceCulture);
            }
        }
        
        public static string lblWaitingApproval {
            get {
                return ResourceManager.GetString("lblWaitingApproval", resourceCulture);
            }
        }
        
        public static string lblWaitingService {
            get {
                return ResourceManager.GetString("lblWaitingService", resourceCulture);
            }
        }
        
        public static string lblVehicleInService {
            get {
                return ResourceManager.GetString("lblVehicleInService", resourceCulture);
            }
        }
        
        public static string lblFinishedVehicleService {
            get {
                return ResourceManager.GetString("lblFinishedVehicleService", resourceCulture);
            }
        }
        
        public static string lblVehicleAllocationManager {
            get {
                return ResourceManager.GetString("lblVehicleAllocationManager", resourceCulture);
            }
        }
        
        public static string lblVehicleAllocationDriver {
            get {
                return ResourceManager.GetString("lblVehicleAllocationDriver", resourceCulture);
            }
        }
        
        public static string lblParentDepartment {
            get {
                return ResourceManager.GetString("lblParentDepartment", resourceCulture);
            }
        }
        
        public static string lblTypeOfWork {
            get {
                return ResourceManager.GetString("lblTypeOfWork", resourceCulture);
            }
        }
        
        public static string msgDataFingerprintInvalid {
            get {
                return ResourceManager.GetString("msgDataFingerprintInvalid", resourceCulture);
            }
        }
        
        public static string msgUserListNotChanged {
            get {
                return ResourceManager.GetString("msgUserListNotChanged", resourceCulture);
            }
        }
        
        public static string lblLostAccessPermission {
            get {
                return ResourceManager.GetString("lblLostAccessPermission", resourceCulture);
            }
        }
        
        public static string lblAddAccessPermission {
            get {
                return ResourceManager.GetString("lblAddAccessPermission", resourceCulture);
            }
        }
        
        public static string msgChangeDepartment {
            get {
                return ResourceManager.GetString("msgChangeDepartment", resourceCulture);
            }
        }
        
        public static string lblStudent {
            get {
                return ResourceManager.GetString("lblStudent", resourceCulture);
            }
        }
        
        public static string lblTeacher {
            get {
                return ResourceManager.GetString("lblTeacher", resourceCulture);
            }
        }
        
        public static string lblSyncData {
            get {
                return ResourceManager.GetString("lblSyncData", resourceCulture);
            }
        }
        
        public static string lblCode {
            get {
                return ResourceManager.GetString("lblCode", resourceCulture);
            }
        }
        
        public static string lblNone {
            get {
                return ResourceManager.GetString("lblNone", resourceCulture);
            }
        }
        
        public static string lblFaceAndIris {
            get {
                return ResourceManager.GetString("lblFaceAndIris", resourceCulture);
            }
        }
        
        public static string lblFaceOnly {
            get {
                return ResourceManager.GetString("lblFaceOnly", resourceCulture);
            }
        }
        
        public static string lblIrisOnly {
            get {
                return ResourceManager.GetString("lblIrisOnly", resourceCulture);
            }
        }
        
        public static string lblOffDutyBreak {
            get {
                return ResourceManager.GetString("lblOffDutyBreak", resourceCulture);
            }
        }
        
        public static string msgImageInvalid {
            get {
                return ResourceManager.GetString("msgImageInvalid", resourceCulture);
            }
        }
        
        public static string DeletedUserFailed {
            get {
                return ResourceManager.GetString("DeletedUserFailed", resourceCulture);
            }
        }
    }
}
