export type TEmployeeAccessReport = {
  id: number;
  icuId: number;
  userId: number | null;
  visitId: number | null;
  accessTime: string; // "DD.MM.YYYY HH:mm:ss"
  eventTime: string;
  userName: string | null;
  birthDay: string;
  employeeNumber: string;
  department: string;
  departmentName: string;
  cardId: string | null;
  deviceAddress: string;
  doorName: string;
  building: string;
  userCode: string | null;
  inOut: string;
  eventDetail: string;
  eventLogId: number;
  issueCount: number;
  cardStatus: string;
  cardType: string;
  action: string | null;
  imageCamera: string | null;
  vehicleImage: string | null;
  videos: string | null;
  videosVehicle: string | null;
  resultCheckIn: string | null;
  bodyTemperature: number;
  delayOpenDoorByCamera: number;
  avatar: string;
  workType: string | null;
  workTypeName: string;
  memo: string | null;
  distance: number;
  searchScore: number;
  livenessScore: number;
};
