//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AttendanceResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AttendanceResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.AttendanceResource", typeof(AttendanceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lblAttendance {
            get {
                return ResourceManager.GetString("lblAttendance", resourceCulture);
            }
        }
        
        public static string headerName {
            get {
                return ResourceManager.GetString("headerName", resourceCulture);
            }
        }
        
        public static string headerDate {
            get {
                return ResourceManager.GetString("headerDate", resourceCulture);
            }
        }
        
        public static string headerClockIn {
            get {
                return ResourceManager.GetString("headerClockIn", resourceCulture);
            }
        }
        
        public static string headerClockOut {
            get {
                return ResourceManager.GetString("headerClockOut", resourceCulture);
            }
        }
        
        public static string headerUnfulfilledTime {
            get {
                return ResourceManager.GetString("headerUnfulfilledTime", resourceCulture);
            }
        }
        
        public static string headerOverTime {
            get {
                return ResourceManager.GetString("headerOverTime", resourceCulture);
            }
        }
        
        public static string headerTotalTime {
            get {
                return ResourceManager.GetString("headerTotalTime", resourceCulture);
            }
        }
        
        public static string headerDayOfWeek {
            get {
                return ResourceManager.GetString("headerDayOfWeek", resourceCulture);
            }
        }
        
        public static string lblSunday {
            get {
                return ResourceManager.GetString("lblSunday", resourceCulture);
            }
        }
        
        public static string lblMonday {
            get {
                return ResourceManager.GetString("lblMonday", resourceCulture);
            }
        }
        
        public static string lblTuesday {
            get {
                return ResourceManager.GetString("lblTuesday", resourceCulture);
            }
        }
        
        public static string lblWednesday {
            get {
                return ResourceManager.GetString("lblWednesday", resourceCulture);
            }
        }
        
        public static string lblThursday {
            get {
                return ResourceManager.GetString("lblThursday", resourceCulture);
            }
        }
        
        public static string lblFriday {
            get {
                return ResourceManager.GetString("lblFriday", resourceCulture);
            }
        }
        
        public static string lblSaturday {
            get {
                return ResourceManager.GetString("lblSaturday", resourceCulture);
            }
        }
        
        public static string headerDiffTime {
            get {
                return ResourceManager.GetString("headerDiffTime", resourceCulture);
            }
        }
        
        public static string lblTotalWorkingHour {
            get {
                return ResourceManager.GetString("lblTotalWorkingHour", resourceCulture);
            }
        }
        
        public static string lblTotalDiffTime {
            get {
                return ResourceManager.GetString("lblTotalDiffTime", resourceCulture);
            }
        }
        
        public static string lblWeekWorkingHour {
            get {
                return ResourceManager.GetString("lblWeekWorkingHour", resourceCulture);
            }
        }
        
        public static string lblWeekDiffTime {
            get {
                return ResourceManager.GetString("lblWeekDiffTime", resourceCulture);
            }
        }
        
        public static string lblWeekly {
            get {
                return ResourceManager.GetString("lblWeekly", resourceCulture);
            }
        }
        
        public static string lblTotal {
            get {
                return ResourceManager.GetString("lblTotal", resourceCulture);
            }
        }
        
        public static string lblOnlyInOffice {
            get {
                return ResourceManager.GetString("lblOnlyInOffice", resourceCulture);
            }
        }
        
        public static string lblTotalInOffice {
            get {
                return ResourceManager.GetString("lblTotalInOffice", resourceCulture);
            }
        }
        
        public static string lblStatusWaiting {
            get {
                return ResourceManager.GetString("lblStatusWaiting", resourceCulture);
            }
        }
        
        public static string lblStatusAprroval {
            get {
                return ResourceManager.GetString("lblStatusAprroval", resourceCulture);
            }
        }
        
        public static string lblStatusReject {
            get {
                return ResourceManager.GetString("lblStatusReject", resourceCulture);
            }
        }
        
        public static string contentRegisterAttenance {
            get {
                return ResourceManager.GetString("contentRegisterAttenance", resourceCulture);
            }
        }
        
        public static string contentAcceptAttendanceLeave {
            get {
                return ResourceManager.GetString("contentAcceptAttendanceLeave", resourceCulture);
            }
        }
        
        public static string contentRejectAttendanceLeave {
            get {
                return ResourceManager.GetString("contentRejectAttendanceLeave", resourceCulture);
            }
        }
        
        public static string messageRegisterSuccess {
            get {
                return ResourceManager.GetString("messageRegisterSuccess", resourceCulture);
            }
        }
        
        public static string requestAttendanceExist {
            get {
                return ResourceManager.GetString("requestAttendanceExist", resourceCulture);
            }
        }
        
        public static string headerAttendanceType {
            get {
                return ResourceManager.GetString("headerAttendanceType", resourceCulture);
            }
        }
        
        public static string cannotDeleteRequest {
            get {
                return ResourceManager.GetString("cannotDeleteRequest", resourceCulture);
            }
        }
        
        public static string cannotEditRequest {
            get {
                return ResourceManager.GetString("cannotEditRequest", resourceCulture);
            }
        }
        
        public static string titleNoticationLeaveRequest {
            get {
                return ResourceManager.GetString("titleNoticationLeaveRequest", resourceCulture);
            }
        }
        
        public static string lblHHmmss {
            get {
                return ResourceManager.GetString("lblHHmmss", resourceCulture);
            }
        }
        
        public static string lblHHmm {
            get {
                return ResourceManager.GetString("lblHHmm", resourceCulture);
            }
        }
        
        public static string msgAddNewWorkingType {
            get {
                return ResourceManager.GetString("msgAddNewWorkingType", resourceCulture);
            }
        }
        
        public static string msgUpdateWorkingType {
            get {
                return ResourceManager.GetString("msgUpdateWorkingType", resourceCulture);
            }
        }
        
        public static string msgDeleteWorkingType {
            get {
                return ResourceManager.GetString("msgDeleteWorkingType", resourceCulture);
            }
        }
        
        public static string lblAttendanceReportType1 {
            get {
                return ResourceManager.GetString("lblAttendanceReportType1", resourceCulture);
            }
        }
        
        public static string lblAttendanceReportType0 {
            get {
                return ResourceManager.GetString("lblAttendanceReportType0", resourceCulture);
            }
        }
        
        public static string headerBodyTemperature {
            get {
                return ResourceManager.GetString("headerBodyTemperature", resourceCulture);
            }
        }
        
        public static string headerDepartment {
            get {
                return ResourceManager.GetString("headerDepartment", resourceCulture);
            }
        }
        
        public static string msgNotifyCheckinLate {
            get {
                return ResourceManager.GetString("msgNotifyCheckinLate", resourceCulture);
            }
        }
        
        public static string lblLeaveUserName {
            get {
                return ResourceManager.GetString("lblLeaveUserName", resourceCulture);
            }
        }
        
        public static string lblLeaveType {
            get {
                return ResourceManager.GetString("lblLeaveType", resourceCulture);
            }
        }
        
        public static string lblLeaveFromDate {
            get {
                return ResourceManager.GetString("lblLeaveFromDate", resourceCulture);
            }
        }
        
        public static string lblLeaveToDate {
            get {
                return ResourceManager.GetString("lblLeaveToDate", resourceCulture);
            }
        }
        
        public static string lblLeaveReason {
            get {
                return ResourceManager.GetString("lblLeaveReason", resourceCulture);
            }
        }
        
        public static string lblLeaveRejectReason {
            get {
                return ResourceManager.GetString("lblLeaveRejectReason", resourceCulture);
            }
        }
        
        public static string lblButtonCheckLeaveRequest {
            get {
                return ResourceManager.GetString("lblButtonCheckLeaveRequest", resourceCulture);
            }
        }
        
        public static string lblAttendanceReportType2 {
            get {
                return ResourceManager.GetString("lblAttendanceReportType2", resourceCulture);
            }
        }
        
        public static string titleAttendanceReportType2 {
            get {
                return ResourceManager.GetString("titleAttendanceReportType2", resourceCulture);
            }
        }
        
        public static string titleAttendanceReportDateType2 {
            get {
                return ResourceManager.GetString("titleAttendanceReportDateType2", resourceCulture);
            }
        }
        
        public static string lblNote {
            get {
                return ResourceManager.GetString("lblNote", resourceCulture);
            }
        }
        
        public static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        public static string lblFullName {
            get {
                return ResourceManager.GetString("lblFullName", resourceCulture);
            }
        }
        
        public static string lblTimeIn {
            get {
                return ResourceManager.GetString("lblTimeIn", resourceCulture);
            }
        }
        
        public static string lblTimeOut {
            get {
                return ResourceManager.GetString("lblTimeOut", resourceCulture);
            }
        }
        
        public static string lblDefineLateIn {
            get {
                return ResourceManager.GetString("lblDefineLateIn", resourceCulture);
            }
        }
        
        public static string lblDefineAbsence {
            get {
                return ResourceManager.GetString("lblDefineAbsence", resourceCulture);
            }
        }
        
        public static string lblDefineEarlyOut {
            get {
                return ResourceManager.GetString("lblDefineEarlyOut", resourceCulture);
            }
        }
        
        public static string lblWork {
            get {
                return ResourceManager.GetString("lblWork", resourceCulture);
            }
        }
        
        public static string lblAnnualVacation {
            get {
                return ResourceManager.GetString("lblAnnualVacation", resourceCulture);
            }
        }
        
        public static string lblOfficialVacation {
            get {
                return ResourceManager.GetString("lblOfficialVacation", resourceCulture);
            }
        }
        
        public static string lblPetitionVacation {
            get {
                return ResourceManager.GetString("lblPetitionVacation", resourceCulture);
            }
        }
        
        public static string lblSpecialVacation {
            get {
                return ResourceManager.GetString("lblSpecialVacation", resourceCulture);
            }
        }
        
        public static string lblSleepOut {
            get {
                return ResourceManager.GetString("lblSleepOut", resourceCulture);
            }
        }
        
        public static string lblGoOut {
            get {
                return ResourceManager.GetString("lblGoOut", resourceCulture);
            }
        }
        
        public static string lblVisitOut {
            get {
                return ResourceManager.GetString("lblVisitOut", resourceCulture);
            }
        }
        
        public static string lblHospitalization {
            get {
                return ResourceManager.GetString("lblHospitalization", resourceCulture);
            }
        }
        
        public static string lblStartDate {
            get {
                return ResourceManager.GetString("lblStartDate", resourceCulture);
            }
        }
        
        public static string lblEndDate {
            get {
                return ResourceManager.GetString("lblEndDate", resourceCulture);
            }
        }
        
        public static string titleAttendanceReportDateType3 {
            get {
                return ResourceManager.GetString("titleAttendanceReportDateType3", resourceCulture);
            }
        }
        
        public static string lblAttendanceReportType3 {
            get {
                return ResourceManager.GetString("lblAttendanceReportType3", resourceCulture);
            }
        }
        
        public static string lblUserCode {
            get {
                return ResourceManager.GetString("lblUserCode", resourceCulture);
            }
        }
        
        public static string lblPosition {
            get {
                return ResourceManager.GetString("lblPosition", resourceCulture);
            }
        }
        
        public static string lblDepartment {
            get {
                return ResourceManager.GetString("lblDepartment", resourceCulture);
            }
        }
        
        public static string lblDateOfMonth {
            get {
                return ResourceManager.GetString("lblDateOfMonth", resourceCulture);
            }
        }
        
        public static string lblAttendanceReportType4 {
            get {
                return ResourceManager.GetString("lblAttendanceReportType4", resourceCulture);
            }
        }
        
        public static string headerShift {
            get {
                return ResourceManager.GetString("headerShift", resourceCulture);
            }
        }
        
        public static string headerLateIn {
            get {
                return ResourceManager.GetString("headerLateIn", resourceCulture);
            }
        }
        
        public static string headerEarlyOut {
            get {
                return ResourceManager.GetString("headerEarlyOut", resourceCulture);
            }
        }
        
        public static string headerActualWorkingHour {
            get {
                return ResourceManager.GetString("headerActualWorkingHour", resourceCulture);
            }
        }
        
        public static string headerRealWorkingHour {
            get {
                return ResourceManager.GetString("headerRealWorkingHour", resourceCulture);
            }
        }
        
        public static string headerOvertimeDurationBefore {
            get {
                return ResourceManager.GetString("headerOvertimeDurationBefore", resourceCulture);
            }
        }
        
        public static string headerOvertimeDurationAfter {
            get {
                return ResourceManager.GetString("headerOvertimeDurationAfter", resourceCulture);
            }
        }
        
        public static string msgNotifyCheckinFirst {
            get {
                return ResourceManager.GetString("msgNotifyCheckinFirst", resourceCulture);
            }
        }
        
        public static string lblHHmmDot {
            get {
                return ResourceManager.GetString("lblHHmmDot", resourceCulture);
            }
        }
        
        public static string msgWorkingTimeNameExisted {
            get {
                return ResourceManager.GetString("msgWorkingTimeNameExisted", resourceCulture);
            }
        }
        
        public static string msgValidationWorkingType {
            get {
                return ResourceManager.GetString("msgValidationWorkingType", resourceCulture);
            }
        }
        
        public static string msgValidationWorkingTime {
            get {
                return ResourceManager.GetString("msgValidationWorkingTime", resourceCulture);
            }
        }
        
        public static string msgValidationWorkingDay {
            get {
                return ResourceManager.GetString("msgValidationWorkingDay", resourceCulture);
            }
        }
        
        public static string msgValidationLunchTime {
            get {
                return ResourceManager.GetString("msgValidationLunchTime", resourceCulture);
            }
        }
    }
}
