//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MeetingResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MeetingResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.MeetingResource", typeof(MeetingResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        internal static string lblAttendance {
            get {
                return ResourceManager.GetString("lblAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in.
        /// </summary>
        internal static string lblCheckIn {
            get {
                return ResourceManager.GetString("lblCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string lblMeeting {
            get {
                return ResourceManager.GetString("lblMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event room.
        /// </summary>
        internal static string lblMeetingRoom {
            get {
                return ResourceManager.GetString("lblMeetingRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string lblYes {
            get {
                return ResourceManager.GetString("lblYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign user(s) to event successfully..
        /// </summary>
        internal static string msgAssignUsers {
            get {
                return ResourceManager.GetString("msgAssignUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign visitor(s) to event successfully..
        /// </summary>
        internal static string msgAssignVisits {
            get {
                return ResourceManager.GetString("msgAssignVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to assign these users..
        /// </summary>
        internal static string msgCannotAssignUsers {
            get {
                return ResourceManager.GetString("msgCannotAssignUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event room cannot be deleted while there are event scheduled in the room..
        /// </summary>
        internal static string msgCanNotDeleteMeetingWithDependance {
            get {
                return ResourceManager.GetString("msgCanNotDeleteMeetingWithDependance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please assign at least one user..
        /// </summary>
        internal static string msgEmptyUser {
            get {
                return ResourceManager.GetString("msgEmptyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please assign at least one visitor..
        /// </summary>
        internal static string msgEmptyVisit {
            get {
                return ResourceManager.GetString("msgEmptyVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User in this event can not add over {0}/{1} persons..
        /// </summary>
        internal static string msgMeetingLimitAttandance {
            get {
                return ResourceManager.GetString("msgMeetingLimitAttandance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnAssign user(s) to event successfully..
        /// </summary>
        internal static string msgUnAssignUsers {
            get {
                return ResourceManager.GetString("msgUnAssignUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnAssign visitor(s) to event successfully..
        /// </summary>
        internal static string msgUnAssignVisits {
            get {
                return ResourceManager.GetString("msgUnAssignVisits", resourceCulture);
            }
        }
    }
}
