//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageLogResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageLogResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.MessageLogResource", typeof(MessageLogResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lblAccessControlResponseTopic {
            get {
                return ResourceManager.GetString("lblAccessControlResponseTopic", resourceCulture);
            }
        }
        
        public static string lblAccessControlTopic {
            get {
                return ResourceManager.GetString("lblAccessControlTopic", resourceCulture);
            }
        }
        
        public static string lblAddUser {
            get {
                return ResourceManager.GetString("lblAddUser", resourceCulture);
            }
        }
        
        public static string lblConfigResponseTopic {
            get {
                return ResourceManager.GetString("lblConfigResponseTopic", resourceCulture);
            }
        }
        
        public static string lblConfigTopic {
            get {
                return ResourceManager.GetString("lblConfigTopic", resourceCulture);
            }
        }
        
        public static string lblConnectionStatus {
            get {
                return ResourceManager.GetString("lblConnectionStatus", resourceCulture);
            }
        }
        
        public static string lblDeleteDevice {
            get {
                return ResourceManager.GetString("lblDeleteDevice", resourceCulture);
            }
        }
        
        public static string lblDeleteTimezone {
            get {
                return ResourceManager.GetString("lblDeleteTimezone", resourceCulture);
            }
        }
        
        public static string lblDeleteUser {
            get {
                return ResourceManager.GetString("lblDeleteUser", resourceCulture);
            }
        }
        
        public static string lblDeviceInfoResponseTopic {
            get {
                return ResourceManager.GetString("lblDeviceInfoResponseTopic", resourceCulture);
            }
        }
        
        public static string lblDeviceInfoTopic {
            get {
                return ResourceManager.GetString("lblDeviceInfoTopic", resourceCulture);
            }
        }
        
        public static string lblDeviceInstruction {
            get {
                return ResourceManager.GetString("lblDeviceInstruction", resourceCulture);
            }
        }
        
        public static string lblDeviceInstructionResponseTopic {
            get {
                return ResourceManager.GetString("lblDeviceInstructionResponseTopic", resourceCulture);
            }
        }
        
        public static string lblDeviceInstructionTopic {
            get {
                return ResourceManager.GetString("lblDeviceInstructionTopic", resourceCulture);
            }
        }
        
        public static string lblDeviceStatusTopic {
            get {
                return ResourceManager.GetString("lblDeviceStatusTopic", resourceCulture);
            }
        }
        
        public static string lblEventLogJsonTopic {
            get {
                return ResourceManager.GetString("lblEventLogJsonTopic", resourceCulture);
            }
        }
        
        public static string lblEventLogResponse {
            get {
                return ResourceManager.GetString("lblEventLogResponse", resourceCulture);
            }
        }
        
        public static string lblEventLogResponseTopic {
            get {
                return ResourceManager.GetString("lblEventLogResponseTopic", resourceCulture);
            }
        }
        
        public static string lblEventLogTopic {
            get {
                return ResourceManager.GetString("lblEventLogTopic", resourceCulture);
            }
        }
        
        public static string lblExport {
            get {
                return ResourceManager.GetString("lblExport", resourceCulture);
            }
        }
        
        public static string lblFileDownload {
            get {
                return ResourceManager.GetString("lblFileDownload", resourceCulture);
            }
        }
        
        public static string lblFileTranferResponseTopic {
            get {
                return ResourceManager.GetString("lblFileTranferResponseTopic", resourceCulture);
            }
        }
        
        public static string lblFileTranferTopic {
            get {
                return ResourceManager.GetString("lblFileTranferTopic", resourceCulture);
            }
        }
        
        public static string lblFromPublishedTime {
            get {
                return ResourceManager.GetString("lblFromPublishedTime", resourceCulture);
            }
        }
        
        public static string lblFromResponseTime {
            get {
                return ResourceManager.GetString("lblFromResponseTime", resourceCulture);
            }
        }
        
        public static string lblHolidayResponseTopic {
            get {
                return ResourceManager.GetString("lblHolidayResponseTopic", resourceCulture);
            }
        }
        
        public static string lblHolidayTopic {
            get {
                return ResourceManager.GetString("lblHolidayTopic", resourceCulture);
            }
        }
        
        public static string lblLoadDeviceInfo {
            get {
                return ResourceManager.GetString("lblLoadDeviceInfo", resourceCulture);
            }
        }
        
        public static string lblLongProcessProgress {
            get {
                return ResourceManager.GetString("lblLongProcessProgress", resourceCulture);
            }
        }
        
        public static string lblLongProcessProgressTopic {
            get {
                return ResourceManager.GetString("lblLongProcessProgressTopic", resourceCulture);
            }
        }
        
        public static string lblMessageLog {
            get {
                return ResourceManager.GetString("lblMessageLog", resourceCulture);
            }
        }
        
        public static string lblNotification {
            get {
                return ResourceManager.GetString("lblNotification", resourceCulture);
            }
        }
        
        public static string lblNotificationTopic {
            get {
                return ResourceManager.GetString("lblNotificationTopic", resourceCulture);
            }
        }
        
        public static string lblOnlineTopic {
            get {
                return ResourceManager.GetString("lblOnlineTopic", resourceCulture);
            }
        }
        
        public static string lblTimezoneResponseTopic {
            get {
                return ResourceManager.GetString("lblTimezoneResponseTopic", resourceCulture);
            }
        }
        
        public static string lblTimezoneTopic {
            get {
                return ResourceManager.GetString("lblTimezoneTopic", resourceCulture);
            }
        }
        
        public static string lblToPublishedTime {
            get {
                return ResourceManager.GetString("lblToPublishedTime", resourceCulture);
            }
        }
        
        public static string lblToResponseTime {
            get {
                return ResourceManager.GetString("lblToResponseTime", resourceCulture);
            }
        }
        
        public static string lblUpdateDeviceConfig {
            get {
                return ResourceManager.GetString("lblUpdateDeviceConfig", resourceCulture);
            }
        }
        
        public static string lblUpdateHoliday {
            get {
                return ResourceManager.GetString("lblUpdateHoliday", resourceCulture);
            }
        }
        
        public static string lblUpdateTimezone {
            get {
                return ResourceManager.GetString("lblUpdateTimezone", resourceCulture);
            }
        }
    }
}
