//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.NotificationResource", typeof(NotificationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string TitleNotificationAccess {
            get {
                return ResourceManager.GetString("TitleNotificationAccess", resourceCulture);
            }
        }
        
        public static string TitleNotificationAttendance {
            get {
                return ResourceManager.GetString("TitleNotificationAttendance", resourceCulture);
            }
        }
        
        public static string TitleNotificationVisit {
            get {
                return ResourceManager.GetString("TitleNotificationVisit", resourceCulture);
            }
        }
        
        public static string TitleNotificationDoors {
            get {
                return ResourceManager.GetString("TitleNotificationDoors", resourceCulture);
            }
        }
        
        public static string TitleNotificationInform {
            get {
                return ResourceManager.GetString("TitleNotificationInform", resourceCulture);
            }
        }
        
        public static string TitleNotificationWarning {
            get {
                return ResourceManager.GetString("TitleNotificationWarning", resourceCulture);
            }
        }
        
        public static string TitleNotificationAction {
            get {
                return ResourceManager.GetString("TitleNotificationAction", resourceCulture);
            }
        }
        
        public static string TitleNotificationEmergency {
            get {
                return ResourceManager.GetString("TitleNotificationEmergency", resourceCulture);
            }
        }
        
        public static string TitlleNotificationNotice {
            get {
                return ResourceManager.GetString("TitlleNotificationNotice", resourceCulture);
            }
        }
        
        public static string msgCreateSuccessNewLFaceId {
            get {
                return ResourceManager.GetString("msgCreateSuccessNewLFaceId", resourceCulture);
            }
        }
        
        public static string msgCreateErrorNewLFaceId {
            get {
                return ResourceManager.GetString("msgCreateErrorNewLFaceId", resourceCulture);
            }
        }
        
        public static string msgCreateSuccessNewBioFaceId {
            get {
                return ResourceManager.GetString("msgCreateSuccessNewBioFaceId", resourceCulture);
            }
        }
        
        public static string msgCreateErrorNewBioFaceId {
            get {
                return ResourceManager.GetString("msgCreateErrorNewBioFaceId", resourceCulture);
            }
        }
        
        public static string msgCreateErrorNewDCFaceId {
            get {
                return ResourceManager.GetString("msgCreateErrorNewDCFaceId", resourceCulture);
            }
        }
        
        public static string msgCreateSuccessNewDCFaceId {
            get {
                return ResourceManager.GetString("msgCreateSuccessNewDCFaceId", resourceCulture);
            }
        }
    }
}
