//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemLogTypeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemLogTypeResource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.SystemLogTypeResource", typeof(SystemLogTypeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AccessGroup과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccessGroup {
            get {
                return ResourceManager.GetString("AccessGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access level과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccessLevel {
            get {
                return ResourceManager.GetString("AccessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccessTime {
            get {
                return ResourceManager.GetString("AccessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account Management과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccountManagement {
            get {
                return ResourceManager.GetString("AccountManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attendance과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Building과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canteen과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Canteen {
            get {
                return ResourceManager.GetString("Canteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Category과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Device Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CheckDeviceSetting {
            get {
                return ResourceManager.GetString("CheckDeviceSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check User Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CheckUserInformation {
            get {
                return ResourceManager.GetString("CheckUserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Company과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Department과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Monitoring과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeviceMonitoring {
            get {
                return ResourceManager.GetString("DeviceMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeviceSetting {
            get {
                return ResourceManager.GetString("DeviceSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Update과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeviceUpdate {
            get {
                return ResourceManager.GetString("DeviceUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Role과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DynamicRole {
            get {
                return ResourceManager.GetString("DynamicRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emergency과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Emergency {
            get {
                return ResourceManager.GetString("Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Event Recovery과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EventRecovery {
            get {
                return ResourceManager.GetString("EventRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Holiday과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Action과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblAction {
            get {
                return ResourceManager.GetString("lblAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Company과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblCompany {
            get {
                return ResourceManager.GetString("lblCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblMessage {
            get {
                return ResourceManager.GetString("lblMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Object Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblObjectType {
            get {
                return ResourceManager.GetString("lblObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation Date From과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblOpeDateFrom {
            get {
                return ResourceManager.GetString("lblOpeDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation Date To과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblOpeDateTo {
            get {
                return ResourceManager.GetString("lblOpeDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblOperationTime {
            get {
                return ResourceManager.GetString("lblOperationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation Time From과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblOpeTimeFrom {
            get {
                return ResourceManager.GetString("lblOpeTimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation Time To과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblOpeTimeTo {
            get {
                return ResourceManager.GetString("lblOpeTimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Report과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblReport {
            get {
                return ResourceManager.GetString("lblReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblSystemLog {
            get {
                return ResourceManager.GetString("lblSystemLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblUserAccount {
            get {
                return ResourceManager.GetString("lblUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logout과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MessageSetting {
            get {
                return ResourceManager.GetString("MessageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multi person rule과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MultiPersonRule {
            get {
                return ResourceManager.GetString("MultiPersonRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plug-in과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PlugIn {
            get {
                return ResourceManager.GetString("PlugIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registered user과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RegisteredUser {
            get {
                return ResourceManager.GetString("RegisteredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Report과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemSetting {
            get {
                return ResourceManager.GetString("SystemSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transmit All Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TransmitAllData {
            get {
                return ResourceManager.GetString("TransmitAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vehicle과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vehicle allocation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VehicleAllocation {
            get {
                return ResourceManager.GetString("VehicleAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visit Management과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string VisitManagement {
            get {
                return ResourceManager.GetString("VisitManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wiegand과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WgSetting {
            get {
                return ResourceManager.GetString("WgSetting", resourceCulture);
            }
        }
    }
}
