//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkShiftResource
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkShiftResource()
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.Equals(null, resourceMan))
                {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.WorkShiftResource", typeof(WorkShiftResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string lblWorkShift
        {
            get
            {
                return ResourceManager.GetString("lblWorkShift", resourceCulture);
            }
        }
        public static string msgEmptyUser
        {
            get
            {
                return ResourceManager.GetString("msgEmptyUser", resourceCulture);
            }
        }
        public static string msgCannotAssignUsers
        {
            get
            {
                return ResourceManager.GetString("msgCannotAssignUsers", resourceCulture);
            }
        }

        public static string msgAssignUsers
        {
            get
            {
                return ResourceManager.GetString("msgAssignUsers", resourceCulture);
            }
        }
        public static string msgUnAssignUsers
        {
            get
            {
                return ResourceManager.GetString("msgUnAssignUsers", resourceCulture);
            }
        }
        public static string TimeIsInvalid
        {
            get
            {
                return ResourceManager.GetString("TimeIsInvalid", resourceCulture);
            }
        }
        public static string StartTimeMustBeLessThanEndTime
        {
            get
            {
                return ResourceManager.GetString("StartTimeMustBeLessThanEndTime", resourceCulture);
            }
        }
        public static string NameAlreadyExists
        {
            get
            {
                return ResourceManager.GetString("NameAlreadyExists", resourceCulture);
            }
        }

        
        
    }
}
