//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccessGroupResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccessGroupResource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.AccessGroupResource", typeof(AccessGroupResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Only the last approver can assign a door.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string assingedVisitAuthor {
            get {
                return ResourceManager.GetString("assingedVisitAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The visit need to approved first.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string assingedVisitNotApproval {
            get {
                return ResourceManager.GetString("assingedVisitNotApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access Group과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblAccessGroup {
            get {
                return ResourceManager.GetString("lblAccessGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access Group count과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblAccessGroupCount {
            get {
                return ResourceManager.GetString("lblAccessGroupCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access Group Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblAccessGroupName {
            get {
                return ResourceManager.GetString("lblAccessGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assign Door(s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblAssignDoor {
            get {
                return ResourceManager.GetString("lblAssignDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assign User(s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblAssignUser {
            get {
                return ResourceManager.GetString("lblAssignUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom group과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblCustomGroup {
            get {
                return ResourceManager.GetString("lblCustomGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default Access Group과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblDefaultAccessGroup {
            get {
                return ResourceManager.GetString("lblDefaultAccessGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous Access Group Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblOldAccessGroupName {
            get {
                return ResourceManager.GetString("lblOldAccessGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unassign Door(s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblUnAssignDoor {
            get {
                return ResourceManager.GetString("lblUnAssignDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unassign User(s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblUnAssignUser {
            get {
                return ResourceManager.GetString("lblUnAssignUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Added a new Access group과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgAddAccessGroup {
            get {
                return ResourceManager.GetString("msgAddAccessGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assign door(s) to access group successfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgAssignDoors {
            get {
                return ResourceManager.GetString("msgAssignDoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assign foor(s) to access group successfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgAssignFoors {
            get {
                return ResourceManager.GetString("msgAssignFoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assign user(s) to access group successfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgAssignUsers {
            get {
                return ResourceManager.GetString("msgAssignUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assign user(s) to door successfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgAssignUsersToDoor {
            get {
                return ResourceManager.GetString("msgAssignUsersToDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You do not have permission to assign these devices.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgCannotAssignDevices {
            get {
                return ResourceManager.GetString("msgCannotAssignDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You do not have permission to assign these users.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgCannotAssignUsers {
            get {
                return ResourceManager.GetString("msgCannotAssignUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not change the timezone of Full Access Group.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgCanNotChangeTimezone {
            get {
                return ResourceManager.GetString("msgCanNotChangeTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} could not be deleted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgCanNotDeleteAccessGroup {
            get {
                return ResourceManager.GetString("msgCanNotDeleteAccessGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Devices could not be unassigned.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgCanNotDeleteDevice {
            get {
                return ResourceManager.GetString("msgCanNotDeleteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You do not have permission to unassign these devices.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgCannotUnAssignDevices {
            get {
                return ResourceManager.GetString("msgCannotUnAssignDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You do not have permission to unassign these users.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgCannotUnAssignUsers {
            get {
                return ResourceManager.GetString("msgCannotUnAssignUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} could not be updated!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgCanNotUpdateAccessGroup {
            get {
                return ResourceManager.GetString("msgCanNotUpdateAccessGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Access Group information.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgChangeAccessGroup {
            get {
                return ResourceManager.GetString("msgChangeAccessGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change name from &apos;{0}&apos; to &apos;{1}&apos;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgChangeAccessGroupName {
            get {
                return ResourceManager.GetString("msgChangeAccessGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change AccessGroup &apos;{0}&apos;(Default) (Access Group Id).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgChangeAccessGroupWithDefault {
            get {
                return ResourceManager.GetString("msgChangeAccessGroupWithDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} has become Default access group.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgChangeDefaultAccessGroup {
            get {
                return ResourceManager.GetString("msgChangeDefaultAccessGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change timezone for the door(s) successfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgChangeTimezone {
            get {
                return ResourceManager.GetString("msgChangeTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted Access group(s).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgDeleteAccessGroup {
            get {
                return ResourceManager.GetString("msgDeleteAccessGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please assign at least one door.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgEmptyDoorAssign {
            get {
                return ResourceManager.GetString("msgEmptyDoorAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to delete empty doors from all access groups과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgEmptyDoors {
            get {
                return ResourceManager.GetString("msgEmptyDoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please assign at least one user.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgEmptyUser {
            get {
                return ResourceManager.GetString("msgEmptyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no devices were assigned to the access group.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgHasNoAccessGroupDeviceData {
            get {
                return ResourceManager.GetString("msgHasNoAccessGroupDeviceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The system specifies the default AccessGroup because the default AccessGroup has disappeared due to an unknown error.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgNoDefaultAG {
            get {
                return ResourceManager.GetString("msgNoDefaultAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not found access group과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgNotFoundAccessGroup {
            get {
                return ResourceManager.GetString("msgNotFoundAccessGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time zone or door can not found과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgNotFoundTimezoneOrDoor {
            get {
                return ResourceManager.GetString("msgNotFoundTimezoneOrDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You do not have permission to add access group with default.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgNotPermissionAddDefaultAg {
            get {
                return ResourceManager.GetString("msgNotPermissionAddDefaultAg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You do not have permission to change this access group to default.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgNotPermissionChangeDefaultAg {
            get {
                return ResourceManager.GetString("msgNotPermissionChangeDefaultAg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You do not have permission to access this device.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgNotPermissionDevices {
            get {
                return ResourceManager.GetString("msgNotPermissionDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to assign over {0} users to the door {1}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgUnableToAssignOverMaxUser {
            get {
                return ResourceManager.GetString("msgUnableToAssignOverMaxUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unassign door(s) from access group successfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgUnAssignDoors {
            get {
                return ResourceManager.GetString("msgUnAssignDoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unassign foor(s) from access group successfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgUnAssignFoors {
            get {
                return ResourceManager.GetString("msgUnAssignFoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unassign user(s) from access group successfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgUnAssignUsers {
            get {
                return ResourceManager.GetString("msgUnAssignUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unassign user(s) from door successfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgUnAssignUsersFromDoor {
            get {
                return ResourceManager.GetString("msgUnAssignUsersFromDoor", resourceCulture);
            }
        }
    }
}
