//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.AccountResource", typeof(AccountResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lblAdd {
            get {
                return ResourceManager.GetString("lblAdd", resourceCulture);
            }
        }
        
        public static string lblAddNew {
            get {
                return ResourceManager.GetString("lblAddNew", resourceCulture);
            }
        }
        
        public static string lblComanyCode {
            get {
                return ResourceManager.GetString("lblComanyCode", resourceCulture);
            }
        }
        
        public static string lblConfirmPassword {
            get {
                return ResourceManager.GetString("lblConfirmPassword", resourceCulture);
            }
        }
        
        public static string lblDeleteMultiple {
            get {
                return ResourceManager.GetString("lblDeleteMultiple", resourceCulture);
            }
        }
        
        public static string lblEmailAddressOrUsername {
            get {
                return ResourceManager.GetString("lblEmailAddressOrUsername", resourceCulture);
            }
        }
        
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        public static string lblConfirmNewPassword {
            get {
                return ResourceManager.GetString("lblConfirmNewPassword", resourceCulture);
            }
        }
        
        public static string lblRemeberMe {
            get {
                return ResourceManager.GetString("lblRemeberMe", resourceCulture);
            }
        }
        
        public static string lblToken {
            get {
                return ResourceManager.GetString("lblToken", resourceCulture);
            }
        }
        
        public static string lblUpdate {
            get {
                return ResourceManager.GetString("lblUpdate", resourceCulture);
            }
        }
        
        public static string lblAccount {
            get {
                return ResourceManager.GetString("lblAccount", resourceCulture);
            }
        }
        
        public static string lblUsername {
            get {
                return ResourceManager.GetString("lblUsername", resourceCulture);
            }
        }
        
        public static string lblNewPassword {
            get {
                return ResourceManager.GetString("lblNewPassword", resourceCulture);
            }
        }
        
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        public static string lblAccountList {
            get {
                return ResourceManager.GetString("lblAccountList", resourceCulture);
            }
        }
        
        public static string lblAccounts {
            get {
                return ResourceManager.GetString("lblAccounts", resourceCulture);
            }
        }
        
        public static string msgNotDelete {
            get {
                return ResourceManager.GetString("msgNotDelete", resourceCulture);
            }
        }
        
        public static string lblRole {
            get {
                return ResourceManager.GetString("lblRole", resourceCulture);
            }
        }
        
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        public static string msgInvalidCompany {
            get {
                return ResourceManager.GetString("msgInvalidCompany", resourceCulture);
            }
        }
        
        public static string lblEnterYourEmail {
            get {
                return ResourceManager.GetString("lblEnterYourEmail", resourceCulture);
            }
        }
        
        public static string lblForgotPassword {
            get {
                return ResourceManager.GetString("lblForgotPassword", resourceCulture);
            }
        }
        
        public static string lblYourEmailAddress {
            get {
                return ResourceManager.GetString("lblYourEmailAddress", resourceCulture);
            }
        }
        
        public static string msgEmailNotExist {
            get {
                return ResourceManager.GetString("msgEmailNotExist", resourceCulture);
            }
        }
        
        public static string msgResetPassword {
            get {
                return ResourceManager.GetString("msgResetPassword", resourceCulture);
            }
        }
        
        public static string lblContact {
            get {
                return ResourceManager.GetString("lblContact", resourceCulture);
            }
        }
        
        public static string lblContactInfo {
            get {
                return ResourceManager.GetString("lblContactInfo", resourceCulture);
            }
        }
        
        public static string msgInvalidAccount {
            get {
                return ResourceManager.GetString("msgInvalidAccount", resourceCulture);
            }
        }
        
        public static string msgCompanyNonExist {
            get {
                return ResourceManager.GetString("msgCompanyNonExist", resourceCulture);
            }
        }
        
        public static string msgChangePassword {
            get {
                return ResourceManager.GetString("msgChangePassword", resourceCulture);
            }
        }
        
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        public static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        public static string lblLogout {
            get {
                return ResourceManager.GetString("lblLogout", resourceCulture);
            }
        }
        
        public static string msgCompanyExpired {
            get {
                return ResourceManager.GetString("msgCompanyExpired", resourceCulture);
            }
        }
        
        public static string msgInvalidAccountType {
            get {
                return ResourceManager.GetString("msgInvalidAccountType", resourceCulture);
            }
        }
        
        public static string msgNonAccount {
            get {
                return ResourceManager.GetString("msgNonAccount", resourceCulture);
            }
        }
        
        public static string msgChangeCompany {
            get {
                return ResourceManager.GetString("msgChangeCompany", resourceCulture);
            }
        }
        
        public static string lblImageLimit {
            get {
                return ResourceManager.GetString("lblImageLimit", resourceCulture);
            }
        }
        
        public static string msgWrongPassword {
            get {
                return ResourceManager.GetString("msgWrongPassword", resourceCulture);
            }
        }
        
        public static string msgChangePassSuccess {
            get {
                return ResourceManager.GetString("msgChangePassSuccess", resourceCulture);
            }
        }
        
        public static string msgChangePasswordDefault {
            get {
                return ResourceManager.GetString("msgChangePasswordDefault", resourceCulture);
            }
        }
        
        public static string msgAccountNotLinkUser {
            get {
                return ResourceManager.GetString("msgAccountNotLinkUser", resourceCulture);
            }
        }
        
        public static string msgPasswordExpired {
            get {
                return ResourceManager.GetString("msgPasswordExpired", resourceCulture);
            }
        }
        
        public static string msgSamePasswordBefore {
            get {
                return ResourceManager.GetString("msgSamePasswordBefore", resourceCulture);
            }
        }
        
        public static string msgDeleteApprovalAccount {
            get {
                return ResourceManager.GetString("msgDeleteApprovalAccount", resourceCulture);
            }
        }
        
        public static string msgSessionExpired {
            get {
                return ResourceManager.GetString("msgSessionExpired", resourceCulture);
            }
        }
        
        public static string msgAccountUseOther {
            get {
                return ResourceManager.GetString("msgAccountUseOther", resourceCulture);
            }
        }
        
        public static string msgEmptyAvatar {
            get {
                return ResourceManager.GetString("msgEmptyAvatar", resourceCulture);
            }
        }
        
        public static string msgIsTextBase64Avatar {
            get {
                return ResourceManager.GetString("msgIsTextBase64Avatar", resourceCulture);
            }
        }
        
        public static string msgInvalidTimezon {
            get {
                return ResourceManager.GetString("msgInvalidTimezon", resourceCulture);
            }
        }
        
        public static string msgInvalidUser {
            get {
                return ResourceManager.GetString("msgInvalidUser", resourceCulture);
            }
        }
        
        public static string msgCanNotChangeRolePrimaryToSystem {
            get {
                return ResourceManager.GetString("msgCanNotChangeRolePrimaryToSystem", resourceCulture);
            }
        }
        
        public static string lblUserId {
            get {
                return ResourceManager.GetString("lblUserId", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Please change your password on first login for security purposes..
        /// </summary>
        public static string msgPasswordChangeFirstLogin {
            get {
                return ResourceManager.GetString("msgPasswordChangeFirstLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change is required.
        /// </summary>
        public static string msgPasswordChangeRequired {
            get {
                return ResourceManager.GetString("msgPasswordChangeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not meet complexity requirements.
        /// </summary>
        public static string msgPasswordComplexity {
            get {
                return ResourceManager.GetString("msgPasswordComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day(s) have passed since you changed your password. Please update your password..
        /// </summary>
        public static string msgPasswordExpiredWithDays {
            get {
                return ResourceManager.GetString("msgPasswordExpiredWithDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to change your password to enhance security.
        /// </summary>
        public static string msgPasswordNeedToChange {
            get {
                return ResourceManager.GetString("msgPasswordNeedToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one number..
        /// </summary>
        public static string msgPasswordRequireNumber {
            get {
                return ResourceManager.GetString("msgPasswordRequireNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one special character (!@#$%^`)..
        /// </summary>
        public static string msgPasswordRequireSpecialChar {
            get {
                return ResourceManager.GetString("msgPasswordRequireSpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter..
        /// </summary>
        public static string msgPasswordRequireUppercase {
            get {
                return ResourceManager.GetString("msgPasswordRequireUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password will expire in {0} days. Please change it soon..
        /// </summary>
        public static string msgPasswordWillExpireSoon {
            get {
                return ResourceManager.GetString("msgPasswordWillExpireSoon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your account is locked. Please try again after {0} minute(s)..
        /// </summary>
        public static string msgAccountLockedWithDuration
        {
            get
            {
                return ResourceManager.GetString("msgAccountLockedWithDuration", resourceCulture);
            }
        }
         /// <summary>
        ///   Looks up a localized string similar to Your account is locked..
        /// </summary>
        public static string msgAccountLocked {
            get {
                return ResourceManager.GetString("msgAccountLocked", resourceCulture);
            }
        }
        
        public static string msgInvalidPassWordFormat {
            get {
                return ResourceManager.GetString("msgInvalidPassWordFormat", resourceCulture);
            }
        }
        
    }
}
