//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ActionLogTypeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActionLogTypeResource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.ActionLogTypeResource", typeof(ActionLogTypeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Accessible Door Export과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AccessibleDoorExport {
            get {
                return ResourceManager.GetString("AccessibleDoorExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Active door과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ActiveDoor {
            get {
                return ResourceManager.GetString("ActiveDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add new master과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AddMaster {
            get {
                return ResourceManager.GetString("AddMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Analysis Export과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AnalysisExport {
            get {
                return ResourceManager.GetString("AnalysisExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assign Door(s)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AssignDoor {
            get {
                return ResourceManager.GetString("AssignDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assign User과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AssignUser {
            get {
                return ResourceManager.GetString("AssignUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assign user(s) to the door과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AssignUsersToDoor {
            get {
                return ResourceManager.GetString("AssignUsersToDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Register과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AutoRegister {
            get {
                return ResourceManager.GetString("AutoRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Basic Info Transmit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BasicInfoTransmit {
            get {
                return ResourceManager.GetString("BasicInfoTransmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change timezone과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ChangeTimezone {
            get {
                return ResourceManager.GetString("ChangeTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy Door Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy Door Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CopyDoorSetting {
            get {
                return ResourceManager.GetString("CopyDoorSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete existing master과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeleteMaster {
            get {
                return ResourceManager.GetString("DeleteMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete multiple과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeleteMultiple {
            get {
                return ResourceManager.GetString("DeleteMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete multiple {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeleteMultipleType {
            get {
                return ResourceManager.GetString("DeleteMultipleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Door Delete Multiple과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DoorDeleteMultiple {
            get {
                return ResourceManager.GetString("DoorDeleteMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Door Open과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DoorOpen {
            get {
                return ResourceManager.GetString("DoorOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Door Update과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DoorUpdate {
            get {
                return ResourceManager.GetString("DoorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Event Export과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EventExport {
            get {
                return ResourceManager.GetString("EventExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export doors과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExportDoor {
            get {
                return ResourceManager.GetString("ExportDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export building masters과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ExportMaster {
            get {
                return ResourceManager.GetString("ExportMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emergency close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ForcedClose {
            get {
                return ResourceManager.GetString("ForcedClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emergency open과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ForcedOpen {
            get {
                return ResourceManager.GetString("ForcedOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Holiday Transmit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HolidayTransmit {
            get {
                return ResourceManager.GetString("HolidayTransmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inactive Door과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InactiveDoor {
            get {
                return ResourceManager.GetString("InactiveDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Door과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InvalidDoor {
            get {
                return ResourceManager.GetString("InvalidDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logout과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change department of user과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MoveDepartment {
            get {
                return ResourceManager.GetString("MoveDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recovery과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Recovery {
            get {
                return ResourceManager.GetString("Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registered User Export과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RegisteredUserExport {
            get {
                return ResourceManager.GetString("RegisteredUserExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reinstall door setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Reinstall {
            get {
                return ResourceManager.GetString("Reinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emergency Release과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reboot과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sync time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SetTime {
            get {
                return ResourceManager.GetString("SetTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Success과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sync과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Log Export과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemLogExport {
            get {
                return ResourceManager.GetString("SystemLogExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timezone Transmit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TimezoneTransmit {
            get {
                return ResourceManager.GetString("TimezoneTransmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transmit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Transmit {
            get {
                return ResourceManager.GetString("Transmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unassign Door과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UnassignDoor {
            get {
                return ResourceManager.GetString("UnassignDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unassign User과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UnassignUser {
            get {
                return ResourceManager.GetString("UnassignUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Door과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateDoor {
            get {
                return ResourceManager.GetString("UpdateDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Meal Service Price과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateMealServicePrice {
            get {
                return ResourceManager.GetString("UpdateMealServicePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Multiple User과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateMultipleUser {
            get {
                return ResourceManager.GetString("UpdateMultipleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UserAdd {
            get {
                return ResourceManager.GetString("UserAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UserDelete {
            get {
                return ResourceManager.GetString("UserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Delete Multiple과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UserDeleteMultiple {
            get {
                return ResourceManager.GetString("UserDeleteMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Valid Door과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ValidDoor {
            get {
                return ResourceManager.GetString("ValidDoor", resourceCulture);
            }
        }
    }
}
