//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BookResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BookResource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.BookResource", typeof(BookResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Author과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblAuthor {
            get {
                return ResourceManager.GetString("lblAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Available과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblAvailable {
            get {
                return ResourceManager.GetString("lblAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   book과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblBook {
            get {
                return ResourceManager.GetString("lblBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Book area과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblBookArea {
            get {
                return ResourceManager.GetString("lblBookArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Book name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblBookName {
            get {
                return ResourceManager.GetString("lblBookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Borrow Date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblBorrowDate {
            get {
                return ResourceManager.GetString("lblBorrowDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Borrower과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblBorrowerName {
            get {
                return ResourceManager.GetString("lblBorrowerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created On과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblCreatedOn {
            get {
                return ResourceManager.GetString("lblCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deadline Date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblDeadlineDate {
            get {
                return ResourceManager.GetString("lblDeadlineDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ISBN Number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblIsbnNumber {
            get {
                return ResourceManager.GetString("lblIsbnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paid과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblPaid {
            get {
                return ResourceManager.GetString("lblPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rented과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblRented {
            get {
                return ResourceManager.GetString("lblRented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Renting Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblRentingStatus {
            get {
                return ResourceManager.GetString("lblRentingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return Date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblReturnDate {
            get {
                return ResourceManager.GetString("lblReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UnPaid과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblUnPaid {
            get {
                return ResourceManager.GetString("lblUnPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BookArea not existed in system과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgBookAreaNotExisted {
            get {
                return ResourceManager.GetString("msgBookAreaNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Book not existed in system과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgBookNotExisted {
            get {
                return ResourceManager.GetString("msgBookNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Book was rented과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgBookRented {
            get {
                return ResourceManager.GetString("msgBookRented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Borrow Book Success과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgBorrowBookSuccess {
            get {
                return ResourceManager.GetString("msgBorrowBookSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return time must be greater than borrowing time.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgDeadlineRequired {
            get {
                return ResourceManager.GetString("msgDeadlineRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extend book success과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgExtendBookSuccess {
            get {
                return ResourceManager.GetString("msgExtendBookSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List of books were imported complete!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgImportBookComplete {
            get {
                return ResourceManager.GetString("msgImportBookComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List of books are importing. Please wait...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgImportBookProcess {
            get {
                return ResourceManager.GetString("msgImportBookProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ISBN number is existed in system과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgIsbnNumberExisted {
            get {
                return ResourceManager.GetString("msgIsbnNumberExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Book Area Name Existed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgNameBookAreaExisted {
            get {
                return ResourceManager.GetString("msgNameBookAreaExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return Book Success과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgReturnBookSuccess {
            get {
                return ResourceManager.GetString("msgReturnBookSuccess", resourceCulture);
            }
        }
    }
}
