//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CameraResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CameraResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.CameraResource", typeof(CameraResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string DuplicateCameraId {
            get {
                return ResourceManager.GetString("DuplicateCameraId", resourceCulture);
            }
        }
        
        public static string AccessTokenWrong {
            get {
                return ResourceManager.GetString("AccessTokenWrong", resourceCulture);
            }
        }
        
        public static string NotificationProcess {
            get {
                return ResourceManager.GetString("NotificationProcess", resourceCulture);
            }
        }
        
        public static string QrInvalid {
            get {
                return ResourceManager.GetString("QrInvalid", resourceCulture);
            }
        }
        
        public static string UploadAvatarFailed {
            get {
                return ResourceManager.GetString("UploadAvatarFailed", resourceCulture);
            }
        }
        
        public static string SyncDataComplete {
            get {
                return ResourceManager.GetString("SyncDataComplete", resourceCulture);
            }
        }
        
        public static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        public static string AllCamerasOffline {
            get {
                return ResourceManager.GetString("AllCamerasOffline", resourceCulture);
            }
        }
        
        public static string lblCameraHanet {
            get {
                return ResourceManager.GetString("lblCameraHanet", resourceCulture);
            }
        }
        
        public static string lblCameraLPR {
            get {
                return ResourceManager.GetString("lblCameraLPR", resourceCulture);
            }
        }
        
        public static string lblCameraCCTV {
            get {
                return ResourceManager.GetString("lblCameraCCTV", resourceCulture);
            }
        }
        
        public static string InvalidCamera {
            get {
                return ResourceManager.GetString("InvalidCamera", resourceCulture);
            }
        }
        
        public static string CreateFaceIdSuccess {
            get {
                return ResourceManager.GetString("CreateFaceIdSuccess", resourceCulture);
            }
        }
        
        public static string titleCreateFaceId {
            get {
                return ResourceManager.GetString("titleCreateFaceId", resourceCulture);
            }
        }
        
        public static string contentNewVisitWebhook {
            get {
                return ResourceManager.GetString("contentNewVisitWebhook", resourceCulture);
            }
        }
        
        public static string contentNewUserWebhook {
            get {
                return ResourceManager.GetString("contentNewUserWebhook", resourceCulture);
            }
        }
        
        public static string contentUpdateVisitWebhook {
            get {
                return ResourceManager.GetString("contentUpdateVisitWebhook", resourceCulture);
            }
        }
        
        public static string contentDeleteVisitWebhook {
            get {
                return ResourceManager.GetString("contentDeleteVisitWebhook", resourceCulture);
            }
        }
        
        public static string contentUpdateUserWebhook {
            get {
                return ResourceManager.GetString("contentUpdateUserWebhook", resourceCulture);
            }
        }
        
        public static string contentDeleteUserWebhook {
            get {
                return ResourceManager.GetString("contentDeleteUserWebhook", resourceCulture);
            }
        }
        
        public static string contentUpdateCameraSetting {
            get {
                return ResourceManager.GetString("contentUpdateCameraSetting", resourceCulture);
            }
        }
        
        public static string contentUpdateCameraSettingRefresh {
            get {
                return ResourceManager.GetString("contentUpdateCameraSettingRefresh", resourceCulture);
            }
        }
        
        public static string lblChangeSetting {
            get {
                return ResourceManager.GetString("lblChangeSetting", resourceCulture);
            }
        }
        
        public static string lblCameraDC {
            get {
                return ResourceManager.GetString("lblCameraDC", resourceCulture);
            }
        }
        
        public static string lblCameraId {
            get {
                return ResourceManager.GetString("lblCameraId", resourceCulture);
            }
        }
        
        public static string lblCameraName {
            get {
                return ResourceManager.GetString("lblCameraName", resourceCulture);
            }
        }
        
        public static string lblVideoLength {
            get {
                return ResourceManager.GetString("lblVideoLength", resourceCulture);
            }
        }
    }
}
