//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CanteenResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CanteenResource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.CanteenResource", typeof(CanteenResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Can not remove data created by manual과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeleteMealEventLog {
            get {
                return ResourceManager.GetString("DeleteMealEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Additional과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string exceptionalUserTypeAdditional {
            get {
                return ResourceManager.GetString("exceptionalUserTypeAdditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string exceptionalUserTypeDiscount {
            get {
                return ResourceManager.GetString("exceptionalUserTypeDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specified과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string exceptionalUserTypeSpecified {
            get {
                return ResourceManager.GetString("exceptionalUserTypeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Corner과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblCornerSetting {
            get {
                return ResourceManager.GetString("lblCornerSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExceptionalMeal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblExceptionalMeal {
            get {
                return ResourceManager.GetString("lblExceptionalMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MealEventLog과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblMealEventLog {
            get {
                return ResourceManager.GetString("lblMealEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Meal Service Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblMealServiceTime {
            get {
                return ResourceManager.GetString("lblMealServiceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Meal Service Time Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblMealServiceTimeName {
            get {
                return ResourceManager.GetString("lblMealServiceTimeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MealSetting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblMealSetting {
            get {
                return ResourceManager.GetString("lblMealSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Meal Service과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblMealType {
            get {
                return ResourceManager.GetString("lblMealType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This meal service is used in a Meal service time!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblMealTypeCannotDelete {
            get {
                return ResourceManager.GetString("lblMealTypeCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exceptional User과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblUserDiscount {
            get {
                return ResourceManager.GetString("lblUserDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FirstAccessTime could not be bigger than LastAccessTime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgCompareAccessTime {
            get {
                return ResourceManager.GetString("msgCompareAccessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The code is duplicated in system.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgDuplicatedCode {
            get {
                return ResourceManager.GetString("msgDuplicatedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input FirstAccessTime and LastAccessTime please과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgInputAccessTime {
            get {
                return ResourceManager.GetString("msgInputAccessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The code can not be empty.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgMealTypeCodeIsNull {
            get {
                return ResourceManager.GetString("msgMealTypeCodeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name can not be empty.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgNameIsNull {
            get {
                return ResourceManager.GetString("msgNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please create a corner first.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgNullCorner {
            get {
                return ResourceManager.GetString("msgNullCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start time or end time cannot be part of another mealsetting timeline과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgRangeTimeExists {
            get {
                return ResourceManager.GetString("msgRangeTimeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can only search for periods of 3 months과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgSearchLimitedAccessTime {
            get {
                return ResourceManager.GetString("msgSearchLimitedAccessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
    }
}
