//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CardIssuingResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardIssuingResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.CardIssuingResource", typeof(CardIssuingResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lblTemporaryAccessCard {
            get {
                return ResourceManager.GetString("lblTemporaryAccessCard", resourceCulture);
            }
        }
        
        public static string lblAccessCard {
            get {
                return ResourceManager.GetString("lblAccessCard", resourceCulture);
            }
        }
        
        public static string lblVisitCard {
            get {
                return ResourceManager.GetString("lblVisitCard", resourceCulture);
            }
        }
        
        public static string lblSoldier {
            get {
                return ResourceManager.GetString("lblSoldier", resourceCulture);
            }
        }
        
        public static string lblFamily {
            get {
                return ResourceManager.GetString("lblFamily", resourceCulture);
            }
        }
        
        public static string lblRegularCivilian {
            get {
                return ResourceManager.GetString("lblRegularCivilian", resourceCulture);
            }
        }
        
        public static string lblResidentCivilian {
            get {
                return ResourceManager.GetString("lblResidentCivilian", resourceCulture);
            }
        }
        
        public static string lblConstruction {
            get {
                return ResourceManager.GetString("lblConstruction", resourceCulture);
            }
        }
        
        public static string lblMeetingVisit {
            get {
                return ResourceManager.GetString("lblMeetingVisit", resourceCulture);
            }
        }
        
        public static string lblTraning {
            get {
                return ResourceManager.GetString("lblTraning", resourceCulture);
            }
        }
        
        public static string lblCardReader {
            get {
                return ResourceManager.GetString("lblCardReader", resourceCulture);
            }
        }
        
        public static string lblCardPrinter {
            get {
                return ResourceManager.GetString("lblCardPrinter", resourceCulture);
            }
        }
        
        public static string lblVerticalAlignment {
            get {
                return ResourceManager.GetString("lblVerticalAlignment", resourceCulture);
            }
        }
        
        public static string lblHorizontalAlignment {
            get {
                return ResourceManager.GetString("lblHorizontalAlignment", resourceCulture);
            }
        }
        
        public static string msgIpAddressInUse {
            get {
                return ResourceManager.GetString("msgIpAddressInUse", resourceCulture);
            }
        }
        
        public static string msgNameInUse {
            get {
                return ResourceManager.GetString("msgNameInUse", resourceCulture);
            }
        }
        
        public static string lblCardLayout {
            get {
                return ResourceManager.GetString("lblCardLayout", resourceCulture);
            }
        }
        
        public static string lblManagementNumber {
            get {
                return ResourceManager.GetString("lblManagementNumber", resourceCulture);
            }
        }
        
        public static string lblAccidentType {
            get {
                return ResourceManager.GetString("lblAccidentType", resourceCulture);
            }
        }
        
        public static string lblPersonCardType {
            get {
                return ResourceManager.GetString("lblPersonCardType", resourceCulture);
            }
        }
        
        public static string msgDeviceConnectFailed {
            get {
                return ResourceManager.GetString("msgDeviceConnectFailed", resourceCulture);
            }
        }
        
        public static string msgDeviceConnectSuccess {
            get {
                return ResourceManager.GetString("msgDeviceConnectSuccess", resourceCulture);
            }
        }
        
        public static string ConnectTimeout {
            get {
                return ResourceManager.GetString("ConnectTimeout", resourceCulture);
            }
        }
        
        public static string msgRequireConnectToDevice {
            get {
                return ResourceManager.GetString("msgRequireConnectToDevice", resourceCulture);
            }
        }
        
        public static string msgPleaseWaitForPrinting {
            get {
                return ResourceManager.GetString("msgPleaseWaitForPrinting", resourceCulture);
            }
        }
        
        public static string msgPrintCardSuccess {
            get {
                return ResourceManager.GetString("msgPrintCardSuccess", resourceCulture);
            }
        }
        
        public static string msgPrintCardError {
            get {
                return ResourceManager.GetString("msgPrintCardError", resourceCulture);
            }
        }
        
        public static string lblCardType {
            get {
                return ResourceManager.GetString("lblCardType", resourceCulture);
            }
        }
        
        public static string lblCardName {
            get {
                return ResourceManager.GetString("lblCardName", resourceCulture);
            }
        }
        
        public static string lblRegisteredDate {
            get {
                return ResourceManager.GetString("lblRegisteredDate", resourceCulture);
            }
        }
        
        public static string lblCardId {
            get {
                return ResourceManager.GetString("lblCardId", resourceCulture);
            }
        }
        
        public static string lblDepartment {
            get {
                return ResourceManager.GetString("lblDepartment", resourceCulture);
            }
        }
        
        public static string lblIssuedDate {
            get {
                return ResourceManager.GetString("lblIssuedDate", resourceCulture);
            }
        }
        
        public static string lblIssuer {
            get {
                return ResourceManager.GetString("lblIssuer", resourceCulture);
            }
        }
        
        public static string lblRemark {
            get {
                return ResourceManager.GetString("lblRemark", resourceCulture);
            }
        }
        
        public static string lblReturnedDate {
            get {
                return ResourceManager.GetString("lblReturnedDate", resourceCulture);
            }
        }
        
        public static string lblPosition {
            get {
                return ResourceManager.GetString("lblPosition", resourceCulture);
            }
        }
        
        public static string lblCardStatus {
            get {
                return ResourceManager.GetString("lblCardStatus", resourceCulture);
            }
        }
        
        public static string lblMsn {
            get {
                return ResourceManager.GetString("lblMsn", resourceCulture);
            }
        }
        
        public static string lblNewStatus {
            get {
                return ResourceManager.GetString("lblNewStatus", resourceCulture);
            }
        }
        
        public static string lblOldStatus {
            get {
                return ResourceManager.GetString("lblOldStatus", resourceCulture);
            }
        }
        
        public static string lblUpdatedOn {
            get {
                return ResourceManager.GetString("lblUpdatedOn", resourceCulture);
            }
        }
        
        public static string lblUpdatedBy {
            get {
                return ResourceManager.GetString("lblUpdatedBy", resourceCulture);
            }
        }
        
        public static string lblNote {
            get {
                return ResourceManager.GetString("lblNote", resourceCulture);
            }
        }
        
        public static string lblIDPSmartCardPrinter {
            get {
                return ResourceManager.GetString("lblIDPSmartCardPrinter", resourceCulture);
            }
        }
        
        public static string lblBackGround {
            get {
                return ResourceManager.GetString("lblBackGround", resourceCulture);
            }
        }
        
        public static string lblPictureFixed {
            get {
                return ResourceManager.GetString("lblPictureFixed", resourceCulture);
            }
        }
        
        public static string lblPictureUser {
            get {
                return ResourceManager.GetString("lblPictureUser", resourceCulture);
            }
        }
        
        public static string lblTextFixed {
            get {
                return ResourceManager.GetString("lblTextFixed", resourceCulture);
            }
        }
        
        public static string lblTextDbInfo {
            get {
                return ResourceManager.GetString("lblTextDbInfo", resourceCulture);
            }
        }
        
        public static string lblIssueCount {
            get {
                return ResourceManager.GetString("lblIssueCount", resourceCulture);
            }
        }
        
        public static string msgUserAssignedCard {
            get {
                return ResourceManager.GetString("msgUserAssignedCard", resourceCulture);
            }
        }
        
        public static string msgErrorCheckQueue {
            get {
                return ResourceManager.GetString("msgErrorCheckQueue", resourceCulture);
            }
        }
        
        public static string msgPrintQueue {
            get {
                return ResourceManager.GetString("msgPrintQueue", resourceCulture);
            }
        }
        
        public static string msgNotFinishedYet {
            get {
                return ResourceManager.GetString("msgNotFinishedYet", resourceCulture);
            }
        }
        
        public static string lblCXD80 {
            get {
                return ResourceManager.GetString("lblCXD80", resourceCulture);
            }
        }
    }
}
