//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CompanyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompanyResource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.CompanyResource", typeof(CompanyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add new company.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblAddNew {
            get {
                return ResourceManager.GetString("lblAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Admin과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblAdmin {
            get {
                return ResourceManager.GetString("lblAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblClear {
            get {
                return ResourceManager.GetString("lblClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Company과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblCompany {
            get {
                return ResourceManager.GetString("lblCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Company Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblCompanyCode {
            get {
                return ResourceManager.GetString("lblCompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Company list과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblCompanyList {
            get {
                return ResourceManager.GetString("lblCompanyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblCompanyLogo {
            get {
                return ResourceManager.GetString("lblCompanyLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mini Logo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblCompanyMiniLogo {
            get {
                return ResourceManager.GetString("lblCompanyMiniLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Company Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblCompanyName {
            get {
                return ResourceManager.GetString("lblCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblConfirmPassword {
            get {
                return ResourceManager.GetString("lblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contact과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblContact {
            get {
                return ResourceManager.GetString("lblContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created Date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblCreatedDate {
            get {
                return ResourceManager.GetString("lblCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete multiple company과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblDeleteMultiple {
            get {
                return ResourceManager.GetString("lblDeleteMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expired Date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblExpiredDate {
            get {
                return ResourceManager.GetString("lblExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expired Date From과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblExpiredDateFrom {
            get {
                return ResourceManager.GetString("lblExpiredDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblExpiredDateTo {
            get {
                return ResourceManager.GetString("lblExpiredDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Optimal size 176 x 40 pixels과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblOptimalSizeLogo {
            get {
                return ResourceManager.GetString("lblOptimalSizeLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Optimal size 59 x 40 pixels.&lt;br/&gt;Logo used for collapse left menu.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblOptimalSizeMiniLogo {
            get {
                return ResourceManager.GetString("lblOptimalSizeMiniLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Note과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblRemarks {
            get {
                return ResourceManager.GetString("lblRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update company과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblUpdateCompany {
            get {
                return ResourceManager.GetString("lblUpdateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Admin account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assign door(s) to the company {0} (Company Name) successfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgAssingDoors {
            get {
                return ResourceManager.GetString("msgAssingDoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The account has been changed from {0} to {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgChangeAccount {
            get {
                return ResourceManager.GetString("msgChangeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The  contact has been changed from {0} to {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgChangeContact {
            get {
                return ResourceManager.GetString("msgChangeContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The password has been changed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgChangePassword {
            get {
                return ResourceManager.GetString("msgChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete company.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgDelete {
            get {
                return ResourceManager.GetString("msgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The root company can not be deleted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgNotDelete {
            get {
                return ResourceManager.GetString("msgNotDelete", resourceCulture);
            }
        }
    }
}
