//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DeviceResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeviceResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.DeviceResource", typeof(DeviceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lblAccessTimezone {
            get {
                return ResourceManager.GetString("lblAccessTimezone", resourceCulture);
            }
        }
        
        public static string lblAddNew {
            get {
                return ResourceManager.GetString("lblAddNew", resourceCulture);
            }
        }
        
        public static string lblAlarm {
            get {
                return ResourceManager.GetString("lblAlarm", resourceCulture);
            }
        }
        
        public static string lblAntiPassback {
            get {
                return ResourceManager.GetString("lblAntiPassback", resourceCulture);
            }
        }
        
        public static string lblBlue {
            get {
                return ResourceManager.GetString("lblBlue", resourceCulture);
            }
        }
        
        public static string lblBuilding {
            get {
                return ResourceManager.GetString("lblBuilding", resourceCulture);
            }
        }
        
        public static string lblCardReaderLed {
            get {
                return ResourceManager.GetString("lblCardReaderLed", resourceCulture);
            }
        }
        
        public static string lblChooseAtLeast {
            get {
                return ResourceManager.GetString("lblChooseAtLeast", resourceCulture);
            }
        }
        
        public static string lblCloseReverseLock {
            get {
                return ResourceManager.GetString("lblCloseReverseLock", resourceCulture);
            }
        }
        
        public static string lblCondition {
            get {
                return ResourceManager.GetString("lblCondition", resourceCulture);
            }
        }
        
        public static string lblMprInterval {
            get {
                return ResourceManager.GetString("lblMprInterval", resourceCulture);
            }
        }
        
        public static string lblConnectionStatus {
            get {
                return ResourceManager.GetString("lblConnectionStatus", resourceCulture);
            }
        }
        
        public static string lblDe950 {
            get {
                return ResourceManager.GetString("lblDe950", resourceCulture);
            }
        }
        
        public static string lblDeAbcm {
            get {
                return ResourceManager.GetString("lblDeAbcm", resourceCulture);
            }
        }
        
        public static string lblDeleteMultipleDevice {
            get {
                return ResourceManager.GetString("lblDeleteMultipleDevice", resourceCulture);
            }
        }
        
        public static string lblDevice {
            get {
                return ResourceManager.GetString("lblDevice", resourceCulture);
            }
        }
        
        public static string lblDeviceAddress {
            get {
                return ResourceManager.GetString("lblDeviceAddress", resourceCulture);
            }
        }
        
        public static string lblDeviceList {
            get {
                return ResourceManager.GetString("lblDeviceList", resourceCulture);
            }
        }
        
        public static string lblDeviceSetting {
            get {
                return ResourceManager.GetString("lblDeviceSetting", resourceCulture);
            }
        }
        
        public static string lblDeviceType {
            get {
                return ResourceManager.GetString("lblDeviceType", resourceCulture);
            }
        }
        
        public static string lblDoorActiveTimezone {
            get {
                return ResourceManager.GetString("lblDoorActiveTimezone", resourceCulture);
            }
        }
        
        public static string lblDoorName {
            get {
                return ResourceManager.GetString("lblDoorName", resourceCulture);
            }
        }
        
        public static string lblDoorPassageTimezone {
            get {
                return ResourceManager.GetString("lblDoorPassageTimezone", resourceCulture);
            }
        }
        
        public static string lblDoorSensorType {
            get {
                return ResourceManager.GetString("lblDoorSensorType", resourceCulture);
            }
        }
        
        public static string lblEntrance {
            get {
                return ResourceManager.GetString("lblEntrance", resourceCulture);
            }
        }
        
        public static string lblReception {
            get {
                return ResourceManager.GetString("lblReception", resourceCulture);
            }
        }
        
        public static string lblHardPassback {
            get {
                return ResourceManager.GetString("lblHardPassback", resourceCulture);
            }
        }
        
        public static string lblIcu300N {
            get {
                return ResourceManager.GetString("lblIcu300N", resourceCulture);
            }
        }
        
        public static string lblIcu300X {
            get {
                return ResourceManager.GetString("lblIcu300X", resourceCulture);
            }
        }
        
        public static string lblDe960 {
            get {
                return ResourceManager.GetString("lblDe960", resourceCulture);
            }
        }
        
        public static string lblITouchPop2A {
            get {
                return ResourceManager.GetString("lblITouchPop2A", resourceCulture);
            }
        }
        
        public static string lblAbcm {
            get {
                return ResourceManager.GetString("lblAbcm", resourceCulture);
            }
        }
        
        public static string lblSoundTrack01 {
            get {
                return ResourceManager.GetString("lblSoundTrack01", resourceCulture);
            }
        }
        
        public static string lblMainFirmware {
            get {
                return ResourceManager.GetString("lblMainFirmware", resourceCulture);
            }
        }
        
        public static string lblTransmitServerIp {
            get {
                return ResourceManager.GetString("lblTransmitServerIp", resourceCulture);
            }
        }
        
        public static string lblTransmitCurrentTime {
            get {
                return ResourceManager.GetString("lblTransmitCurrentTime", resourceCulture);
            }
        }
        
        public static string lblTransmitDeviceSetting {
            get {
                return ResourceManager.GetString("lblTransmitDeviceSetting", resourceCulture);
            }
        }
        
        public static string lblTransmitTimezoneSetting {
            get {
                return ResourceManager.GetString("lblTransmitTimezoneSetting", resourceCulture);
            }
        }
        
        public static string lblTransmitHolidaySetting {
            get {
                return ResourceManager.GetString("lblTransmitHolidaySetting", resourceCulture);
            }
        }
        
        public static string lblTransmitUserInfo {
            get {
                return ResourceManager.GetString("lblTransmitUserInfo", resourceCulture);
            }
        }
        
        public static string lblTransmitMessageSetting {
            get {
                return ResourceManager.GetString("lblTransmitMessageSetting", resourceCulture);
            }
        }
        
        public static string lblInReader {
            get {
                return ResourceManager.GetString("lblInReader", resourceCulture);
            }
        }
        
        public static string lblOutReader {
            get {
                return ResourceManager.GetString("lblOutReader", resourceCulture);
            }
        }
        
        public static string lblNfcModule {
            get {
                return ResourceManager.GetString("lblNfcModule", resourceCulture);
            }
        }
        
        public static string lblExtra {
            get {
                return ResourceManager.GetString("lblExtra", resourceCulture);
            }
        }
        
        public static string lblIn {
            get {
                return ResourceManager.GetString("lblIn", resourceCulture);
            }
        }
        
        public static string lblIpAddress {
            get {
                return ResourceManager.GetString("lblIpAddress", resourceCulture);
            }
        }
        
        public static string lbliTouchPop {
            get {
                return ResourceManager.GetString("lbliTouchPop", resourceCulture);
            }
        }
        
        public static string lblLastCommunicationTime {
            get {
                return ResourceManager.GetString("lblLastCommunicationTime", resourceCulture);
            }
        }
        
        public static string lblLockOpenDuration {
            get {
                return ResourceManager.GetString("lblLockOpenDuration", resourceCulture);
            }
        }
        
        public static string lblMacAddress {
            get {
                return ResourceManager.GetString("lblMacAddress", resourceCulture);
            }
        }
        
        public static string lblMultiPersonRule {
            get {
                return ResourceManager.GetString("lblMultiPersonRule", resourceCulture);
            }
        }
        
        public static string lblNetworkEnable {
            get {
                return ResourceManager.GetString("lblNetworkEnable", resourceCulture);
            }
        }
        
        public static string lblNone {
            get {
                return ResourceManager.GetString("lblNone", resourceCulture);
            }
        }
        
        public static string lblNormalClose {
            get {
                return ResourceManager.GetString("lblNormalClose", resourceCulture);
            }
        }
        
        public static string lblNormalOpen {
            get {
                return ResourceManager.GetString("lblNormalOpen", resourceCulture);
            }
        }
        
        public static string lblNumberOfNotTransmittingEvent {
            get {
                return ResourceManager.GetString("lblNumberOfNotTransmittingEvent", resourceCulture);
            }
        }
        
        public static string lblOpenDoor {
            get {
                return ResourceManager.GetString("lblOpenDoor", resourceCulture);
            }
        }
        
        public static string lblOut {
            get {
                return ResourceManager.GetString("lblOut", resourceCulture);
            }
        }
        
        public static string lblPunchInterval {
            get {
                return ResourceManager.GetString("lblPunchInterval", resourceCulture);
            }
        }
        
        public static string lblRed {
            get {
                return ResourceManager.GetString("lblRed", resourceCulture);
            }
        }
        
        public static string lblRegisterIdNumber {
            get {
                return ResourceManager.GetString("lblRegisterIdNumber", resourceCulture);
            }
        }
        
        public static string lblRestaurant {
            get {
                return ResourceManager.GetString("lblRestaurant", resourceCulture);
            }
        }
        
        public static string lblServerIp {
            get {
                return ResourceManager.GetString("lblServerIp", resourceCulture);
            }
        }
        
        public static string lblServerPort {
            get {
                return ResourceManager.GetString("lblServerPort", resourceCulture);
            }
        }
        
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        public static string lblStatusDelay {
            get {
                return ResourceManager.GetString("lblStatusDelay", resourceCulture);
            }
        }
        
        public static string lblOperationType {
            get {
                return ResourceManager.GetString("lblOperationType", resourceCulture);
            }
        }
        
        public static string lblUpdateDevice {
            get {
                return ResourceManager.GetString("lblUpdateDevice", resourceCulture);
            }
        }
        
        public static string lblUtc {
            get {
                return ResourceManager.GetString("lblUtc", resourceCulture);
            }
        }
        
        public static string lblVerifyMode {
            get {
                return ResourceManager.GetString("lblVerifyMode", resourceCulture);
            }
        }
        
        public static string lblVersion {
            get {
                return ResourceManager.GetString("lblVersion", resourceCulture);
            }
        }
        
        public static string lblWiegandFormat {
            get {
                return ResourceManager.GetString("lblWiegandFormat", resourceCulture);
            }
        }
        
        public static string msgActiveDoor {
            get {
                return ResourceManager.GetString("msgActiveDoor", resourceCulture);
            }
        }
        
        public static string msgChangeActiveTimezone {
            get {
                return ResourceManager.GetString("msgChangeActiveTimezone", resourceCulture);
            }
        }
        
        public static string msgChangeAntiPassback {
            get {
                return ResourceManager.GetString("msgChangeAntiPassback", resourceCulture);
            }
        }
        
        public static string msgChangeDevice {
            get {
                return ResourceManager.GetString("msgChangeDevice", resourceCulture);
            }
        }
        
        public static string msgChangeDeviceAddress {
            get {
                return ResourceManager.GetString("msgChangeDeviceAddress", resourceCulture);
            }
        }
        
        public static string msgChangeDoorName {
            get {
                return ResourceManager.GetString("msgChangeDoorName", resourceCulture);
            }
        }
        
        public static string msgChangeDoorSensorType {
            get {
                return ResourceManager.GetString("msgChangeDoorSensorType", resourceCulture);
            }
        }
        
        public static string msgChangeIpAddress {
            get {
                return ResourceManager.GetString("msgChangeIpAddress", resourceCulture);
            }
        }
        
        public static string msgChangeLockOpenDuration {
            get {
                return ResourceManager.GetString("msgChangeLockOpenDuration", resourceCulture);
            }
        }
        
        public static string msgChangeMprAccessTimezone {
            get {
                return ResourceManager.GetString("msgChangeMprAccessTimezone", resourceCulture);
            }
        }
        
        public static string msgChangeMprCondition {
            get {
                return ResourceManager.GetString("msgChangeMprCondition", resourceCulture);
            }
        }
        
        public static string msgChangeMprGroup {
            get {
                return ResourceManager.GetString("msgChangeMprGroup", resourceCulture);
            }
        }
        
        public static string msgChangePassageTimezone {
            get {
                return ResourceManager.GetString("msgChangePassageTimezone", resourceCulture);
            }
        }
        
        public static string msgChangeVerifyMode {
            get {
                return ResourceManager.GetString("msgChangeVerifyMode", resourceCulture);
            }
        }
        
        public static string msgChangeWgFormat {
            get {
                return ResourceManager.GetString("msgChangeWgFormat", resourceCulture);
            }
        }
        
        public static string msgConfirmSwitch {
            get {
                return ResourceManager.GetString("msgConfirmSwitch", resourceCulture);
            }
        }
        
        public static string msgCopyDeviceSetting {
            get {
                return ResourceManager.GetString("msgCopyDeviceSetting", resourceCulture);
            }
        }
        
        public static string msgDeleteMultipleDevices {
            get {
                return ResourceManager.GetString("msgDeleteMultipleDevices", resourceCulture);
            }
        }
        
        public static string msgDeviceAddressInUse {
            get {
                return ResourceManager.GetString("msgDeviceAddressInUse", resourceCulture);
            }
        }
        
        public static string msgDisableAlarm {
            get {
                return ResourceManager.GetString("msgDisableAlarm", resourceCulture);
            }
        }
        
        public static string msgDisableAntiPassback {
            get {
                return ResourceManager.GetString("msgDisableAntiPassback", resourceCulture);
            }
        }
        
        public static string msgDisableHardAntiPassback {
            get {
                return ResourceManager.GetString("msgDisableHardAntiPassback", resourceCulture);
            }
        }
        
        public static string msgDisableNetworkConnection {
            get {
                return ResourceManager.GetString("msgDisableNetworkConnection", resourceCulture);
            }
        }
        
        public static string msgEmergencyForcedClose {
            get {
                return ResourceManager.GetString("msgEmergencyForcedClose", resourceCulture);
            }
        }
        
        public static string msgEmergencyForcedOpen {
            get {
                return ResourceManager.GetString("msgEmergencyForcedOpen", resourceCulture);
            }
        }
        
        public static string msgEmergencyRelease {
            get {
                return ResourceManager.GetString("msgEmergencyRelease", resourceCulture);
            }
        }
        
        public static string msgEnableAlarm {
            get {
                return ResourceManager.GetString("msgEnableAlarm", resourceCulture);
            }
        }
        
        public static string msgEnableHardAntiPassback {
            get {
                return ResourceManager.GetString("msgEnableHardAntiPassback", resourceCulture);
            }
        }
        
        public static string msgEnableNetworkConnection {
            get {
                return ResourceManager.GetString("msgEnableNetworkConnection", resourceCulture);
            }
        }
        
        public static string msgInactiveDoor {
            get {
                return ResourceManager.GetString("msgInactiveDoor", resourceCulture);
            }
        }
        
        public static string msgInvalidDoor {
            get {
                return ResourceManager.GetString("msgInvalidDoor", resourceCulture);
            }
        }
        
        public static string msgReinstallDeviceSetting {
            get {
                return ResourceManager.GetString("msgReinstallDeviceSetting", resourceCulture);
            }
        }
        
        public static string msgSendDeviceCommand {
            get {
                return ResourceManager.GetString("msgSendDeviceCommand", resourceCulture);
            }
        }
        
        public static string msgSendDeviceMonitoringCommand {
            get {
                return ResourceManager.GetString("msgSendDeviceMonitoringCommand", resourceCulture);
            }
        }
        
        public static string msgSendEmergency {
            get {
                return ResourceManager.GetString("msgSendEmergency", resourceCulture);
            }
        }
        
        public static string msgValidDoor {
            get {
                return ResourceManager.GetString("msgValidDoor", resourceCulture);
            }
        }
        
        public static string lblAccessibleUsers {
            get {
                return ResourceManager.GetString("lblAccessibleUsers", resourceCulture);
            }
        }
        
        public static string lblId {
            get {
                return ResourceManager.GetString("lblId", resourceCulture);
            }
        }
        
        public static string msgExportAccessibleUserList {
            get {
                return ResourceManager.GetString("msgExportAccessibleUserList", resourceCulture);
            }
        }
        
        public static string lblExportAccessibleUser {
            get {
                return ResourceManager.GetString("lblExportAccessibleUser", resourceCulture);
            }
        }
        
        public static string lblIndex {
            get {
                return ResourceManager.GetString("lblIndex", resourceCulture);
            }
        }
        
        public static string lblMpr {
            get {
                return ResourceManager.GetString("lblMpr", resourceCulture);
            }
        }
        
        public static string lblRID {
            get {
                return ResourceManager.GetString("lblRID", resourceCulture);
            }
        }
        
        public static string msgFirmwareUpdate {
            get {
                return ResourceManager.GetString("msgFirmwareUpdate", resourceCulture);
            }
        }
        
        public static string lblFromDbIdNumber {
            get {
                return ResourceManager.GetString("lblFromDbIdNumber", resourceCulture);
            }
        }
        
        public static string dsClosedAndLock {
            get {
                return ResourceManager.GetString("dsClosedAndLock", resourceCulture);
            }
        }
        
        public static string dsClosedAndUnlocked {
            get {
                return ResourceManager.GetString("dsClosedAndUnlocked", resourceCulture);
            }
        }
        
        public static string dsEmergencyClosed {
            get {
                return ResourceManager.GetString("dsEmergencyClosed", resourceCulture);
            }
        }
        
        public static string dsEmergencyOpened {
            get {
                return ResourceManager.GetString("dsEmergencyOpened", resourceCulture);
            }
        }
        
        public static string dsForceOpened {
            get {
                return ResourceManager.GetString("dsForceOpened", resourceCulture);
            }
        }
        
        public static string dsOpened {
            get {
                return ResourceManager.GetString("dsOpened", resourceCulture);
            }
        }
        
        public static string dsPassageOpened {
            get {
                return ResourceManager.GetString("dsPassageOpened", resourceCulture);
            }
        }
        
        public static string lblCommand {
            get {
                return ResourceManager.GetString("lblCommand", resourceCulture);
            }
        }
        
        public static string lblOpenPeriod {
            get {
                return ResourceManager.GetString("lblOpenPeriod", resourceCulture);
            }
        }
        
        public static string lblOpenUntilTime {
            get {
                return ResourceManager.GetString("lblOpenUntilTime", resourceCulture);
            }
        }
        
        public static string lblReset {
            get {
                return ResourceManager.GetString("lblReset", resourceCulture);
            }
        }
        
        public static string lblForceOpen {
            get {
                return ResourceManager.GetString("lblForceOpen", resourceCulture);
            }
        }
        
        public static string lblForceClose {
            get {
                return ResourceManager.GetString("lblForceClose", resourceCulture);
            }
        }
        
        public static string lblRelease {
            get {
                return ResourceManager.GetString("lblRelease", resourceCulture);
            }
        }
        
        public static string lblDeviceCount {
            get {
                return ResourceManager.GetString("lblDeviceCount", resourceCulture);
            }
        }
        
        public static string lblBackupPeriod {
            get {
                return ResourceManager.GetString("lblBackupPeriod", resourceCulture);
            }
        }
        
        public static string msgTransmitData {
            get {
                return ResourceManager.GetString("msgTransmitData", resourceCulture);
            }
        }
        
        public static string msgDuplicateRole {
            get {
                return ResourceManager.GetString("msgDuplicateRole", resourceCulture);
            }
        }
        
        public static string lblDesktopApp {
            get {
                return ResourceManager.GetString("lblDesktopApp", resourceCulture);
            }
        }
        
        public static string dsUnknown {
            get {
                return ResourceManager.GetString("dsUnknown", resourceCulture);
            }
        }
        
        public static string dsLock {
            get {
                return ResourceManager.GetString("dsLock", resourceCulture);
            }
        }
        
        public static string dsUnlock {
            get {
                return ResourceManager.GetString("dsUnlock", resourceCulture);
            }
        }
        
        public static string lblITouchPopX {
            get {
                return ResourceManager.GetString("lblITouchPopX", resourceCulture);
            }
        }
        
        public static string lblModule {
            get {
                return ResourceManager.GetString("lblModule", resourceCulture);
            }
        }
        
        public static string lblLibrary {
            get {
                return ResourceManager.GetString("lblLibrary", resourceCulture);
            }
        }
        
        public static string NotificationDevice {
            get {
                return ResourceManager.GetString("NotificationDevice", resourceCulture);
            }
        }
        
        public static string verifyCard {
            get {
                return ResourceManager.GetString("verifyCard", resourceCulture);
            }
        }
        
        public static string verifyQR {
            get {
                return ResourceManager.GetString("verifyQR", resourceCulture);
            }
        }
        
        public static string verifyFace {
            get {
                return ResourceManager.GetString("verifyFace", resourceCulture);
            }
        }
        
        public static string verifyPassCode {
            get {
                return ResourceManager.GetString("verifyPassCode", resourceCulture);
            }
        }
        
        public static string verifyCardOrQR {
            get {
                return ResourceManager.GetString("verifyCardOrQR", resourceCulture);
            }
        }
        
        public static string VerifyCardOrPassCode {
            get {
                return ResourceManager.GetString("VerifyCardOrPassCode", resourceCulture);
            }
        }
        
        public static string verifyCardAndQR {
            get {
                return ResourceManager.GetString("verifyCardAndQR", resourceCulture);
            }
        }
        
        public static string verifyCardAndPassCode {
            get {
                return ResourceManager.GetString("verifyCardAndPassCode", resourceCulture);
            }
        }
        
        public static string msgCannotUseVerifyMode {
            get {
                return ResourceManager.GetString("msgCannotUseVerifyMode", resourceCulture);
            }
        }
        
        public static string lblDQMini {
            get {
                return ResourceManager.GetString("lblDQMini", resourceCulture);
            }
        }
        
        public static string NewDevice {
            get {
                return ResourceManager.GetString("NewDevice", resourceCulture);
            }
        }
        
        public static string ReplaceDevice {
            get {
                return ResourceManager.GetString("ReplaceDevice", resourceCulture);
            }
        }
        
        public static string RelocatedDevice {
            get {
                return ResourceManager.GetString("RelocatedDevice", resourceCulture);
            }
        }
        
        public static string lblCreateTimeOnlineDevice {
            get {
                return ResourceManager.GetString("lblCreateTimeOnlineDevice", resourceCulture);
            }
        }
        
        public static string lblUpTimeOnlineDevice {
            get {
                return ResourceManager.GetString("lblUpTimeOnlineDevice", resourceCulture);
            }
        }
        
        public static string lblCreatedOn {
            get {
                return ResourceManager.GetString("lblCreatedOn", resourceCulture);
            }
        }
        
        public static string lblDQMiniPlus {
            get {
                return ResourceManager.GetString("lblDQMiniPlus", resourceCulture);
            }
        }
        
        public static string lblIt100 {
            get {
                return ResourceManager.GetString("lblIt100", resourceCulture);
            }
        }
        
        public static string lblNexpaLPR {
            get {
                return ResourceManager.GetString("lblNexpaLPR", resourceCulture);
            }
        }
        
        public static string verifyIris {
            get {
                return ResourceManager.GetString("verifyIris", resourceCulture);
            }
        }
        
        public static string verifyFaceOrIris {
            get {
                return ResourceManager.GetString("verifyFaceOrIris", resourceCulture);
            }
        }
        
        public static string verifyFaceAndIris {
            get {
                return ResourceManager.GetString("verifyFaceAndIris", resourceCulture);
            }
        }
        
        public static string VerifyCardOrQROrPassCode {
            get {
                return ResourceManager.GetString("VerifyCardOrQROrPassCode", resourceCulture);
            }
        }
        
        public static string verifyCardOrFaceOrIris {
            get {
                return ResourceManager.GetString("verifyCardOrFaceOrIris", resourceCulture);
            }
        }
        
        public static string lblIt100Registration {
            get {
                return ResourceManager.GetString("lblIt100Registration", resourceCulture);
            }
        }
        
        public static string lblPersonalVehicle {
            get {
                return ResourceManager.GetString("lblPersonalVehicle", resourceCulture);
            }
        }
        
        public static string lblUnitVehicle {
            get {
                return ResourceManager.GetString("lblUnitVehicle", resourceCulture);
            }
        }
        
        public static string lblNormalVehicle {
            get {
                return ResourceManager.GetString("lblNormalVehicle", resourceCulture);
            }
        }
        
        public static string lblRFIDVehicle {
            get {
                return ResourceManager.GetString("lblRFIDVehicle", resourceCulture);
            }
        }
        
        public static string lblVehicleAllow {
            get {
                return ResourceManager.GetString("lblVehicleAllow", resourceCulture);
            }
        }
        
        public static string lblVehicleDisallow {
            get {
                return ResourceManager.GetString("lblVehicleDisallow", resourceCulture);
            }
        }
        
        public static string lblControllerDevice {
            get {
                return ResourceManager.GetString("lblControllerDevice", resourceCulture);
            }
        }
        
        public static string lblNexpaLMS {
            get {
                return ResourceManager.GetString("lblNexpaLMS", resourceCulture);
            }
        }
        
        public static string lblRule2Vehicle {
            get {
                return ResourceManager.GetString("lblRule2Vehicle", resourceCulture);
            }
        }
        
        public static string lblRule5Vehicle {
            get {
                return ResourceManager.GetString("lblRule5Vehicle", resourceCulture);
            }
        }
        
        public static string lblExceptionVehicle {
            get {
                return ResourceManager.GetString("lblExceptionVehicle", resourceCulture);
            }
        }
        
        public static string msgDeviceNotWorking {
            get {
                return ResourceManager.GetString("msgDeviceNotWorking", resourceCulture);
            }
        }
        
        public static string msgCameraNotRecognizeFace {
            get {
                return ResourceManager.GetString("msgCameraNotRecognizeFace", resourceCulture);
            }
        }
        
        public static string lblAlarmStateOff {
            get {
                return ResourceManager.GetString("lblAlarmStateOff", resourceCulture);
            }
        }
        
        public static string lblAlarmStateOn {
            get {
                return ResourceManager.GetString("lblAlarmStateOn", resourceCulture);
            }
        }
        
        public static string lblXStation2 {
            get {
                return ResourceManager.GetString("lblXStation2", resourceCulture);
            }
        }
        
        public static string lblFV6000 {
            get {
                return ResourceManager.GetString("lblFV6000", resourceCulture);
            }
        }
        
        public static string lblViolationVehicle {
            get {
                return ResourceManager.GetString("lblViolationVehicle", resourceCulture);
            }
        }
        
        public static string lblKorecenServer {
            get {
                return ResourceManager.GetString("lblKorecenServer", resourceCulture);
            }
        }
        
        public static string lblBusReader {
            get {
                return ResourceManager.GetString("lblBusReader", resourceCulture);
            }
        }
        
        public static string lblPM85 {
            get {
                return ResourceManager.GetString("lblPM85", resourceCulture);
            }
        }
        
        public static string lblTarFile {
            get {
                return ResourceManager.GetString("lblTarFile", resourceCulture);
            }
        }
        
        public static string msgMaximumAddDevice {
            get {
                return ResourceManager.GetString("msgMaximumAddDevice", resourceCulture);
            }
        }
        
        public static string lblFireDetector {
            get {
                return ResourceManager.GetString("lblFireDetector", resourceCulture);
            }
        }
        
        public static string lblITouch30A {
            get {
                return ResourceManager.GetString("lblITouch30A", resourceCulture);
            }
        }
        
        public static string lblDP636X {
            get {
                return ResourceManager.GetString("lblDP636X", resourceCulture);
            }
        }
        
        public static string msgForcedOpenSuccess {
            get {
                return ResourceManager.GetString("msgForcedOpenSuccess", resourceCulture);
            }
        }
        
        public static string msgForcedCloseSuccess {
            get {
                return ResourceManager.GetString("msgForcedCloseSuccess", resourceCulture);
            }
        }
        
        public static string msgForcedReleaseSuccess {
            get {
                return ResourceManager.GetString("msgForcedReleaseSuccess", resourceCulture);
            }
        }
        
        public static string msgOpenDoorTimePeriod {
            get {
                return ResourceManager.GetString("msgOpenDoorTimePeriod", resourceCulture);
            }
        }
        
        public static string msgOpenDoorUtilTime {
            get {
                return ResourceManager.GetString("msgOpenDoorUtilTime", resourceCulture);
            }
        }
        
        public static string lblDQCube {
            get {
                return ResourceManager.GetString("lblDQCube", resourceCulture);
            }
        }
        
        public static string lblDF970 {
            get {
                return ResourceManager.GetString("lblDF970", resourceCulture);
            }
        }
        
        public static string dsFireDetected {
            get {
                return ResourceManager.GetString("dsFireDetected", resourceCulture);
            }
        }
        
        public static string dsFireNoDetected {
            get {
                return ResourceManager.GetString("dsFireNoDetected", resourceCulture);
            }
        }
        
        public static string dsNoMealTime {
            get {
                return ResourceManager.GetString("dsNoMealTime", resourceCulture);
            }
        }
        
        public static string dsInactive {
            get {
                return ResourceManager.GetString("dsInactive", resourceCulture);
            }
        }
        
        public static string dsNeedSetting {
            get {
                return ResourceManager.GetString("dsNeedSetting", resourceCulture);
            }
        }
        
        public static string dsInvalid {
            get {
                return ResourceManager.GetString("dsInvalid", resourceCulture);
            }
        }
        
        public static string lblBiostation2 {
            get {
                return ResourceManager.GetString("lblBiostation2", resourceCulture);
            }
        }
        
        public static string verifyFingerprintOnly {
            get {
                return ResourceManager.GetString("verifyFingerprintOnly", resourceCulture);
            }
        }
        
        public static string verifyCardOrFingerprint {
            get {
                return ResourceManager.GetString("verifyCardOrFingerprint", resourceCulture);
            }
        }
        
        public static string lblIcu300NX {
            get {
                return ResourceManager.GetString("lblIcu300NX", resourceCulture);
            }
        }
        
        public static string lblBioStationMode {
            get {
                return ResourceManager.GetString("lblBioStationMode", resourceCulture);
            }
        }
        
        public static string lblMaster {
            get {
                return ResourceManager.GetString("lblMaster", resourceCulture);
            }
        }
        
        public static string lblSlave {
            get {
                return ResourceManager.GetString("lblSlave", resourceCulture);
            }
        }
        
        public static string lblStandalone {
            get {
                return ResourceManager.GetString("lblStandalone", resourceCulture);
            }
        }
        
        public static string verifyCardAndFingerprint {
            get {
                return ResourceManager.GetString("verifyCardAndFingerprint", resourceCulture);
            }
        }
        
        public static string verifyFingerprintAndPassCode {
            get {
                return ResourceManager.GetString("verifyFingerprintAndPassCode", resourceCulture);
            }
        }
        
        public static string lblBiostation3 {
            get {
                return ResourceManager.GetString("lblBiostation3", resourceCulture);
            }
        }
        
        public static string verifyCardAndFace {
            get {
                return ResourceManager.GetString("verifyCardAndFace", resourceCulture);
            }
        }
        
        public static string verifyFaceAndPassCode {
            get {
                return ResourceManager.GetString("verifyFaceAndPassCode", resourceCulture);
            }
        }
        
        public static string verifyCardAndFaceAndPassCode {
            get {
                return ResourceManager.GetString("verifyCardAndFaceAndPassCode", resourceCulture);
            }
        }
        
        public static string lblEbknReader {
            get {
                return ResourceManager.GetString("lblEbknReader", resourceCulture);
            }
        }
        
        public static string verifyFaceOrFingerPrintOrPassCode {
            get {
                return ResourceManager.GetString("verifyFaceOrFingerPrintOrPassCode", resourceCulture);
            }
        }
        
        public static string verifyFingerprintAndFace {
            get {
                return ResourceManager.GetString("verifyFingerprintAndFace", resourceCulture);
            }
        }
        
        public static string verifyCardOrQrOrFingerprintOrFaceId {
            get {
                return ResourceManager.GetString("verifyCardOrQrOrFingerprintOrFaceId", resourceCulture);
            }
        }
        
        public static string lblBA8300 {
            get {
                return ResourceManager.GetString("lblBA8300", resourceCulture);
            }
        }
        
        public static string msgDeviceNotReady {
            get {
                return ResourceManager.GetString("msgDeviceNotReady", resourceCulture);
            }
        }
        
        public static string lblIcu400 {
            get {
                return ResourceManager.GetString("lblIcu400", resourceCulture);
            }
        }
        
        public static string lblDeviceId {
            get {
                return ResourceManager.GetString("lblDeviceId", resourceCulture);
            }
        }
        
        public static string lblDoorStatus {
            get {
                return ResourceManager.GetString("lblDoorStatus", resourceCulture);
            }
        }
        
        public static string lblProgress {
            get {
                return ResourceManager.GetString("lblProgress", resourceCulture);
            }
        }
        
        public static string msgRejectVideoCall {
            get {
                return ResourceManager.GetString("msgRejectVideoCall", resourceCulture);
            }
        }
        
        public static string lblRA08 {
            get {
                return ResourceManager.GetString("lblRA08", resourceCulture);
            }
        }
        
        public static string lblDQ8500 {
            get {
                return ResourceManager.GetString("lblDQ8500", resourceCulture);
            }
        }
        
        public static string lblActiveFaceLicense {
            get {
                return ResourceManager.GetString("lblActiveFaceLicense", resourceCulture);
            }
        }
        
        public static string lblSerial {
            get {
                return ResourceManager.GetString("lblSerial", resourceCulture);
            }
        }
        
        public static string lblKey {
            get {
                return ResourceManager.GetString("lblKey", resourceCulture);
            }
        }
        
        public static string lblITouchPop2AlblITouchPop2A {
            get {
                return ResourceManager.GetString("lblITouchPop2AlblITouchPop2A", resourceCulture);
            }
        }
        
        public static string lblActivationCode {
            get {
                return ResourceManager.GetString("lblActivationCode", resourceCulture);
            }
        }
        
        public static string msgYourRequestSuccess {
            get {
                return ResourceManager.GetString("msgYourRequestSuccess", resourceCulture);
            }
        }
        
        public static string msgNotificationNewFile {
            get {
                return ResourceManager.GetString("msgNotificationNewFile", resourceCulture);
            }
        }
        
        public static string lblAratek {
            get {
                return ResourceManager.GetString("lblAratek", resourceCulture);
            }
        }
        
        public static string lblMaxOpenDuration {
            get {
                return ResourceManager.GetString("lblMaxOpenDuration", resourceCulture);
            }
        }
        
        public static string prgMsgLoadDeviceInfo {
            get {
                return ResourceManager.GetString("prgMsgLoadDeviceInfo", resourceCulture);
            }
        }
        
        public static string prgMsgUpdateTimezone {
            get {
                return ResourceManager.GetString("prgMsgUpdateTimezone", resourceCulture);
            }
        }
        
        public static string prgMsgUpdateHoliday {
            get {
                return ResourceManager.GetString("prgMsgUpdateHoliday", resourceCulture);
            }
        }
        
        public static string prgMsgAddUser {
            get {
                return ResourceManager.GetString("prgMsgAddUser", resourceCulture);
            }
        }
        
        public static string prgMsgUpdateDeviceMessage {
            get {
                return ResourceManager.GetString("prgMsgUpdateDeviceMessage", resourceCulture);
            }
        }
        
        public static string prgMsgUpdateDeviceFirmware {
            get {
                return ResourceManager.GetString("prgMsgUpdateDeviceFirmware", resourceCulture);
            }
        }
        
        public static string prgMsgSending {
            get {
                return ResourceManager.GetString("prgMsgSending", resourceCulture);
            }
        }
        
        public static string lblDQ200 {
            get {
                return ResourceManager.GetString("lblDQ200", resourceCulture);
            }
        }
        
        public static string msgDeviceNotResponse {
            get {
                return ResourceManager.GetString("msgDeviceNotResponse", resourceCulture);
            }
        }
        
        public static string lblDCCamera {
            get {
                return ResourceManager.GetString("lblDCCamera", resourceCulture);
            }
        }
        
        public static string verifyVehicle {
            get {
                return ResourceManager.GetString("verifyVehicle", resourceCulture);
            }
        }
        
        public static string verifyVehicleAndFace {
            get {
                return ResourceManager.GetString("verifyVehicleAndFace", resourceCulture);
            }
        }
        
        public static string verifyPlateNumberAndVNID {
            get {
                return ResourceManager.GetString("verifyPlateNumberAndVNID", resourceCulture);
            }
        }
        
        public static string verifyVNID {
            get {
                return ResourceManager.GetString("verifyVNID", resourceCulture);
            }
        }
        
        public static string lblTBVision {
            get {
                return ResourceManager.GetString("lblTBVision", resourceCulture);
            }
        }
        
        public static string lblIcu500 {
            get {
                return ResourceManager.GetString("lblIcu500", resourceCulture);
            }
        }
        
        public static string lblMotoBike {
            get {
                return ResourceManager.GetString("lblMotoBike", resourceCulture);
            }
        }
        
        public static string lblCar {
            get {
                return ResourceManager.GetString("lblCar", resourceCulture);
            }
        }
        
        public static string lblT2Face {
            get {
                return ResourceManager.GetString("lblT2Face", resourceCulture);
            }
        }
        
        public static string msgDoorNameInUse {
            get {
                return ResourceManager.GetString("msgDoorNameInUse", resourceCulture);
            }
        }
    }
}
