//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HolidayResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HolidayResource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.HolidayResource", typeof(HolidayResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add new holiday과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblAddNew {
            get {
                return ResourceManager.GetString("lblAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiple delele holiday과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblDeleteMultipleHoliday {
            get {
                return ResourceManager.GetString("lblDeleteMultipleHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblEndDate {
            get {
                return ResourceManager.GetString("lblEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Holiday과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblHoliday {
            get {
                return ResourceManager.GetString("lblHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Holiday list과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblHolidayList {
            get {
                return ResourceManager.GetString("lblHolidayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Holiday name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblHolidayName {
            get {
                return ResourceManager.GetString("lblHolidayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Holiday type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblHolidayType {
            get {
                return ResourceManager.GetString("lblHolidayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Holiday type 1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblHolidayType1 {
            get {
                return ResourceManager.GetString("lblHolidayType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Holiday type 2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblHolidayType2 {
            get {
                return ResourceManager.GetString("lblHolidayType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Holiday type 3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblHolidayType3 {
            get {
                return ResourceManager.GetString("lblHolidayType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recurring과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblRecurring {
            get {
                return ResourceManager.GetString("lblRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remark과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblRemark {
            get {
                return ResourceManager.GetString("lblRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a holiday type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblSelectHolidayType {
            get {
                return ResourceManager.GetString("lblSelectHolidayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblStartDate {
            get {
                return ResourceManager.GetString("lblStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update holiday {0} information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string lblUpdateHoliday {
            get {
                return ResourceManager.GetString("lblUpdateHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can not create any more holiday. The system limit holiday in {0} days.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgLimitHoliday {
            get {
                return ResourceManager.GetString("msgLimitHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start date or end date is overlapped to other holidays.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msgOverlapDurationTime {
            get {
                return ResourceManager.GetString("msgOverlapDurationTime", resourceCulture);
            }
        }
    }
}
