//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MonitoringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MonitoringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.MonitoringResource", typeof(MonitoringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string lblCompany {
            get {
                return ResourceManager.GetString("lblCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door Name.
        /// </summary>
        public static string lblDoorName {
            get {
                return ResourceManager.GetString("lblDoorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastest Sync.
        /// </summary>
        public static string lblLastestSync {
            get {
                return ResourceManager.GetString("lblLastestSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string lblMonitoring {
            get {
                return ResourceManager.GetString("lblMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Time.
        /// </summary>
        public static string lblSyncTime {
            get {
                return ResourceManager.GetString("lblSyncTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync type.
        /// </summary>
        public static string lblSyncType {
            get {
                return ResourceManager.GetString("lblSyncType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Way to sync.
        /// </summary>
        public static string lblWayToSync {
            get {
                return ResourceManager.GetString("lblWayToSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template 1.
        /// </summary>
        public static string typeMonitoring1 {
            get {
                return ResourceManager.GetString("typeMonitoring1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template 2.
        /// </summary>
        public static string typeMonitoring2 {
            get {
                return ResourceManager.GetString("typeMonitoring2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template 3.
        /// </summary>
        public static string typeMonitoring3 {
            get {
                return ResourceManager.GetString("typeMonitoring3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template 4.
        /// </summary>
        public static string typeMonitoring4 {
            get {
                return ResourceManager.GetString("typeMonitoring4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template 5.
        /// </summary>
        public static string typeMonitoring5 {
            get {
                return ResourceManager.GetString("typeMonitoring5", resourceCulture);
            }
        }
        
        public static string typeMonitoring6 {
            get {
                return ResourceManager.GetString("typeMonitoring6", resourceCulture);
            }
        }
        
        public static string typeMonitoring7 {
            get {
                return ResourceManager.GetString("typeMonitoring7", resourceCulture);
            }
        }
    }
}
