//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeMasterProCloud.Common.Resources {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PermissionResource
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PermissionResource()
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.Equals(null, resourceMan))
                {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DeMasterProCloud.Common.Resources.PermissionResource", typeof(PermissionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string ViewAccessGroup
        {
            get
            {
                return ResourceManager.GetString("ViewAccessGroup", resourceCulture);
            }
        }

        public static string AddAccessGroup
        {
            get
            {
                return ResourceManager.GetString("AddAccessGroup", resourceCulture);
            }
        }

        public static string EditAccessGroup
        {
            get
            {
                return ResourceManager.GetString("EditAccessGroup", resourceCulture);
            }
        }

        public static string DeleteAccessGroup
        {
            get
            {
                return ResourceManager.GetString("DeleteAccessGroup", resourceCulture);
            }
        }

        public static string AssignDoorAccessGroup
        {
            get
            {
                return ResourceManager.GetString("AssignDoorAccessGroup", resourceCulture);
            }
        }

        public static string DescriptionViewAccessGroup
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewAccessGroup", resourceCulture);
            }
        }

        public static string DescriptionAddAccessGroup
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddAccessGroup", resourceCulture);
            }
        }

        public static string DescriptionEditAccessGroup
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditAccessGroup", resourceCulture);
            }
        }

        public static string DescriptionDeleteAccessGroup
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteAccessGroup", resourceCulture);
            }
        }

        public static string DescriptionAssignDoorAccessGroup
        {
            get
            {
                return ResourceManager.GetString("DescriptionAssignDoorAccessGroup", resourceCulture);
            }
        }

        public static string AccessGroup
        {
            get
            {
                return ResourceManager.GetString("AccessGroup", resourceCulture);
            }
        }

        public static string ViewAccount
        {
            get
            {
                return ResourceManager.GetString("ViewAccount", resourceCulture);
            }
        }

        public static string AddAccount
        {
            get
            {
                return ResourceManager.GetString("AddAccount", resourceCulture);
            }
        }

        public static string EditAccount
        {
            get
            {
                return ResourceManager.GetString("EditAccount", resourceCulture);
            }
        }

        public static string DeleteAccount
        {
            get
            {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }

        public static string DescriptionViewAccount
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewAccount", resourceCulture);
            }
        }

        public static string DescriptionAddAccount
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddAccount", resourceCulture);
            }
        }

        public static string DescriptionEditAccount
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditAccount", resourceCulture);
            }
        }

        public static string DescriptionDeleteAccount
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteAccount", resourceCulture);
            }
        }

        public static string Account
        {
            get
            {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }

        public static string ViewAttendance
        {
            get
            {
                return ResourceManager.GetString("ViewAttendance", resourceCulture);
            }
        }

        public static string ExportAttendance
        {
            get
            {
                return ResourceManager.GetString("ExportAttendance", resourceCulture);
            }
        }

        public static string DescriptionViewAttendance
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewAttendance", resourceCulture);
            }
        }

        public static string DescriptionExportAttendance
        {
            get
            {
                return ResourceManager.GetString("DescriptionExportAttendance", resourceCulture);
            }
        }

        public static string TimeAttendanceReport
        {
            get
            {
                return ResourceManager.GetString("TimeAttendanceReport", resourceCulture);
            }
        }

        public static string ViewBuilding
        {
            get
            {
                return ResourceManager.GetString("ViewBuilding", resourceCulture);
            }
        }

        public static string AddBuilding
        {
            get
            {
                return ResourceManager.GetString("AddBuilding", resourceCulture);
            }
        }

        public static string EditBuilding
        {
            get
            {
                return ResourceManager.GetString("EditBuilding", resourceCulture);
            }
        }

        public static string DeleteBuilding
        {
            get
            {
                return ResourceManager.GetString("DeleteBuilding", resourceCulture);
            }
        }

        public static string AssignDoorBuilding
        {
            get
            {
                return ResourceManager.GetString("AssignDoorBuilding", resourceCulture);
            }
        }

        public static string DescriptionAssignDoorBuilding
        {
            get
            {
                return ResourceManager.GetString("DescriptionAssignDoorBuilding", resourceCulture);
            }
        }

        public static string DescriptionViewBuilding
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewBuilding", resourceCulture);
            }
        }

        public static string DescriptionAddBuilding
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddBuilding", resourceCulture);
            }
        }

        public static string DescriptionEditBuilding
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditBuilding", resourceCulture);
            }
        }

        public static string DescriptionDeleteBuilding
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteBuilding", resourceCulture);
            }
        }

        public static string Building
        {
            get
            {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }

        public static string ViewCategory
        {
            get
            {
                return ResourceManager.GetString("ViewCategory", resourceCulture);
            }
        }

        public static string AddCategory
        {
            get
            {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }

        public static string EditCategory
        {
            get
            {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }

        public static string DeleteCategory
        {
            get
            {
                return ResourceManager.GetString("DeleteCategory", resourceCulture);
            }
        }

        public static string DescriptionViewCategory
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewCategory", resourceCulture);
            }
        }

        public static string DescriptionAddCategory
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddCategory", resourceCulture);
            }
        }

        public static string DescriptionEditCategory
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditCategory", resourceCulture);
            }
        }

        public static string DescriptionDeleteCategory
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteCategory", resourceCulture);
            }
        }

        public static string Category
        {
            get
            {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }

        public static string ViewDepartment
        {
            get
            {
                return ResourceManager.GetString("ViewDepartment", resourceCulture);
            }
        }

        public static string AddDepartment
        {
            get
            {
                return ResourceManager.GetString("AddDepartment", resourceCulture);
            }
        }

        public static string EditDepartment
        {
            get
            {
                return ResourceManager.GetString("EditDepartment", resourceCulture);
            }
        }

        public static string DeleteDepartment
        {
            get
            {
                return ResourceManager.GetString("DeleteDepartment", resourceCulture);
            }
        }

        public static string ExportDepartment
        {
            get
            {
                return ResourceManager.GetString("ExportDepartment", resourceCulture);
            }
        }

        public static string DescriptionViewDepartment
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewDepartment", resourceCulture);
            }
        }

        public static string DescriptionAddDepartment
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddDepartment", resourceCulture);
            }
        }

        public static string DescriptionEditDepartment
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditDepartment", resourceCulture);
            }
        }

        public static string DescriptionDeleteDepartment
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteDepartment", resourceCulture);
            }
        }

        public static string DescriptionExportDepartment
        {
            get
            {
                return ResourceManager.GetString("DescriptionExportDepartment", resourceCulture);
            }
        }

        public static string Department
        {
            get
            {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }

        public static string ViewDevice
        {
            get
            {
                return ResourceManager.GetString("ViewDevice", resourceCulture);
            }
        }

        public static string EditDevice
        {
            get
            {
                return ResourceManager.GetString("EditDevice", resourceCulture);
            }
        }

        public static string SendInstructionDevice
        {
            get
            {
                return ResourceManager.GetString("SendInstructionDevice", resourceCulture);
            }
        }

        public static string ViewHistoryDevice
        {
            get
            {
                return ResourceManager.GetString("ViewHistoryDevice", resourceCulture);
            }
        }

        public static string ReinstallDevice
        {
            get
            {
                return ResourceManager.GetString("ReinstallDevice", resourceCulture);
            }
        }

        public static string RebootDevice
        {
            get
            {
                return ResourceManager.GetString("RebootDevice", resourceCulture);
            }
        }

        public static string CopyDevice
        {
            get
            {
                return ResourceManager.GetString("CopyDevice", resourceCulture);
            }
        }

        public static string DescriptionViewDevice
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewDevice", resourceCulture);
            }
        }

        public static string DescriptionEditDevice
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditDevice", resourceCulture);
            }
        }

        public static string DescriptionSendInstructionDevice
        {
            get
            {
                return ResourceManager.GetString("DescriptionSendInstructionDevice", resourceCulture);
            }
        }

        public static string DescriptionViewHistoryDevice
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewHistoryDevice", resourceCulture);
            }
        }

        public static string DescriptionReinstallDevice
        {
            get
            {
                return ResourceManager.GetString("DescriptionReinstallDevice", resourceCulture);
            }
        }

        public static string DescriptionRebootDevice
        {
            get
            {
                return ResourceManager.GetString("DescriptionRebootDevice", resourceCulture);
            }
        }

        public static string DescriptionCopyDevice
        {
            get
            {
                return ResourceManager.GetString("DescriptionCopyDevice", resourceCulture);
            }
        }

        public static string Device
        {
            get
            {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }

        public static string ViewDeviceMessage
        {
            get
            {
                return ResourceManager.GetString("ViewDeviceMessage", resourceCulture);
            }
        }

        public static string EditDeviceMessage
        {
            get
            {
                return ResourceManager.GetString("EditDeviceMessage", resourceCulture);
            }
        }

        public static string DescriptionViewDeviceMessage
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewDeviceMessage", resourceCulture);
            }
        }

        public static string DescriptionEditDeviceMessage
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditDeviceMessage", resourceCulture);
            }
        }

        public static string DeviceMessage
        {
            get
            {
                return ResourceManager.GetString("DeviceMessage", resourceCulture);
            }
        }

        public static string ViewEventLog
        {
            get
            {
                return ResourceManager.GetString("ViewEventLog", resourceCulture);
            }
        }

        public static string ExportEventLog
        {
            get
            {
                return ResourceManager.GetString("ExportEventLog", resourceCulture);
            }
        }

        public static string DescriptionViewEventLog
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewEventLog", resourceCulture);
            }
        }

        public static string DescriptionExportEventLog
        {
            get
            {
                return ResourceManager.GetString("DescriptionExportEventLog", resourceCulture);
            }
        }

        public static string EventLog
        {
            get
            {
                return ResourceManager.GetString("EventLog", resourceCulture);
            }
        }

        public static string ViewHoliday
        {
            get
            {
                return ResourceManager.GetString("ViewHoliday", resourceCulture);
            }
        }

        public static string AddHoliday
        {
            get
            {
                return ResourceManager.GetString("AddHoliday", resourceCulture);
            }
        }

        public static string EditHoliday
        {
            get
            {
                return ResourceManager.GetString("EditHoliday", resourceCulture);
            }
        }

        public static string DeleteHoliday
        {
            get
            {
                return ResourceManager.GetString("DeleteHoliday", resourceCulture);
            }
        }

        public static string DescriptionViewHoliday
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewHoliday", resourceCulture);
            }
        }

        public static string DescriptionAddHoliday
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddHoliday", resourceCulture);
            }
        }

        public static string DescriptionEditHoliday
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditHoliday", resourceCulture);
            }
        }

        public static string DescriptionDeleteHoliday
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteHoliday", resourceCulture);
            }
        }

        public static string Holiday
        {
            get
            {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }

        public static string ViewSetting
        {
            get
            {
                return ResourceManager.GetString("ViewSetting", resourceCulture);
            }
        }

        public static string EditSetting
        {
            get
            {
                return ResourceManager.GetString("EditSetting", resourceCulture);
            }
        }

        public static string DescriptionViewSetting
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewSetting", resourceCulture);
            }
        }

        public static string DescriptionEditSetting
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditSetting", resourceCulture);
            }
        }

        public static string Setting
        {
            get
            {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }

        public static string ViewSystemLog
        {
            get
            {
                return ResourceManager.GetString("ViewSystemLog", resourceCulture);
            }
        }

        public static string ExportSystemLog
        {
            get
            {
                return ResourceManager.GetString("ExportSystemLog", resourceCulture);
            }
        }

        public static string DescriptionViewSystemLog
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewSystemLog", resourceCulture);
            }
        }

        public static string DescriptionExportSystemLog
        {
            get
            {
                return ResourceManager.GetString("DescriptionExportSystemLog", resourceCulture);
            }
        }

        public static string SystemLog
        {
            get
            {
                return ResourceManager.GetString("SystemLog", resourceCulture);
            }
        }

        public static string ViewTimezone
        {
            get
            {
                return ResourceManager.GetString("ViewTimezone", resourceCulture);
            }
        }

        public static string AddTimezone
        {
            get
            {
                return ResourceManager.GetString("AddTimezone", resourceCulture);
            }
        }

        public static string EditTimezone
        {
            get
            {
                return ResourceManager.GetString("EditTimezone", resourceCulture);
            }
        }

        public static string DeleteTimezone
        {
            get
            {
                return ResourceManager.GetString("DeleteTimezone", resourceCulture);
            }
        }

        public static string DescriptionViewTimezone
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewTimezone", resourceCulture);
            }
        }

        public static string DescriptionAddTimezone
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddTimezone", resourceCulture);
            }
        }

        public static string DescriptionEditTimezone
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditTimezone", resourceCulture);
            }
        }

        public static string DescriptionDeleteTimezone
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteTimezone", resourceCulture);
            }
        }

        public static string Timezone
        {
            get
            {
                return ResourceManager.GetString("Timezone", resourceCulture);
            }
        }

        public static string ViewUser
        {
            get
            {
                return ResourceManager.GetString("ViewUser", resourceCulture);
            }
        }

        public static string AddUser
        {
            get
            {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }

        public static string EditUser
        {
            get
            {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }

        public static string DeleteUser
        {
            get
            {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }

        public static string DescriptionViewUser
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewUser", resourceCulture);
            }
        }

        public static string DescriptionAddUser
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddUser", resourceCulture);
            }
        }

        public static string DescriptionEditUser
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditUser", resourceCulture);
            }
        }

        public static string DescriptionDeleteUser
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteUser", resourceCulture);
            }
        }

        public static string User
        {
            get
            {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }

        public static string ViewWorkingTime
        {
            get
            {
                return ResourceManager.GetString("ViewWorkingTime", resourceCulture);
            }
        }

        public static string AddWorkingTime
        {
            get
            {
                return ResourceManager.GetString("AddWorkingTime", resourceCulture);
            }
        }

        public static string EditWorkingTime
        {
            get
            {
                return ResourceManager.GetString("EditWorkingTime", resourceCulture);
            }
        }

        public static string DeleteWorkingTime
        {
            get
            {
                return ResourceManager.GetString("DeleteWorkingTime", resourceCulture);
            }
        }

        public static string DescriptionViewWorkingTime
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewWorkingTime", resourceCulture);
            }
        }

        public static string DescriptionAddWorkingTime
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddWorkingTime", resourceCulture);
            }
        }

        public static string DescriptionEditWorkingTime
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditWorkingTime", resourceCulture);
            }
        }

        public static string DescriptionDeleteWorkingTime
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteWorkingTime", resourceCulture);
            }
        }

        public static string WorkingTime
        {
            get
            {
                return ResourceManager.GetString("WorkingTime", resourceCulture);
            }
        }

        public static string ViewVisit
        {
            get
            {
                return ResourceManager.GetString("ViewVisit", resourceCulture);
            }
        }

        public static string AddVisit
        {
            get
            {
                return ResourceManager.GetString("AddVisit", resourceCulture);
            }
        }

        public static string EditVisit
        {
            get
            {
                return ResourceManager.GetString("EditVisit", resourceCulture);
            }
        }

        public static string DeleteVisit
        {
            get
            {
                return ResourceManager.GetString("DeleteVisit", resourceCulture);
            }
        }

        public static string ExportVisit
        {
            get
            {
                return ResourceManager.GetString("ExportVisit", resourceCulture);
            }
        }

        public static string ReturnCardVisit
        {
            get
            {
                return ResourceManager.GetString("ReturnCardVisit", resourceCulture);
            }
        }

        public static string ViewHistoryVisit
        {
            get
            {
                return ResourceManager.GetString("ViewHistoryVisit", resourceCulture);
            }
        }

        public static string AssignDoorVisit
        {
            get
            {
                return ResourceManager.GetString("AssignDoorVisit", resourceCulture);
            }
        }

        public static string DescriptionViewVisit
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewVisit", resourceCulture);
            }
        }

        public static string DescriptionAddVisit
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddVisit", resourceCulture);
            }
        }

        public static string DescriptionEditVisit
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditVisit", resourceCulture);
            }
        }

        public static string DescriptionDeleteVisit
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteVisit", resourceCulture);
            }
        }

        public static string DescriptionExportVisit
        {
            get
            {
                return ResourceManager.GetString("DescriptionExportVisit", resourceCulture);
            }
        }

        public static string DescriptionReturnCardVisit
        {
            get
            {
                return ResourceManager.GetString("DescriptionReturnCardVisit", resourceCulture);
            }
        }

        public static string DescriptionViewHistoryVisit
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewHistoryVisit", resourceCulture);
            }
        }

        public static string DescriptionAssignDoorVisit
        {
            get
            {
                return ResourceManager.GetString("DescriptionAssignDoorVisit", resourceCulture);
            }
        }

        public static string VisitManagement
        {
            get
            {
                return ResourceManager.GetString("VisitManagement", resourceCulture);
            }
        }

        public static string ViewUserArmy
        {
            get
            {
                return ResourceManager.GetString("ViewUserArmy", resourceCulture);
            }
        }

        public static string AddUserArmy
        {
            get
            {
                return ResourceManager.GetString("AddUserArmy", resourceCulture);
            }
        }

        public static string EditUserArmy
        {
            get
            {
                return ResourceManager.GetString("EditUserArmy", resourceCulture);
            }
        }

        public static string DeleteUserArmy
        {
            get
            {
                return ResourceManager.GetString("DeleteUserArmy", resourceCulture);
            }
        }

        public static string DescriptionViewUserArmy
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewUserArmy", resourceCulture);
            }
        }

        public static string DescriptionAddUserArmy
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddUserArmy", resourceCulture);
            }
        }

        public static string DescriptionEditUserArmy
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditUserArmy", resourceCulture);
            }
        }

        public static string DescriptionDeleteUserArmy
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteUserArmy", resourceCulture);
            }
        }

        public static string UserArmy
        {
            get
            {
                return ResourceManager.GetString("UserArmy", resourceCulture);
            }
        }

        public static string ViewVisitArmy
        {
            get
            {
                return ResourceManager.GetString("ViewVisitArmy", resourceCulture);
            }
        }

        public static string AddVisitArmy
        {
            get
            {
                return ResourceManager.GetString("AddVisitArmy", resourceCulture);
            }
        }

        public static string EditVisitArmy
        {
            get
            {
                return ResourceManager.GetString("EditVisitArmy", resourceCulture);
            }
        }

        public static string DeleteVisitArmy
        {
            get
            {
                return ResourceManager.GetString("DeleteVisitArmy", resourceCulture);
            }
        }

        public static string DescriptionViewVisitArmy
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewVisitArmy", resourceCulture);
            }
        }

        public static string DescriptionAddVisitArmy
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddVisitArmy", resourceCulture);
            }
        }

        public static string DescriptionEditVisitArmy
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditVisitArmy", resourceCulture);
            }
        }

        public static string DescriptionDeleteVisitArmy
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteVisitArmy", resourceCulture);
            }
        }

        public static string VisitArmyManagement
        {
            get
            {
                return ResourceManager.GetString("VisitArmyManagement", resourceCulture);
            }
        }

        public static string ViewMonitoring
        {
            get
            {
                return ResourceManager.GetString("ViewMonitoring", resourceCulture);
            }
        }

        public static string DescriptionViewMonitoring
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewMonitoring", resourceCulture);
            }
        }

        public static string Monitoring
        {
            get
            {
                return ResourceManager.GetString("Monitoring", resourceCulture);
            }
        }

        public static string ViewDeviceMonitoring
        {
            get
            {
                return ResourceManager.GetString("ViewDeviceMonitoring", resourceCulture);
            }
        }

        public static string DescriptionViewDeviceMonitoring
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewDeviceMonitoring", resourceCulture);
            }
        }

        public static string DeviceMonitoring
        {
            get
            {
                return ResourceManager.GetString("DeviceMonitoring", resourceCulture);
            }
        }

        public static string SendInstructionDeviceMonitoring
        {
            get
            {
                return ResourceManager.GetString("SendInstructionDeviceMonitoring", resourceCulture);
            }
        }

        public static string DescriptionSendInstructionDeviceMonitoring
        {
            get
            {
                return ResourceManager.GetString("DescriptionSendInstructionDeviceMonitoring", resourceCulture);
            }
        }

        public static string ViewUserDepartment
        {
            get
            {
                return ResourceManager.GetString("ViewUserDepartment", resourceCulture);
            }
        }

        public static string DescriptionViewUserDepartment
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewUserDepartment", resourceCulture);
            }
        }

        public static string ExportUser
        {
            get
            {
                return ResourceManager.GetString("ExportUser", resourceCulture);
            }
        }

        public static string DescriptionExportUser
        {
            get
            {
                return ResourceManager.GetString("DescriptionExportUser", resourceCulture);
            }
        }

        public static string SetWorkingTimeUser
        {
            get
            {
                return ResourceManager.GetString("SetWorkingTimeUser", resourceCulture);
            }
        }

        public static string DescriptionSetWorkingTimeUser
        {
            get
            {
                return ResourceManager.GetString("DescriptionSetWorkingTimeUser", resourceCulture);
            }
        }

        public static string ViewDeviceSetting
        {
            get
            {
                return ResourceManager.GetString("ViewDeviceSetting", resourceCulture);
            }
        }

        public static string EditDeviceSetting
        {
            get
            {
                return ResourceManager.GetString("EditDeviceSetting", resourceCulture);
            }
        }

        public static string CopyDeviceSetting
        {
            get
            {
                return ResourceManager.GetString("CopyDeviceSetting", resourceCulture);
            }
        }

        public static string ReinstallDeviceSetting
        {
            get
            {
                return ResourceManager.GetString("ReinstallDeviceSetting", resourceCulture);
            }
        }

        public static string ViewHistoryDeviceSetting
        {
            get
            {
                return ResourceManager.GetString("ViewHistoryDeviceSetting", resourceCulture);
            }
        }

        public static string DescriptionViewDeviceSetting
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewDeviceSetting", resourceCulture);
            }
        }

        public static string DescriptionEditDeviceSetting
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditDeviceSetting", resourceCulture);
            }
        }

        public static string DescriptionCopyDeviceSetting
        {
            get
            {
                return ResourceManager.GetString("DescriptionCopyDeviceSetting", resourceCulture);
            }
        }

        public static string DescriptionReinstallDeviceSetting
        {
            get
            {
                return ResourceManager.GetString("DescriptionReinstallDeviceSetting", resourceCulture);
            }
        }

        public static string DescriptionViewHistoryDeviceSetting
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewHistoryDeviceSetting", resourceCulture);
            }
        }

        public static string DeviceSetting
        {
            get
            {
                return ResourceManager.GetString("DeviceSetting", resourceCulture);
            }
        }

        public static string ViewReport
        {
            get
            {
                return ResourceManager.GetString("ViewReport", resourceCulture);
            }
        }

        public static string ExportReport
        {
            get
            {
                return ResourceManager.GetString("ExportReport", resourceCulture);
            }
        }

        public static string DescriptionViewReport
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewReport", resourceCulture);
            }
        }

        public static string DescriptionExportReport
        {
            get
            {
                return ResourceManager.GetString("DescriptionExportReport", resourceCulture);
            }
        }

        public static string Report
        {
            get
            {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }

        public static string ViewAccessibleDoor
        {
            get
            {
                return ResourceManager.GetString("ViewAccessibleDoor", resourceCulture);
            }
        }

        public static string ExportAccessibleDoor
        {
            get
            {
                return ResourceManager.GetString("ExportAccessibleDoor", resourceCulture);
            }
        }

        public static string DescriptionViewAccessibleDoor
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewAccessibleDoor", resourceCulture);
            }
        }

        public static string DescriptionExportAccessibleDoor
        {
            get
            {
                return ResourceManager.GetString("DescriptionExportAccessibleDoor", resourceCulture);
            }
        }

        public static string AccessibleDoor
        {
            get
            {
                return ResourceManager.GetString("AccessibleDoor", resourceCulture);
            }
        }

        public static string ViewRegisteredUser
        {
            get
            {
                return ResourceManager.GetString("ViewRegisteredUser", resourceCulture);
            }
        }

        public static string ExportRegisteredUser
        {
            get
            {
                return ResourceManager.GetString("ExportRegisteredUser", resourceCulture);
            }
        }

        public static string DescriptionViewRegisteredUser
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewRegisteredUser", resourceCulture);
            }
        }

        public static string DescriptionExportRegisteredUser
        {
            get
            {
                return ResourceManager.GetString("DescriptionExportRegisteredUser", resourceCulture);
            }
        }

        public static string RegisteredUser
        {
            get
            {
                return ResourceManager.GetString("RegisteredUser", resourceCulture);
            }
        }

        public static string EditAttendance
        {
            get
            {
                return ResourceManager.GetString("EditAttendance", resourceCulture);
            }
        }

        public static string ViewHistoryAttendance
        {
            get
            {
                return ResourceManager.GetString("ViewHistoryAttendance", resourceCulture);
            }
        }

        public static string DescriptionEditAttendance
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditAttendance", resourceCulture);
            }
        }

        public static string DescriptionViewHistoryAttendance
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewHistoryAttendance", resourceCulture);
            }
        }

        public static string ApproveVisit
        {
            get
            {
                return ResourceManager.GetString("ApproveVisit", resourceCulture);
            }
        }

        public static string DescriptionApproveVisit
        {
            get
            {
                return ResourceManager.GetString("DescriptionApproveVisit", resourceCulture);
            }
        }

        public static string ViewVisitReport
        {
            get
            {
                return ResourceManager.GetString("ViewVisitReport", resourceCulture);
            }
        }

        public static string ExportVisitReport
        {
            get
            {
                return ResourceManager.GetString("ExportVisitReport", resourceCulture);
            }
        }

        public static string EditVisitSetting
        {
            get
            {
                return ResourceManager.GetString("EditVisitSetting", resourceCulture);
            }
        }

        public static string DescriptionViewVisitReport
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewVisitReport", resourceCulture);
            }
        }

        public static string DescriptionExportVisitReport
        {
            get
            {
                return ResourceManager.GetString("DescriptionExportVisitReport", resourceCulture);
            }
        }

        public static string DescriptionEditVisitSetting
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditVisitSetting", resourceCulture);
            }
        }

        public static string VisitReport
        {
            get
            {
                return ResourceManager.GetString("VisitReport", resourceCulture);
            }
        }

        public static string VisitSetting
        {
            get
            {
                return ResourceManager.GetString("VisitSetting", resourceCulture);
            }
        }

        public static string ApproveUser
        {
            get
            {
                return ResourceManager.GetString("ApproveUser", resourceCulture);
            }
        }

        public static string DescriptionApproveUser
        {
            get
            {
                return ResourceManager.GetString("DescriptionApproveUser", resourceCulture);
            }
        }

        public static string AccessSetting
        {
            get
            {
                return ResourceManager.GetString("AccessSetting", resourceCulture);
            }
        }

        public static string EditAccessSetting
        {
            get
            {
                return ResourceManager.GetString("EditAccessSetting", resourceCulture);
            }
        }

        public static string DescriptionEditAccessSetting
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditAccessSetting", resourceCulture);
            }
        }

        public static string VehicleManagement
        {
            get
            {
                return ResourceManager.GetString("VehicleManagement", resourceCulture);
            }
        }

        public static string CardIssuing
        {
            get
            {
                return ResourceManager.GetString("CardIssuing", resourceCulture);
            }
        }

        public static string CardIssuingSetting
        {
            get
            {
                return ResourceManager.GetString("CardIssuingSetting", resourceCulture);
            }
        }

        public static string CardIssuingLayout
        {
            get
            {
                return ResourceManager.GetString("CardIssuingLayout", resourceCulture);
            }
        }

        public static string AddVehicle
        {
            get
            {
                return ResourceManager.GetString("AddVehicle", resourceCulture);
            }
        }

        public static string ViewVehicle
        {
            get
            {
                return ResourceManager.GetString("ViewVehicle", resourceCulture);
            }
        }

        public static string EditVehicle
        {
            get
            {
                return ResourceManager.GetString("EditVehicle", resourceCulture);
            }
        }

        public static string DescriptionAddVehicle
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddVehicle", resourceCulture);
            }
        }

        public static string DescriptionViewVehicle
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewVehicle", resourceCulture);
            }
        }

        public static string DescriptionEditVehicle
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditVehicle", resourceCulture);
            }
        }

        public static string ViewCardIssuing
        {
            get
            {
                return ResourceManager.GetString("ViewCardIssuing", resourceCulture);
            }
        }

        public static string AddCardIssuing
        {
            get
            {
                return ResourceManager.GetString("AddCardIssuing", resourceCulture);
            }
        }

        public static string EditCardIssuing
        {
            get
            {
                return ResourceManager.GetString("EditCardIssuing", resourceCulture);
            }
        }

        public static string DescriptionAddCardIssuing
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddCardIssuing", resourceCulture);
            }
        }

        public static string DescriptionViewCardIssuing
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewCardIssuing", resourceCulture);
            }
        }

        public static string ViewCardIssuingSetting
        {
            get
            {
                return ResourceManager.GetString("ViewCardIssuingSetting", resourceCulture);
            }
        }

        public static string ViewCardIssuingLayout
        {
            get
            {
                return ResourceManager.GetString("ViewCardIssuingLayout", resourceCulture);
            }
        }

        public static string AddCardIssuingLayout
        {
            get
            {
                return ResourceManager.GetString("AddCardIssuingLayout", resourceCulture);
            }
        }

        public static string AddCardIssuingSetting
        {
            get
            {
                return ResourceManager.GetString("AddCardIssuingSetting", resourceCulture);
            }
        }

        public static string EditCardIssuingSetting
        {
            get
            {
                return ResourceManager.GetString("EditCardIssuingSetting", resourceCulture);
            }
        }

        public static string EditCardIssuingLayout
        {
            get
            {
                return ResourceManager.GetString("EditCardIssuingLayout", resourceCulture);
            }
        }

        public static string DescriptionViewCardIssuingSetting
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewCardIssuingSetting", resourceCulture);
            }
        }

        public static string DescriptionViewCardIssuingLayout
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewCardIssuingLayout", resourceCulture);
            }
        }

        public static string DescriptionAddCardIssuingSetting
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddCardIssuingSetting", resourceCulture);
            }
        }

        public static string DescriptionAddCardIssuingLayout
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddCardIssuingLayout", resourceCulture);
            }
        }

        public static string DescriptionEditCardIssuingSetting
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditCardIssuingSetting", resourceCulture);
            }
        }

        public static string DescriptionEditCardIssuingLayout
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditCardIssuingLayout", resourceCulture);
            }
        }

        public static string DescriptionEditCardIssuing
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditCardIssuing", resourceCulture);
            }
        }

        public static string ViewDashBoard
        {
            get
            {
                return ResourceManager.GetString("ViewDashBoard", resourceCulture);
            }
        }

        public static string DescriptionViewDashBoard
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewDashBoard", resourceCulture);
            }
        }

        public static string DashBoard
        {
            get
            {
                return ResourceManager.GetString("DashBoard", resourceCulture);
            }
        }

        public static string EventManagement
        {
            get
            {
                return ResourceManager.GetString("EventManagement", resourceCulture);
            }
        }

        public static string ViewEventManagement
        {
            get
            {
                return ResourceManager.GetString("ViewEventManagement", resourceCulture);
            }
        }

        public static string AddEventManagement
        {
            get
            {
                return ResourceManager.GetString("AddEventManagement", resourceCulture);
            }
        }

        public static string EditEventManagement
        {
            get
            {
                return ResourceManager.GetString("EditEventManagement", resourceCulture);
            }
        }

        public static string DeleteEventManagement
        {
            get
            {
                return ResourceManager.GetString("DeleteEventManagement", resourceCulture);
            }
        }

        public static string DescriptionViewEventManagement
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewEventManagement", resourceCulture);
            }
        }

        public static string DescriptionAddEventManagement
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddEventManagement", resourceCulture);
            }
        }

        public static string DescriptionEditEventManagement
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditEventManagement", resourceCulture);
            }
        }

        public static string DescriptionDeleteEventManagement
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteEventManagement", resourceCulture);
            }
        }

        public static string LibraryManagement
        {
            get
            {
                return ResourceManager.GetString("LibraryManagement", resourceCulture);
            }
        }

        public static string EditBook
        {
            get
            {
                return ResourceManager.GetString("EditBook", resourceCulture);
            }
        }

        public static string AddBook
        {
            get
            {
                return ResourceManager.GetString("AddBook", resourceCulture);
            }
        }

        public static string DeleteBook
        {
            get
            {
                return ResourceManager.GetString("DeleteBook", resourceCulture);
            }
        }

        public static string DescriptionViewBook
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewBook", resourceCulture);
            }
        }

        public static string DescriptionAddBook
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddBook", resourceCulture);
            }
        }

        public static string DescriptionEditBook
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditBook", resourceCulture);
            }
        }

        public static string DescriptionDeleteBook
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteBook", resourceCulture);
            }
        }

        public static string Book
        {
            get
            {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }

        public static string ViewBook
        {
            get
            {
                return ResourceManager.GetString("ViewBook", resourceCulture);
            }
        }

        public static string LeaveRequest
        {
            get
            {
                return ResourceManager.GetString("LeaveRequest", resourceCulture);
            }
        }

        public static string ViewLeaveRequest
        {
            get
            {
                return ResourceManager.GetString("ViewLeaveRequest", resourceCulture);
            }
        }

        public static string AddLeaveRequest
        {
            get
            {
                return ResourceManager.GetString("AddLeaveRequest", resourceCulture);
            }
        }

        public static string EditLeaveRequest
        {
            get
            {
                return ResourceManager.GetString("EditLeaveRequest", resourceCulture);
            }
        }

        public static string DeleteLeaveRequest
        {
            get
            {
                return ResourceManager.GetString("DeleteLeaveRequest", resourceCulture);
            }
        }

        public static string DescriptionViewLeaveRequest
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewLeaveRequest", resourceCulture);
            }
        }

        public static string DescriptionAddLeaveRequest
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddLeaveRequest", resourceCulture);
            }
        }

        public static string DescriptionEditLeaveRequest
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditLeaveRequest", resourceCulture);
            }
        }

        public static string DescriptionDeleteLeaveRequest
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteLeaveRequest", resourceCulture);
            }
        }

        public static string ViewLeaveManagementLeaveRequest
        {
            get
            {
                return ResourceManager.GetString("ViewLeaveManagementLeaveRequest", resourceCulture);
            }
        }

        public static string DescriptionViewLeaveManagementLeaveRequest
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewLeaveManagementLeaveRequest", resourceCulture);
            }
        }

        public static string UpdateUserSettingUser
        {
            get
            {
                return ResourceManager.GetString("UpdateUserSettingUser", resourceCulture);
            }
        }

        public static string DescriptionUpdateUserSettingUser
        {
            get
            {
                return ResourceManager.GetString("DescriptionUpdateUserSettingUser", resourceCulture);
            }
        }

        public static string UpdateAttendanceSettingAttendance
        {
            get
            {
                return ResourceManager.GetString("UpdateAttendanceSettingAttendance", resourceCulture);
            }
        }

        public static string DescriptionUpdateAttendanceSettingAttendance
        {
            get
            {
                return ResourceManager.GetString("DescriptionUpdateAttendanceSettingAttendance", resourceCulture);
            }
        }

        public static string ViewVehicleAllocation
        {
            get
            {
                return ResourceManager.GetString("ViewVehicleAllocation", resourceCulture);
            }
        }

        public static string DescriptionViewVehicleAllocation
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewVehicleAllocation", resourceCulture);
            }
        }

        public static string AddVehicleAllocation
        {
            get
            {
                return ResourceManager.GetString("AddVehicleAllocation", resourceCulture);
            }
        }

        public static string DescriptionAddVehicleAllocation
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddVehicleAllocation", resourceCulture);
            }
        }

        public static string VehicleAllocation
        {
            get
            {
                return ResourceManager.GetString("VehicleAllocation", resourceCulture);
            }
        }

        public static string EditVehicleAllocation
        {
            get
            {
                return ResourceManager.GetString("EditVehicleAllocation", resourceCulture);
            }
        }

        public static string DescriptionEditVehicleAllocation
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditVehicleAllocation", resourceCulture);
            }
        }

        public static string DeleteVehicleAllocation
        {
            get
            {
                return ResourceManager.GetString("DeleteVehicleAllocation", resourceCulture);
            }
        }

        public static string DescriptionDeleteVehicleAllocation
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteVehicleAllocation", resourceCulture);
            }
        }

        public static string RunVehicleAllocation
        {
            get
            {
                return ResourceManager.GetString("RunVehicleAllocation", resourceCulture);
            }
        }

        public static string DescriptionRunVehicleAllocation
        {
            get
            {
                return ResourceManager.GetString("DescriptionRunVehicleAllocation", resourceCulture);
            }
        }

        public static string UserArmyManagement
        {
            get
            {
                return ResourceManager.GetString("UserArmyManagement", resourceCulture);
            }
        }

        public static string ViewUserArmyManagement
        {
            get
            {
                return ResourceManager.GetString("ViewUserArmyManagement", resourceCulture);
            }
        }

        public static string DescriptionViewUserArmyManagement
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewUserArmyManagement", resourceCulture);
            }
        }

        public static string AddUserArmyManagement
        {
            get
            {
                return ResourceManager.GetString("AddUserArmyManagement", resourceCulture);
            }
        }

        public static string DescriptionAddUserArmyManagement
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddUserArmyManagement", resourceCulture);
            }
        }

        public static string EditUserArmyManagement
        {
            get
            {
                return ResourceManager.GetString("EditUserArmyManagement", resourceCulture);
            }
        }

        public static string DescriptionEditUserArmyManagement
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditUserArmyManagement", resourceCulture);
            }
        }

        public static string DeleteUserArmyManagement
        {
            get
            {
                return ResourceManager.GetString("DeleteUserArmyManagement", resourceCulture);
            }
        }

        public static string DescriptionDeleteUserArmyManagement
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteUserArmyManagement", resourceCulture);
            }
        }

        public static string RegCivilVisitArmyManagement
        {
            get
            {
                return ResourceManager.GetString("RegCivilVisitArmyManagement", resourceCulture);
            }
        }

        public static string RegOtherVisitArmyManagement
        {
            get
            {
                return ResourceManager.GetString("RegOtherVisitArmyManagement", resourceCulture);
            }
        }

        public static string DescriptionRegCivilVisitArmyManagement
        {
            get
            {
                return ResourceManager.GetString("DescriptionRegCivilVisitArmyManagement", resourceCulture);
            }
        }

        public static string DescriptionRegOtherVisitArmyManagement
        {
            get
            {
                return ResourceManager.GetString("DescriptionRegOtherVisitArmyManagement", resourceCulture);
            }
        }

        public static string DescriptionRegiMasterBuilding
        {
            get
            {
                return ResourceManager.GetString("DescriptionRegiMasterBuilding", resourceCulture);
            }
        }

        public static string DescriptionViewMasterBuilding
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewMasterBuilding", resourceCulture);
            }
        }

        public static string ViewMasterBuilding
        {
            get
            {
                return ResourceManager.GetString("ViewMasterBuilding", resourceCulture);
            }
        }

        public static string RegiMasterBuilding
        {
            get
            {
                return ResourceManager.GetString("RegiMasterBuilding", resourceCulture);
            }
        }

        public static string ViewAllReport
        {
            get
            {
                return ResourceManager.GetString("ViewAllReport", resourceCulture);
            }
        }

        public static string DescriptionViewAllReport
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewAllReport", resourceCulture);
            }
        }

        public static string DeleteVehicle
        {
            get
            {
                return ResourceManager.GetString("DeleteVehicle", resourceCulture);
            }
        }

        public static string DescriptionDeleteVehicle
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteVehicle", resourceCulture);
            }
        }

        public static string DeleteCardIssuing
        {
            get
            {
                return ResourceManager.GetString("DeleteCardIssuing", resourceCulture);
            }
        }

        public static string DeleteCardIssuingLayout
        {
            get
            {
                return ResourceManager.GetString("DeleteCardIssuingLayout", resourceCulture);
            }
        }

        public static string DeleteCardIssuingSetting
        {
            get
            {
                return ResourceManager.GetString("DeleteCardIssuingSetting", resourceCulture);
            }
        }

        public static string DescriptionDeleteCardIssuing
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteCardIssuing", resourceCulture);
            }
        }

        public static string DescriptionDeleteCardIssuingLayout
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteCardIssuingLayout", resourceCulture);
            }
        }

        public static string DescriptionDeleteCardIssuingSetting
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteCardIssuingSetting", resourceCulture);
            }
        }

        public static string ManageOwnRecordLeaveRequest
        {
            get
            {
                return ResourceManager.GetString("ManageOwnRecordLeaveRequest", resourceCulture);
            }
        }

        public static string DescriptionManageOwnRecordLeaveRequest
        {
            get
            {
                return ResourceManager.GetString("DescriptionManageOwnRecordLeaveRequest", resourceCulture);
            }
        }


        public static string AccessSchedule
        {
            get
            {
                return ResourceManager.GetString("AccessSchedule", resourceCulture);
            }
        }

        public static string ViewAccessSchedule
        {
            get
            {
                return ResourceManager.GetString("ViewAccessSchedule", resourceCulture);
            }
        }

        public static string DescriptionViewAccessSchedule
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewAccessSchedule", resourceCulture);
            }
        }

        public static string AddAccessSchedule
        {
            get
            {
                return ResourceManager.GetString("AddAccessSchedule", resourceCulture);
            }
        }

        public static string DescriptionAddAccessSchedule
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddAccessSchedule", resourceCulture);
            }
        }
        public static string EditAccessSchedule
        {
            get
            {
                return ResourceManager.GetString("EditAccessSchedule", resourceCulture);
            }
        }

        public static string DescriptionEditAccessSchedule
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditAccessSchedule", resourceCulture);
            }
        }
        public static string DeleteAccessSchedule
        {
            get
            {
                return ResourceManager.GetString("DeleteAccessSchedule", resourceCulture);
            }
        }

        public static string DescriptionDeleteAccessSchedule
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteAccessSchedule", resourceCulture);
            }
        }

        public static string DeviceReader
        {
            get
            {
                return ResourceManager.GetString("DeviceReader", resourceCulture);
            }
        }

        public static string ViewDeviceReader
        {
            get
            {
                return ResourceManager.GetString("ViewDeviceReader", resourceCulture);
            }
        }

        public static string DescriptionViewDeviceReader
        {
            get
            {
                return ResourceManager.GetString("DescriptionViewDeviceReader", resourceCulture);
            }
        }

        public static string AddDeviceReader
        {
            get
            {
                return ResourceManager.GetString("AddDeviceReader", resourceCulture);
            }
        }

        public static string DescriptionAddDeviceReader
        {
            get
            {
                return ResourceManager.GetString("DescriptionAddDeviceReader", resourceCulture);
            }
        }

        public static string EditDeviceReader
        {
            get
            {
                return ResourceManager.GetString("EditDeviceReader", resourceCulture);
            }
        }

        public static string DescriptionEditDeviceReader
        {
            get
            {
                return ResourceManager.GetString("DescriptionEditDeviceReader", resourceCulture);
            }
        }

        public static string DeleteDeviceReader
        {
            get
            {
                return ResourceManager.GetString("DeleteDeviceReader", resourceCulture);
            }
        }

        public static string DescriptionDeleteDeviceReader
        {
            get
            {
                return ResourceManager.GetString("DescriptionDeleteDeviceReader", resourceCulture);
            }
        }

    }
}
